import { Theme } from '@mui/material';

const createBookDemoStyle = (theme: Theme) => ({
 section: {
   paddingTop: { xs: '1rem', sm: '4rem' },
   paddingBottom: { xs: '1rem', sm: '4rem' },
   backgroundColor: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   '&::before': {
     content: '""',
     position: 'absolute',
     top: 0,
     right: 0,
     width: '40%',
     height: '100%',
     opacity: 0.5,
     borderTopLeftRadius: '50%',
     borderBottomLeftRadius: '50%',
     display: { xs: 'none', md: 'block' },
   },
 },
 container: {
   position: 'relative',
   zIndex: 1,
   maxWidth: '1200px',
   margin: '0 auto',
   padding: { xs: '0 0.5rem', sm: '0 2rem' },
 },
 contentBox: {
   display: 'flex',
   flexDirection: { xs: 'column', md: 'row' },
   alignItems: 'center',
   gap: { xs: '2rem', md: '6rem' },
   background: { xs: 'transparent', md: 'transparent' },
   borderRadius: { xs: '0.75rem', md: '2' },
   padding: { xs: '1rem', md: '2' },
   border: { xs: 'none',md:  `1px solid ${theme.palette.divider}` },
 },
 textContainer: {
   flex: { xs: '1', md: '0.6' },
   textAlign: { xs: 'center', md: 'left' },
 },
 tagline: {
   display: 'inline-block',
   padding: { xs: '0.3rem 0.7rem', sm: '0.5rem 1rem' },
   borderRadius: '1rem',
   backgroundColor: '#115e59',
   color: theme.palette.common.white,
   fontWeight: 'bold',
   marginBottom: { xs: '1rem', sm: '1.5rem' },
   fontSize: { xs: '0.75rem', sm: '0.9rem' },
 },
 title: {
   fontSize: { xs: '1.2rem', sm: '2rem' },
   fontWeight: 600,
   marginBottom: { xs: '1rem', sm: '1.5rem' },
   color: theme.palette.text.primary,
 },
 bulletPoints: {
   marginBottom: { xs: '1.5rem', sm: '2rem' },
 },
 bulletItem: {
   display: 'flex',
   alignItems: 'flex-start',
   marginBottom: { xs: '0.75rem', sm: '1rem' },
   textAlign: 'left',
 },
 bulletIcon: {
   color: theme.palette.secondary.main,
   marginRight: '0.75rem',
   fontSize: { xs: '1rem', sm: '1.25rem' },
   marginTop: '0.1rem',
 },
 bulletText: {
   fontSize: { xs: '0.85rem', sm: '1rem' },
   color: theme.palette.text.secondary,
   lineHeight: 1.6,
 },
 button: {
   backgroundColor: '#115e59',
   color: '#f9fafb',
   fontWeight: '600',
   padding: { xs: '0.5rem 1.5rem', sm: '0.75rem 2rem' },
   fontSize: { xs: '0.85rem', sm: '1rem' },
   borderRadius: '0.5rem',
   border: '1px solid #0d9488',
   textTransform: 'none' as const,
   '&:hover': {
     backgroundColor: '#0f766e',
   },
 },
 imageContainer: {
   flex: { xs: '1', md: '0.4' },
   width: '100%',
   display: { xs: 'none', md: 'flex' },
   justifyContent: 'center',
   alignItems: 'center',
 },
 image: {
   width: '100%',
   maxWidth: { xs: '300px', sm: '400px' },
   height: 'auto',
   borderRadius: { xs: '0.75rem', sm: '1rem' },
   boxShadow: theme.shadows[4],
 },
 imagePlaceholder: {
   width: '100%',
   maxWidth: { xs: '300px', sm: '400px' },
   height: { xs: '200px', sm: '300px' },
   borderRadius: { xs: '0.75rem', sm: '1rem' },
   backgroundColor: theme.palette.background.default,
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   color: theme.palette.text.secondary,
   border: `1px solid ${theme.palette.divider}`,
 },
});

export default createBookDemoStyle;