const appBarB2BStyles = {
	appBar: {
		backgroundColor: '#101010',
		position: 'fixed',
		zIndex: 10,
		boxShadow: 'none',
		borderBottom: '1px solid rgba(38, 38, 38, 0.6)',
	},
	toolbar: {
		padding: { xs: '0 1rem', md: '0 2rem' },
		minHeight: '1rem',
	},
	navContainer: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
		width: '100%',
		height: '4rem',
	},
	logoContainer: {
		display: 'flex',
		alignItems: 'center',
		flex: { xs: '1', md: '0 0 auto' },
	},
	logo: {
		color: '#f9fafb',
		fontWeight: 700,
		fontSize: { xs: '1rem', md: '1rem' },
		display: 'flex',
		alignItems: 'center',
	},
	logoImage: {
		maxWidth: '32px',
		height: '32px',
	},
	logoPlus: {
		color: '#14b8a6',
		fontSize: { xs: '1.25rem', md: '1.5rem' },
		fontWeight: 'bold',
		marginLeft: '0.25rem',
	},
	navItems: {
		display: { xs: 'none', md: 'flex' },
		alignItems: 'center',
		justifyContent: 'center',
		flex: '1 1 auto',
	},
	navItem: {
		marginLeft: '0.5rem',
		marginRight: '0.5rem',
	},
	navButton: {
		color: '#f9fafb',
		fontSize: { xs: '0.875rem', md: '1rem' },
		textTransform: 'none',
		borderBottom: '0.25rem solid transparent',
		borderRadius: 0,
		padding: { xs: '0.75rem 1rem', md: '1rem 1.5rem' },
		transition: 'all 0.2s ease',
	},
	activeNavButton: {
		color: 'white',
		fontSize: { xs: '0.875rem', md: '1rem' },
		textTransform: 'none',
		borderBottom: '0.25rem solid white',
		borderRadius: 0,
		padding: { xs: '0.75rem 1rem', md: '1rem 1.5rem' },
		transition: 'all 0.2s ease',
	},
	dropdownIcon: {
		fontSize: '1.2rem',
		marginLeft: '0.25rem',
		transition: 'transform 0.2s ease',
	},
	activeDropdownIcon: {
		fontSize: '1.2rem',
		marginLeft: '0.25rem',
		transform: 'rotate(180deg)',
		transition: 'transform 0.2s ease',
	},
	actionButtons: {
		display: { xs: 'none', md: 'flex' },
		alignItems: 'center',
		gap: { xs: '0.5rem', md: '0.75rem' },
		flex: '0 0 auto',
	},
	talkButton: {
		backgroundColor: '#115e59',
		color: '#f9fafb',
		borderRadius: '0.5rem',
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.25rem 0.5rem',
		},
		textTransform: 'none',
		fontSize: '0.75rem',
		whiteSpace: 'nowrap',
		border: '1px solid #0d9488',
		transition: 'all 150ms ease',
		'&:hover': {
			backgroundColor: '#0f766e',
		},

	},
	shopButton: {
		color: '#f9fafb',
		borderRadius: '0.5rem',
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.25rem 0.5rem',
		},
		textTransform: 'none',
		fontSize: '0.75rem',
		whiteSpace: 'nowrap',
		backgroundColor: '#1f2937',
		border: '1px solid #4b5563',
		transition: 'background-color 150ms ease',
		'&:hover': {
			backgroundColor: '#374151',
			borderColor: '#4b5563',
		},
	},
	mobileMenuContainer: {
		display: { xs: 'flex', md: 'none' },
		justifyContent: 'flex-end',
		flex: '1 0 auto',
	},
	menuIcon: {
		color: '#f9fafb',
		padding: '0.5rem',
	},
	drawer: {
		'& .MuiDrawer-paper': {
			width: '100%',
			height: '100%',
			overflowY: 'auto',
			backgroundColor: '#0a0a0a',
			'&::-webkit-scrollbar': {
				display: 'none',
			},
			msOverflowStyle: 'none',
			scrollbarWidth: 'none',
		},
	},
	drawerContent: {
		display: 'flex',
		flexDirection: 'column',
		height: 'auto',
		minHeight: '100%',
		backgroundColor: '#0a0a0a',
		overflowY: 'auto',
		'&::-webkit-scrollbar': {
			display: 'none',
		},
		msOverflowStyle: 'none',
		scrollbarWidth: 'none',
	},
	mobileMenuHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '0.75rem 1rem',
		borderBottom: '1px solid #262626',
		backgroundColor: '#0a0a0a',
	},
	mobileLogoContainer: {
		display: 'flex',
		alignItems: 'center',
	},
	mobileLogo: {
		color: '#f9fafb',
		fontWeight: 700,
		fontSize: '1rem',
		display: 'flex',
		alignItems: 'center',
	},
	mobileLogoImage: {
		maxWidth: '40px',
		height: '40px',
		marginRight: '0.5rem',
	},
	mobileHeaderActions: {
		display: 'flex',
		alignItems: 'center',
		gap: '0.75rem',
	},
	closeButton: {
		color: '#f9fafb',
		padding: '0.375rem',
	},
	mobileMenuList: {
		padding: 1,
		backgroundColor: '#0a0a0a',
	},
	mobileMenuItem: {
		padding: '1.5rem',
		borderBottom: '1px solid #262626',
		'& .MuiListItemText-primary': {
			fontWeight: 700,
			fontSize: '1.2rem',
			color: '#f9fafb',
		},
		cursor: 'pointer',
	},
	activeMobileMenuItem: {
		backgroundColor: '#1f1f1f',
		'& .MuiListItemText-primary': {
			color: '#14b8a6',
		},
	},
	arrowContainer: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#1f1f1f',
		borderRadius: '6px',
		width: '40px',
		height: '40px',
	},
	mobileMenuArrow: {
		color: '#f9fafb',
		fontSize: '1.2rem',
	},
	mobileLoginButtonContainer: {
		padding: '1.5rem',
		backgroundColor: '#0a0a0a',
		display: 'flex',
		justifyContent: 'center',
	},
	mobileTalkButton: {
		borderColor: '#262626',
		color: '#f9fafb',
		width: '100%',
		padding: '0.625rem 1rem',
		textTransform: 'none',
		fontSize: '0.875rem',
		borderRadius: '0.25rem',
	},
	mobileDivider: {
		height: '1px',
		backgroundColor: '#262626',
		width: '100%',
		margin: '0.5rem 0',
	},
	mobileFeatureCardContainer: {
		padding: '1rem',
		display: 'flex',
		flexDirection: 'column',
		width: '100%',
	},
	mobileImageContainer: {
		width: '100%',
		height: 'auto',
		marginBottom: '1rem',
		borderRadius: '8px',
		overflow: 'hidden',
		backgroundColor: '#1f1f1f',
	},
	mobilePlaceholder: {
		display: 'none',
	},
	mobileFeatureText: {
		fontSize: '1rem',
		fontWeight: 500,
		color: '#f9fafb',
		marginBottom: '0.25rem',
	},
	mobileFeatureSubtext: {
		fontSize: '0.875rem',
		color: '#9ca3af',
		marginBottom: '1rem',
	},
	knowMoreButton: {
		color: '#14b8a6',
		textTransform: 'none',
		padding: 0,
		fontSize: '0.9375rem',
		fontWeight: 500,
		justifyContent: 'flex-start',
		'&:hover': {
			backgroundColor: 'transparent',
			textDecoration: 'underline',
		},
		'& .MuiButton-endIcon': {
			marginLeft: '0.25rem',
		},
	},
	mobileMenuTitle: {
		fontWeight: 500,
		fontSize: '1rem',
		color: '#f9fafb',
	},
	backButton: {
		color: '#f9fafb',
		padding: '0.375rem',
	},
	mobileSubmenuItem: {
		padding: '1rem',
		borderBottom: '1px solid #262626',
		cursor: 'pointer',
	},
	mobileSubmenuText: {
		fontWeight: 500,
		fontSize: '0.9375rem',
		color: '#f9fafb',
	},
	serviceItemContainer: {
		display: 'flex',
		padding: '1rem',
		borderRadius: '0',
		backgroundColor: 'transparent',
		marginBottom: '1rem',
		cursor: 'pointer',
		boxShadow: 'none',
		border: 'none',
	},
	serviceIconWrapper: {
		color: '#14b8a6',
		width: '2.5rem',
		height: '2.5rem',
		marginRight: '1rem',
		display: 'flex',
		alignItems: 'flex-start',
		justifyContent: 'center',
		flexShrink: 0,
		'& svg': {
			fontSize: '2.5rem',
		},
	},
	serviceContent: {
		flex: 1,
	},
	serviceTitle: {
		fontSize: '0.875rem',
		fontWeight: 500,
		color: '#f9fafb',
		marginBottom: '0.25rem',
	},
	serviceDescription: {
		fontSize: '0.875rem',
		color: '#9ca3af',
		lineHeight: 1.5,
	},
	mobileServiceList: {
		padding: '1rem',
		overflow: 'auto',
		flex: 1,
		backgroundColor: '#0a0a0a',
	},
	mobileFeatureCard: {
		padding: '1.5rem',
		backgroundColor: '#0a0a0a',
		margin: '1rem',
		borderRadius: '0.25rem',
	},
	featureCardHeading: {
		fontSize: '1.125rem',
		fontWeight: 500,
		color: '#f9fafb',
		marginBottom: '0.5rem',
	},
	featureCardText: {
		fontSize: '0.875rem',
		color: '#9ca3af',
		marginBottom: '1.5rem',
	},
	dropdownContainer: {
		position: 'fixed',
		top: '4rem',
		left: 0,
		right: 0,
		backgroundColor: '#121212',
		zIndex: 5,
		boxShadow: '0 0.25rem 0.5rem rgba(0, 0, 0, 0.3)',
		maxHeight: 'calc(100vh - 8rem)',
		overflowY: 'auto',
		'&::-webkit-scrollbar': {
			display: 'none',
		},
		msOverflowStyle: 'none',
		scrollbarWidth: 'none',
		padding: 0,
		margin: 0,
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		transition: 'opacity 0.2s ease, transform 0.2s ease',
		transform: 'translateY(0)',
		opacity: 1,
	},
	sidebarContainer: {
		width: { xs: '100%', md: '280px' },
		backgroundColor: '#0a0a0a',
		minHeight: { xs: 'auto', md: '400px' },
		flexShrink: 0,
	},
	contentContainer: {
		width: '100%',
		maxWidth: { xs: '100%', md: '800px' },
		padding: { xs: '1rem 1.5rem', md: '1.5rem 2rem' },
		flexShrink: 0,
		overflowY: 'auto',
		'&::-webkit-scrollbar': {
			display: 'none',
		},
		msOverflowStyle: 'none',
		scrollbarWidth: 'none',
	},
	rightSideContainer: {
		width: { xs: '100%', md: '280px' },
		backgroundColor: '#121212',
		padding: { xs: '0 1.5rem 1.5rem', md: '0 1.5rem 1.5rem' },
		flexGrow: 1,
	},
	headerSpacer: {
		flexGrow: 1,
	},
	menuBox: {
		width: '100%',
		padding: '1.5rem',
		backgroundColor: '#121212',
	},
};

export default appBarB2BStyles;