import theme from '../../../../theme';

const workflowSectionStyle = {
	box: {
		paddingTop: { sm: '1.5rem', xs: '1rem' },
		paddingBottom: { sm: '2rem', xs: '1.5rem' },
		marginTop: '0rem',
		backgroundColor: theme.palette.background.default,
	},
	workflowOuterContainer: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
		paddingX: { xs: '1rem', sm: '2rem' },
	},
	workflowContainer: {
		display: 'flex',
		flexDirection: 'column' as const,
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center' as const,
		background: theme.palette.background.paper,
		borderRadius: '2rem',
		width: '100%',
		maxWidth: '72rem',
		marginX: 'auto',
		padding: { xs: '2rem', sm: '3rem 2rem' },
		border: `1px solid ${theme.palette.divider}`,
		boxShadow: theme.customShadows?.card,
	},
	gridWrapper: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
		width: '100%',
	},
	leftSection: {
		display: 'flex',
		flexDirection: 'column' as const,
		alignItems: 'flex-start',
		justifyContent: 'center',
		textAlign: 'left' as const,
		gap: '1rem',
	},
	rightSection: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'left' as const,
	},
	chip: {
		background: theme.palette.primary.main,
		color: theme.palette.text.primary,
		fontWeight: 'bold',
		borderRadius: '1rem',
		padding: '0.4rem 1rem',
		boxShadow: '0rem 0.25rem 0.375rem rgba(0, 0, 0, 0.1)',
		fontSize: '0.9rem',
	},
	title: {
		fontWeight: '600',
		color: theme.palette.text.primary,
		fontSize: { xs: '1.6rem', sm: '2rem' },
	},
	description: {
		color: theme.palette.text.secondary,
		fontSize: { xs: '1rem', md: '1.1rem' },
		lineHeight: '1.6',
		maxWidth: '100%',
	},
	gridContainer: {
		width: '100%',
		display: 'flex',
		justifyContent: 'center',
		alignItems: { xs: 'center', sm: 'stretch' },
		flexDirection: { xs: 'column', sm: 'row' },
		flexWrap: 'wrap' as const,
		paddingTop: '2rem',
		gap: '1rem',
	},
	card: {
		flex: '1 1 auto',
		minWidth: '12rem',
		maxWidth: '13rem',
		display: 'flex',
		flexDirection: 'column' as const,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: theme.palette.background.default,
		borderRadius: '1rem',
		boxShadow: theme.customShadows?.card,
		padding: '1.5rem',
		transition: 'transform 0.3s ease, box-shadow 0.3s ease',
		border: `1px solid ${theme.palette.divider}`,
		'&:hover': {
			transform: 'scale(1.05)',
			boxShadow: '0rem 0.5rem 1.25rem rgba(0, 0, 0, 0.6)',
		},
	},
	cardContent: {
		display: 'flex',
		flexDirection: 'column' as const,
		alignItems: 'center',
		justifyContent: 'center',
		gap: '1rem',
		flex: 1,
	},
	iconContainer: {
		width: '6rem',
		height: '5rem',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		borderRadius: '50%',
		padding: '0.5rem',
	},
	icon: {
		fontSize: '3rem',
		color: theme.palette.text.primary,
	},
	cardTitle: {
		fontSize: '1rem',
		fontWeight: 'bold' as const,
		color: theme.palette.text.primary,
		textAlign: 'center' as const,
	},
};

export default workflowSectionStyle;