import theme from '../../../theme';

const benefitsSectionStyle = {
  box: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    paddingBottom: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
    position: 'relative',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginX: 'auto',
    maxWidth: '1200px',
    px: { xs: '1rem', sm: '2rem' },
    position: 'relative',
    zIndex: 1,
  },
  containerBox: {
    textAlign: 'center',
    width: '100%',
    maxWidth: '60rem',
    marginX: 'auto',
    marginBottom: '2rem',
  },
  heading: {
    fontWeight: '600',
    fontSize: { xs: '1.8rem', sm: '2.5rem', md: '2rem' },
    color: theme.palette.text.primary,
    paddingBottom: { sm: '1rem', xs: '0.75rem' },
    position: 'relative',
  },
  subheading: {
    color: theme.palette.text.secondary,
    fontSize: { xs: '1rem', md: '1.2rem' },
    marginTop: '1rem',
    marginBottom: '2rem',
    lineHeight: '1.6',
    maxWidth: '40rem',
    marginX: 'auto',
  },
  benefitsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(3, 1fr)',
    },
    gap: '1.75rem',
    width: '100%',
  },
  benefitCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    backgroundColor: '#17171799',
    backdropFilter: 'blur(6px)',
    borderRadius: '1rem',
    padding: '1.75rem',
    height: { sm: '18rem', xs: 'auto', md: '18rem' },
    transition: 'all 0.35s ease',
    justifyContent: 'flex-start',
    position: 'relative',
    overflow: 'hidden',
    border: `1px solid ${theme.palette.divider}`,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '0',
      background: `linear-gradient(90deg, ${theme.palette.secondary.dark}80, ${theme.palette.secondary.main}80)`,
      borderTopLeftRadius: '1rem',
      borderTopRightRadius: '1rem',
      transition: 'height 0.35s ease',
      zIndex: 0,
    },
    '&:hover': {
      transform: 'translateY(-8px)',
      boxShadow: '0rem 0.75rem 1.5rem rgba(0, 0, 0, 0.15)',
      backgroundColor: theme.palette.background.paper,
      '&::before': {
        height: '4px',
      },
    },
  },
  iconContainer: {
    width: '50px',
    height: '50px',
    borderRadius: '8px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#115e59',
    marginBottom: '1.25rem',
    position: 'relative',
    transition: 'all 0.3s ease',
    alignSelf: 'flex-start',
    zIndex: 1,
  },
  icon: {
    fontSize: '24px',
    color: 'white',
    transition: 'transform 0.3s ease',
    width: '24px',
    height: '24px',
  },
  benefitTitle: {
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: 'left',
    fontSize: { xs: '1.1rem', sm: '1.2rem' },
    marginBottom: '0.75rem',
    position: 'relative',
    zIndex: 1,
  },
  benefitDescription: {
    color: theme.palette.text.secondary,
    textAlign: 'left',
    lineHeight: 1.7,
    fontSize: '1rem',
    position: 'relative',
    zIndex: 1,
  },
};

export default benefitsSectionStyle;