import theme from '../../../theme';

const callToActionSectionStyle = {
	box: {
		paddingTop: { sm: '4rem', xs: '2rem' },
		paddingBottom: { sm: '4rem', xs: '2rem' },
		background: theme.palette.background.default,
		position: 'relative',
		overflow: 'hidden',
	},
	container: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		marginX: 'auto',
		maxWidth: '1200px',
		px: { xs: '1rem', sm: '2rem' },
		position: 'relative',
		zIndex: 1,
	},
	contentWrapper: {
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		alignItems: 'center',
		gap: { xs: '2rem', md: '3rem' },
		backgroundColor: `${theme.palette.background.default}DD`,
		backdropFilter: 'blur(10px)',
		borderRadius: '1rem',
		padding: { xs: '2rem', md: '3rem' },
		border: `1px solid ${theme.palette.divider}`,
		boxShadow: '0 10px 30px rgba(0, 0, 0, 0.15)',
		position: 'relative',
		overflow: 'hidden',
		'&::before': {
			content: '""',
			position: 'absolute',
			top: 0,
			left: 0,
			width: '100%',
			height: '6px',
			background: `linear-gradient(90deg, #115e59, ${theme.palette.secondary.main})`,
			borderTopLeftRadius: '1rem',
			borderTopRightRadius: '1rem',
		},
	},
	textContent: {
		flex: '1.2',
		display: 'flex',
		flexDirection: 'column',
		alignItems: { xs: 'center', md: 'flex-start' },
		textAlign: { xs: 'center', md: 'left' },
	},
	title: {
		fontWeight: '600',
		fontSize: { xs: '1.8rem', sm: '2.5rem',md:'2rem' },
		color: theme.palette.text.primary,
		marginBottom: '1rem',
		position: 'relative',
		paddingBottom: '0.75rem',
		'&::after': {
			content: '""',
			position: 'absolute',
			bottom: 0,
			left: { xs: '50%', md: '0' },
			transform: { xs: 'translateX(-50%)', md: 'translateX(0)' },
			width: '4rem',
			height: '4px',
			background: `linear-gradient(90deg, #115e59, ${theme.palette.secondary.light})`,
			borderRadius: '2px',
		},
	},
	subtitle: {
		color: theme.palette.text.secondary,
		fontSize: { xs: '1.1rem', md: '1.2rem' },
		fontWeight: '500',
		marginBottom: '1.5rem',
	},
	description: {
		color: theme.palette.text.secondary,
		fontSize: '1rem',
		lineHeight: 1.7,
		marginBottom: '2rem',
		maxWidth: '500px',
	},
	featureList: {
		marginBottom: '2rem',
		display: 'flex',
		flexDirection: 'column',
		gap: '0.75rem',
		alignItems: { xs: 'center', md: 'flex-start' },
	},
	featureItem: {
		display: 'flex',
		alignItems: 'center',
		gap: '0.75rem',
	},
	featureIcon: {
		color: '#115e59',
		fontSize: '1.25rem',
	},
	featureText: {
		color: theme.palette.text.secondary,
		fontSize: '1rem',
	},
	button: {
		marginTop: '1rem',
		backgroundColor: '#115e59',
		color: '#f9fafb',
		borderRadius: '0.5rem',
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.25rem 1rem',
		},
		textTransform: 'none',
		fontSize: '1rem',
		whiteSpace: 'nowrap',
		border: '1px solid #0d9488',
		transition: 'all 150ms ease',
		'&:hover': {
			backgroundColor: '#0f766e',
		},
	},
	imageContainer: {
		flex: 1,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		position: 'relative',
	},
	placeholderImage: {
		width: '100%',
		maxWidth: '400px',
		height: '280px',
		borderRadius: '1rem',
		backgroundColor: `${theme.palette.background.darkPaper}99`,
		backdropFilter: 'blur(10px)',
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		color: theme.palette.text.secondary,
		fontSize: '1rem',
		border: `1px solid ${theme.palette.divider}`,

		padding: '1rem',
		textAlign: 'center',
		position: 'relative',
		overflow: 'hidden',
		'&::before': {
			content: '""',
			position: 'absolute',
			bottom: 0,
			left: 0,
			width: '100%',
			height: '4px',
			background: `linear-gradient(90deg, #115e59, ${theme.palette.secondary.light}60)`,
		},
		'&::after': {
			content: '""',
			position: 'absolute',
			top: 0,
			right: 0,
			width: '70px',
			height: '70px',
			background: `radial-gradient(circle, ${theme.palette.secondary.main}30, transparent 70%)`,
			borderRadius: '50%',
			zIndex: -1,
		},
		animation: 'pulse 2s infinite ease-in-out',
		'@keyframes pulse': {
			'0%': { transform: 'scale(1)' },
			'50%': { transform: 'scale(1.02)' },
			'100%': { transform: 'scale(1)' },
		},
	},
};

export default callToActionSectionStyle;
