import theme from '../../../theme';

const featuresSectionStyle = {
  box: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    paddingBottom: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.darkPaper,
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '10%',
      right: '5%',
      width: '20%',
      height: '35%',
      background: `radial-gradient(circle, ${theme.palette.secondary.dark}15, transparent 70%)`,
      borderRadius: '50%',
      pointerEvents: 'none',
      zIndex: 0,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: '20%',
      left: '5%',
      width: '15%',
      height: '25%',
      background: `radial-gradient(circle, ${theme.palette.secondary.main}10, transparent 70%)`,
      borderRadius: '50%',
      pointerEvents: 'none',
      zIndex: 0,
    },
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginX: 'auto',
    maxWidth: '1200px',
    px: { xs: '1rem', sm: '2rem' },
    position: 'relative',
    zIndex: 1,
  },
  containerBox: {
    textAlign: 'center',
    width: '100%',
    maxWidth: '60rem',
    marginX: 'auto',
    marginBottom: '2.5rem',
  },
  heading: {
    fontWeight: '600',
    fontSize: { xs: '1.8rem', sm: '2.5rem' },
    color: theme.palette.text.primary,
    paddingBottom: { sm: '1rem', xs: '0.75rem' },
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: '50%',
      transform: 'translateX(-50%)',
      width: '4rem',
      height: '4px',
      background: `linear-gradient(90deg, ${theme.palette.secondary.dark}, ${theme.palette.secondary.light})`,
      borderRadius: '2px',
    },
  },
  subheading: {
    color: theme.palette.text.secondary,
    fontSize: { xs: '1rem', md: '1.2rem' },
    marginTop: '1rem',
    marginBottom: '1rem',
    lineHeight: '1.6',
    maxWidth: '40rem',
    marginX: 'auto',
  },
  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(4, 1fr)',
    },
    gap: '1.5rem',
    width: '100%',
  },
  featureCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#17171799',
    backdropFilter: 'blur(6px)',
    borderRadius: '1rem',
    padding: '1.75rem 1.5rem',
    height: { sm: '16rem', xs: 'auto', md: '17rem' },
    transition: 'all 0.35s ease',
    justifyContent: 'flex-start',
    position: 'relative',
    overflow: 'hidden',

    border: `1px solid ${theme.palette.divider}`,
    '&:hover': {
      transform: 'translateY(-10px)',
      boxShadow: '0rem 0.8rem 2rem rgba(0, 0, 0, 0.2)',
      backgroundColor: theme.palette.background.paper,
      '& .feature-icon': {
        transform: 'rotate(10deg) scale(1.1)',
        backgroundColor: theme.palette.secondary.dark,
      },
    },
  },
  iconContainer: {
    width: '4rem',
    height: '4rem',
    borderRadius: '0.5rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#115e59',

    marginBottom: '1.25rem',
    position: 'relative',
    transition: 'all 0.5s ease',
    zIndex: 1,
  },
  icon: {
    fontSize: '2rem',
    color: theme.palette.text.primary,
    transition: 'transform 0.5s ease',
  },
  typography: {
    container: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
    },
    title: {
      fontWeight: 'bold',
      color: theme.palette.text.primary,
      textAlign: 'center',
      fontSize: { xs: '1.1rem', sm: '1.2rem' },
      marginBottom: '0.75rem',
    },
    body: {
      color: theme.palette.text.secondary,
      textAlign: 'center',
      lineHeight: 1.7,
      fontSize: '1rem',
    },
  },
  featureTitle: {
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: 'center',
    fontSize: { xs: '1.1rem', sm: '1.2rem' },
    marginBottom: '0.75rem',
  },
  featureDescription: {
    color: theme.palette.text.secondary,
    textAlign: 'center',
    lineHeight: 1.7,
    fontSize: '1rem',
  },
};

export default featuresSectionStyle;
