import theme from '../../../theme';

const heroSectionStyle = {
	section: {
		paddingTop: { sm: '4rem', xs: '2rem' },
		paddingBottom: { sm: '4rem', xs: '2rem' },
		backgroundColor: theme.palette.background.default,
		position: 'relative',
		overflow: 'hidden',
	},
	container: {
		maxWidth: '1200px',
		margin: '0 auto',
		padding: { xs: '0 1rem', sm: '0 2rem' },
	},
	containerBox: {
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		justifyContent: 'space-between',
		alignItems: 'center',
		width: '100%',
		gap: { xs: '2rem', sm: '3rem' },
	},
	contentBox: {
		flex: 1,
		textAlign: { xs: 'center', md: 'left' },
		display: 'flex',
		flexDirection: 'column',
		gap: '1rem',
		alignItems: { xs: 'center', md: 'flex-start' },
		position: 'relative',
		zIndex: 2,
	},
	tagline: {
		display: 'inline-flex',
		alignItems: 'center',
		padding: '0.4rem 1rem',
		borderRadius: '1.3rem',
		fontSize: '0.9rem',
		marginBottom: '1rem',
		background: '#115e59',
		color: theme.palette.text.primary,
		fontWeight: 'bold',
		width: { xs: 'auto', sm: 'fit-content' },
		textAlign: 'center',
		whiteSpace: 'nowrap',
		transition: 'all 0.3s ease',
		marginTop: '2rem',
	},
	title: {
		fontWeight: '600',
		fontSize: { xs: '1.8rem', sm: '2.5rem' },
		color: theme.palette.text.primary,
		lineHeight: 1.3,
		position: 'relative',
		paddingBottom: '0.75rem',
	},
	subtitle: {
		fontSize: { xs: '1.1rem', md: '1.3rem' },
		color: '#115e59',
		lineHeight: 1.6,
		fontWeight: 500,
		marginTop: '0.5rem',
	},
	description: {
		fontSize: '1rem',
		lineHeight: 1.7,
		color: theme.palette.text.secondary,
		marginTop: '0.5rem',
		maxWidth: { xs: '100%', md: '36rem' },
	},
	ctaButton: {
		marginTop: '1rem',
		backgroundColor: '#115e59',
		color: '#f9fafb',
		borderRadius: '0.5rem',
		padding: {
			xs: '0.5rem 1rem',
			sm: '0.5rem 1.5rem',
			md: '0.5rem 2rem',
		},
		textTransform: 'none',
		fontSize: { xs: '0.9rem', sm: '1rem' },
		whiteSpace: 'nowrap',
		border: '1px solid #0d9488',
		transition: 'all 150ms ease',
		'&:hover': {
			backgroundColor: '#0f766e',
		},
	},
	imageBox: {
		flex: { xs: '1', md: '1' },
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: { xs: '1rem', sm: '1rem' },
		width: '100%',
		position: 'relative',
		zIndex: 1,
		maxWidth: { xs: '100%', md: 'unset' },
	},
	heroImageContainer: {
		width: { xs: '100%', sm: '500px', md: '35rem' },
		height: { xs: '320px', sm: '350px', md: '34rem' },
		borderRadius: { xs: '0.5rem', sm: '1rem' },
		overflow: 'hidden',
		position: 'relative',
		transition: 'all 0.3s ease',
		'&:hover': {
			boxShadow: '0px 8px 20px rgba(0, 0, 0, 0.2)',
			transform: 'translateY(-4px)',
		},
		'&::before': {
			content: '""',
			position: 'absolute',
			top: '-10px',
			right: '-10px',
			width: '100px',
			height: '100px',
			background: `radial-gradient(circle, ${theme.palette.secondary.main}40, transparent 70%)`,
			borderRadius: '50%',
			zIndex: 1,
		},
		margin: { xs: '0 auto', md: '0' },
		maxWidth: '100%',
		aspectRatio: { xs: '16/9', md: 'auto' },
	},
	heroImage: {
		objectFit: 'cover' as const,
		objectPosition: 'center',
	},
	imagePlaceholder: {
		width: '100%',
		maxWidth: { xs: '100%', sm: '500px', md: '34rem' },
		height: { xs: '350px', sm: '350px', md: '18rem' },
		borderRadius: '1rem',
		backgroundColor: `${theme.palette.background.paper}BB`,
		backdropFilter: 'blur(8px)',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		color: theme.palette.text.secondary,
		border: `1px solid ${theme.palette.divider}`,
		background: `linear-gradient(135deg, ${theme.palette.background.paper}BB, ${theme.palette.background.darkPaper}99)`,
		padding: '1rem',
		textAlign: 'center',
		transition: 'all 0.3s ease',
		'&:hover': {
			boxShadow: '0px 8px 20px rgba(0, 0, 0, 0.2)',
			transform: 'translateY(-4px)',
		},
		position: 'relative',
		'&::before': {
			content: '""',
			position: 'absolute',
			top: '-10px',
			right: '-10px',
			width: '100px',
			height: '120px',
			background: `radial-gradient(circle, ${theme.palette.secondary.main}40, transparent 70%)`,
			borderRadius: '50%',
			zIndex: -1,
		},
	},
};

export default heroSectionStyle;