import theme from '../../../theme';

const heroSectionStyle = {
  section: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    paddingBottom: { sm: '3rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      background: `radial-gradient(circle at 70% 30%, ${theme.palette.secondary.main}15, transparent 45%)`,
      pointerEvents: 'none',
    },
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: { xs: '0 1rem', sm: '0 2rem' },
  },
  containerBox: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    gap: { xs: '2rem', sm: '3rem' },
  },
  contentBox: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    alignItems: { xs: 'center', md: 'flex-start' },
    position: 'relative',
    zIndex: 2,
  },
  tagline: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0.4rem 1rem',
    borderRadius: '1.3rem',
    fontSize: '0.9rem',
    marginBottom: '1rem',
    background: theme.palette.secondary.dark,
    color: theme.palette.text.primary,
    fontWeight: 'bold',
    width: { xs: 'auto', sm: 'fit-content' },
    textAlign: 'center',
    whiteSpace: 'nowrap',
    transition: 'all 0.3s ease',

    '&:hover': {
      boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.15)',
      transform: 'translateY(-2px)',
    },
  },
  title: {
    fontWeight: '600',
    fontSize: { xs: '1.8rem', sm: '2.5rem' },
    color: theme.palette.text.primary,
    lineHeight: 1.3,
    position: 'relative',
    paddingBottom: '0.75rem',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: { xs: '50%', md: '0' },
      transform: { xs: 'translateX(-50%)', md: 'translateX(0)' },
      width: '4rem',
      height: '4px',
      background: `linear-gradient(90deg, ${theme.palette.secondary.dark}, ${theme.palette.secondary.light})`,
      borderRadius: '2px',
    },
  },
  subtitle: {
    fontSize: { xs: '1.1rem', md: '1.3rem' },
    color: theme.palette.secondary.dark,
    lineHeight: 1.6,
    fontWeight: 500,
    marginTop: '0.5rem',
  },
  description: {
    fontSize: '1rem',
    lineHeight: 1.7,
    color: theme.palette.text.secondary,
    marginTop: '0.5rem',
    maxWidth: '36rem',
  },
  ctaButton: {
    marginTop: '1.5rem',
    color: theme.palette.text.primary,
    fontWeight: 800,
    padding: {
      xs: '0.5rem 1.25rem',
      sm: '0.6rem 1.5rem',
      md: '0.75rem 1.75rem',
    },
    borderRadius: '0.5rem',
    backgroundColor: theme.palette.secondary.dark,
    border: `1px solid ${theme.palette.secondary.main}`,
    textTransform: 'none',
    fontSize: '1rem',
    whiteSpace: 'nowrap',
    transition: 'all 0.3s ease',

    '&:hover': {
      backgroundColor: theme.palette.secondary.main,
      borderColor: theme.palette.secondary.light,
      transform: 'translateY(-2px)',
      boxShadow: '0px 8px 15px rgba(0, 0, 0, 0.15)',
    },
    '&.Mui-disabled': {
      color: theme.palette.text.primary,
      opacity: 0.5,
      backgroundColor: theme.palette.secondary.dark,
      border: `1px solid ${theme.palette.secondary.main}`,
    },
  },
  imageBox: {
    flex: 1,
    display: 'flex',
    justifyContent: { xs: 'center', md: 'flex-end' },
    alignItems: 'center',
    marginTop: { xs: '1rem', sm: '1rem' },
    textAlign: 'center',
    width: '100%',
    position: 'relative',
    zIndex: 1,
  },
  imagePlaceholder: {
    width: '100%',
    maxWidth: '34rem',
    minHeight: '18rem',
    borderRadius: '1rem',
    backgroundColor: `${theme.palette.background.paper}BB`,
    backdropFilter: 'blur(8px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: theme.palette.text.secondary,
    border: `1px solid ${theme.palette.divider}`,

    background: `linear-gradient(135deg, ${theme.palette.background.paper}BB, ${theme.palette.background.darkPaper}99)`,
    padding: '1rem',
    textAlign: 'center',
    transition: 'all 0.3s ease',
    '&:hover': {
      boxShadow: '0px 8px 20px rgba(0, 0, 0, 0.2)',
      transform: 'translateY(-4px)',
    },
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '-10px',
      right: '-10px',
      width: '100px',
      height: '100px',
      background: `radial-gradient(circle, ${theme.palette.secondary.main}40, transparent 70%)`,
      borderRadius: '50%',
      zIndex: -1,
    },
  },
};

export default heroSectionStyle;
