import theme from '../../../theme';

const processSectionStyle = {
  box: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
    position: 'relative',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginX: 'auto',
    position: 'relative',
    zIndex: 1,
  },
  containerBox: {
    textAlign: 'center',
    width: '100%',
    maxWidth: '60rem',
    marginX: 'auto',
    marginBottom: '3rem',
  },
  heading: {
    fontWeight: '600',
    fontSize: { xs: '1.8rem', sm: '2.5rem', md: '2rem' },
    color: theme.palette.text.primary,
    paddingBottom: { sm: '1rem', xs: '0.75rem' },
  },
  subheading: {
    color: theme.palette.text.secondary,
    fontSize: { xs: '1rem', md: '1.1rem' },
    lineHeight: '1.6',
    maxWidth: '40rem',
    marginX: 'auto',
  },
  processTimeline: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '2rem',
  },
  lineContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
    width: '100%',
    maxWidth: '900px',
    margin: '0 auto',
    padding: '0 1.5rem',
  },
  connectingLine: {
    position: 'absolute',
    top: '50%',
    left: '8%',
    right: '8%',
    height: '2px',
    backgroundColor: '#115e5980',
    zIndex: 0,
  },
  stepNumber: {
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#115e59',
    color: 'white',
    borderRadius: '50%',
    fontWeight: 'bold',
    fontSize: '1.25rem',
    zIndex: 2,
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.2)',
    position: 'relative',
  },
  cardsContainer: {
    width: '100%',
  },
  stepCard: {
    backgroundColor: '#17171799',
    backdropFilter: 'blur(6px)',
    borderRadius: '1rem',
    padding: '1.75rem',
    height: '100%',
    minHeight: '220px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    border: `1px solid ${theme.palette.divider}`,
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    '&:hover': {
      transform: 'translateY(-8px)',
      boxShadow: '0 10px 25px rgba(0, 0, 0, 0.2)',
    },
  },
  iconContainer: {
    width: '60px',
    height: '60px',
    backgroundColor: '#115e59',
    borderRadius: '8px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  icon: {
    fontSize: '30px',
    color: 'white',
  },
  stepHeading: {
    fontWeight: '600',
    color: theme.palette.text.primary,
    fontSize: '0.8rem',
    marginBottom: '1rem',
    textAlign: 'center',
    width: '100%',
  },
  stepDescription: {
    color: theme.palette.text.secondary,
    fontSize: '1rem',
    lineHeight: '1.6',
    textAlign: 'center',
    width: '100%',
  },
};

export default processSectionStyle;