import theme from '../../../theme';

const processSectionStyle = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
    marginTop: { xs: '0rem', md: '0rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
    textAlign: 'center',
  },
  tagline: {
    fontFamily: 'monospace',
    fontSize: '0.875rem',
    color: '#0d9488',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  title: {
    marginTop: { xs: '3.5rem', md: '3rem' },

    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    textAlign: 'center',
  },
  subtitle: {
    color: '#6b7280',
    fontSize: { xs: '1rem', sm: '1.1rem' },
    lineHeight: 1.6,
    textAlign: 'center',
  },

  // Step Flow
  stepFlow: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '600px',
    marginBottom: '1rem',
  },
  stepBubble: {
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    backgroundColor: '#115e59',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 2,
    boxShadow: '0 4px 12px rgba(17, 94, 89, 0.3)',
  },
  stepBubbleNumber: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: 'white',
  },
  connector: {
    flex: 1,
    height: '3px',
    backgroundColor: '#0d9488',
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      right: '-6px',
      top: '50%',
      transform: 'translateY(-50%)',
      width: '0',
      height: '0',
      borderLeft: '6px solid #0d9488',
      borderTop: '3px solid transparent',
      borderBottom: '3px solid transparent',
    },
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
    padding: { xs: '2rem', sm: '2.5rem' },
    borderRadius: '1rem',
    backgroundColor: '#171717',
    border: '1px solid #374151',
    transition: 'all 0.3s ease',
    height: '100%',
    minHeight: { xs: '280px', sm: '300px', md: '320px' },
    position: 'relative',
    overflow: 'hidden',
    '&:hover': {
			transform: 'translateY(-5px)',
			borderColor: '#0d9488',
		},
  },
  iconContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '60px',
    height: '60px',
    borderRadius: '16px',
    backgroundColor: '#115e59',
    flexShrink: 0,
    alignSelf: 'center',
    boxShadow: '0 4px 12px rgba(17, 94, 89, 0.3)',
  },
  icon: {
    fontSize: '30px',
    color: 'white',
  },
  cardTitle: {
    fontSize: '1.25rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: 'center',
    lineHeight: 1.3,
  },
  cardDescription: {
    fontSize: '0.95rem',
    color: '#6b7280',
    lineHeight: 1.6,
    textAlign: 'center',
    flex: 1,
  },
  stepIndicator: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: 'auto',
    paddingTop: '1rem',
  },
  stepIndicatorText: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#0d9488',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    padding: '0.25rem 0.75rem',
    borderRadius: '12px',
    backgroundColor: 'rgba(13, 148, 136, 0.1)',
    border: '1px solid rgba(13, 148, 136, 0.2)',
  },
};

export default processSectionStyle;