import theme from '../../../theme';

const processSectionStyle = {
  box: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    paddingBottom: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '15%',
      left: '5%',
      width: '20%',
      height: '30%',
      background: `radial-gradient(ellipse, ${theme.palette.secondary.main}10, transparent 70%)`,
      borderRadius: '50%',
      pointerEvents: 'none',
      zIndex: 0,
    },
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginX: 'auto',
    maxWidth: '1200px',
    px: { xs: '1rem', sm: '2rem' },
    position: 'relative',
    zIndex: 1,
  },
  containerBox: {
    textAlign: 'center',
    width: '100%',
    maxWidth: '60rem',
    marginX: 'auto',
    marginBottom: '3rem',
  },
  heading: {
    fontWeight: '600',
    fontSize: { xs: '1.8rem', sm: '2.5rem' },
    color: theme.palette.text.primary,
    paddingBottom: { sm: '1rem', xs: '0.75rem' },
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: '50%',
      transform: 'translateX(-50%)',
      width: '4rem',
      height: '4px',
      background: `linear-gradient(90deg, ${theme.palette.secondary.dark}, ${theme.palette.secondary.light})`,
      borderRadius: '2px',
    },
  },
  subheading: {
    color: theme.palette.text.secondary,
    fontSize: { xs: '1rem', md: '1.2rem' },
    marginTop: '1rem',
    marginBottom: '1rem',
    lineHeight: '1.6',
    maxWidth: '40rem',
    marginX: 'auto',
  },
  stepsContainer: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: 'stretch',
    gap: { xs: '3rem', md: '1.5rem' },
    width: '100%',
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      top: '3.5rem',
      left: '12%',
      width: '76%',
      height: '2px',
      background: `linear-gradient(90deg, ${theme.palette.secondary.dark}, ${theme.palette.secondary.light})`,
      display: { xs: 'none', md: 'block' },
      zIndex: 0,
    },
  },
  stepCard: {
    flex: 1,
    backgroundColor: `${theme.palette.background.darkTransparent}CC`,
    backdropFilter: 'blur(6px)',
    borderRadius: '1rem',
    padding: '2rem 1.5rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    position: 'relative',
    transition: 'all 0.35s ease',
    border: `1px solid ${theme.palette.divider}`,

    zIndex: 1,
    '&:hover': {
      transform: 'translateY(-8px)',
      boxShadow: '0rem 0.75rem 1.5rem rgba(0, 0, 0, 0.15)',
      backgroundColor: `${theme.palette.background.paper}DD`,
      '& .step-number': {
        transform: 'scale(1.1)',
        boxShadow: '0 0 15px rgba(94, 234, 212, 0.4)',
      },
      '& .step-icon': {
        transform: 'scale(1.1) rotate(5deg)',
      },
    },
  },
  stepNumber: {
    position: 'absolute',
    top: '-1.25rem',
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '50%',
    background: `linear-gradient(135deg, ${theme.palette.secondary.dark}, ${theme.palette.secondary.main})`,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: theme.palette.text.primary,
    fontWeight: 'bold',
    fontSize: '1.25rem',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.1)',
    zIndex: 2,
    transition: 'all 0.3s ease',
  },
  imageContainer: {
    width: '6rem',
    height: '6rem',
    borderRadius: '1rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    background: `linear-gradient(135deg, ${theme.palette.secondary.dark}90, ${theme.palette.secondary.main}70)`,

    marginBottom: '1.5rem',
    marginTop: '0.75rem',
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: '-4px',
      background: `linear-gradient(135deg, ${theme.palette.secondary.light}50, transparent 80%)`,
      borderRadius: 'inherit',
      opacity: 0.7,
      zIndex: -1,
    },
  },
  imageIcon: {
    fontSize: '3rem',
    color: theme.palette.text.primary,
    transition: 'transform 0.3s ease',
  },
  stepHeading: {
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: 'center',
    fontSize: { xs: '1.1rem', sm: '1.2rem' },
    marginBottom: '0.75rem',
  },
  stepDescription: {
    color: theme.palette.text.secondary,
    textAlign: 'center',
    lineHeight: 1.7,
    fontSize: '1rem',
  },
  connector: {
    position: 'absolute',
    top: '2.5rem',
    left: 'calc(100% - 0.5rem)',
    width: '1rem',
    height: '2px',
    backgroundColor: theme.palette.secondary.main,
    display: { xs: 'none', md: 'block' },
  },
};

export default processSectionStyle;
