import theme from '../../../theme';

const supportedFrameworksStyle = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
    marginTop: { xs: '0rem', md: '0rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
    textAlign: 'center',
  },
  tagline: {
    marginTop: { xs: '3rem', md: '3rem' },
    fontFamily: 'monospace',
    fontSize: '0.875rem',
    color: '#0d9488',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  title: {
    
    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: { xs: '1rem', sm: '1.1rem', md: '1.2rem' },
    color: '#0d9488',
    lineHeight: 1.6,
    marginBottom: '1rem',
  },
  description: {
    fontSize: '1rem',
    color: '#6b7280',
    lineHeight: 1.6,
    marginBottom: '1rem',
  },
  frameworksContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '1.5rem',
    marginBottom: '1.5rem',
    maxWidth: '1100px',
    width: '100%',
  },
  frameworkItem: {
    backgroundColor: '#171717',
    borderRadius: '0.5rem',
    padding: '1rem 1.5rem',
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #374151',
    transition: 'transform 0.3s ease, border-color 0.3s ease',
    '&:hover': {
      transform: 'translateY(-5px)',
      borderColor: '#0d9488',
    },
  },
  iconContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '0.75rem',
  },
  checkIcon: {
    color: '#0d9488',
    fontSize: '1.5rem',
  },
  frameworkName: {
    color: theme.palette.text.primary,
    fontWeight: '600',
    fontSize: '1rem',
  },
  note: {
    color: '#6b7280',
    fontSize: '0.9rem',
    marginTop: '1rem',
    fontStyle: 'italic',
  },
  contentWrapper: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    gap: { xs: '2rem', md: '6rem' },
    backgroundColor: '#171717',
    borderRadius: '1rem',
    padding: { xs: '2rem', md: '2rem' },
    border: '1px solid #374151',
    width: '100%',
    maxWidth: '1000px',
  },
  textContent: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
  },
  imageContainer: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    minHeight: { xs: '200px', sm: '250px', md: 'auto' },
  },
  imageWrapper: {
    width: '100%',
    maxWidth: { xs: '280px', sm: '350px', md: '400px' },
    height: { xs: '200px', sm: '250px', md: '300px' },
    position: 'relative',
    borderRadius: '0.75rem',
    overflow: 'hidden',
  },
  tag: {
    display: 'inline-block',
    padding: '0.5rem 1rem',
    borderRadius: '1rem',
    background: '#115e59',
    marginBottom: '1rem',
  },
  tagText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: '0.875rem',
  },
  assistanceImage: {
    objectFit: 'contain' as const,
  },
};

export default supportedFrameworksStyle;