import theme from '../../../theme';

const simpleInfoSectionStyle = {
  box: {
    paddingTop: { sm: '1rem', xs: '0.5rem' },
    paddingBottom: { sm: '1rem', xs: '0.5rem' },
    backgroundColor: theme.palette.background.default,
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginX: 'auto',
    maxWidth: '75rem',
    px: { xs: '1rem', sm: '2rem' },
  },
  title: {
    fontWeight: '600',
    fontSize: { xs: '1.6rem', sm: '2rem' },
    color: 'white',
    textAlign: 'center',
    marginBottom: '1.5rem',
  },
  subtitle: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: theme.palette.secondary.main,
    textAlign: 'center',
    marginBottom: '1rem',
    fontWeight: 500,
  },
  contentWrapper: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '3rem',
    width: '100%',
  },
  imageReverse: {
    flexDirection: { xs: 'column', md: 'row-reverse' },
  },
  textContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: { xs: 'center', md: 'flex-start' },
    textAlign: { xs: 'center', md: 'left' },
  },
  highlightText: {
    backgroundColor: theme.palette.secondary.light,
    color: theme.palette.text.primary,
    fontSize: '0.9rem',
    fontWeight: '600',
    padding: '0.5rem 1rem',
    borderRadius: '0.5rem',
    marginBottom: '1.5rem',
    display: 'inline-block',
  },
  description: {
    color: '#6B7280',
    fontSize: { xs: '1rem', md: '1rem' },
    lineHeight: 1.6,
    marginBottom: '1.5rem',
    textAlign: { xs: 'center', md: 'left' },
  },
  descriptionCentered: {
    color: '#6B7280',
    fontSize: '1rem',
    lineHeight: 1.6,
    marginBottom: '1.5rem',
    textAlign: 'center',
    maxWidth: '50rem',
    margin: '0 auto 1.5rem auto',
  },
  imageContainer: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    maxWidth: '28rem',
    height: 'auto',
    borderRadius: '1rem',
  },
  placeholderImage: {
    width: '100%',
    maxWidth: '28rem',
    minHeight: '16rem',
    borderRadius: '1rem',
    backgroundColor: theme.palette.background.paper,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'rgba(255, 255, 255, 0.3)',
    fontSize: '1rem',
  },
  emoji: {
    fontSize: '1.5rem',
    marginRight: '0.5rem',
  },
};

export default simpleInfoSectionStyle;
