import theme from '../../../theme';

const useCasesSectionStyle = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
    marginTop: { xs: '0rem', md: '0rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
    textAlign: 'center',
  },
  title: {
    marginTop: { xs: '3rem', md: '3rem' },
    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    textAlign: 'center',
  },
  subtitle: {
    color: '#6b7280',
    fontSize: { xs: '1rem', sm: '1.1rem' },
    lineHeight: 1.6,
    textAlign: 'center',
  },
  contentWrapper: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    gap: { xs: '2rem', md: '4rem' },
    width: '100%',
    maxWidth: '1200px',
  },
  textContent: {
    flex: 1,
  },
  list: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  listItem: {
    display: 'flex',
    marginBottom: '2rem',
    padding: '1.5rem',
    backgroundColor: '#171717',
    borderRadius: '0.75rem',
    border: '1px solid #374151',
    transition: 'transform 0.3s ease, border-color 0.3s ease',
    '&:hover': {
      transform: 'translateX(5px)',
      borderColor: '#0d9488',
    },
  },
  numberContainer: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '50%',
    backgroundColor: '#115e59',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: theme.palette.text.primary,
    fontWeight: 'bold',
    fontSize: '1.25rem',
    marginRight: '1.5rem',
    flexShrink: 0,
  },
  itemContent: {
    display: 'flex',
    flexDirection: 'column',
  },
  itemHeading: {
    color: theme.palette.text.primary,
    fontSize: '1.25rem',
    fontWeight: '600',
    marginBottom: '0.5rem',
  },
  itemSubheading: {
    color: '#6b7280',
    fontSize: '1rem',
    lineHeight: 1.6,
  },
  imageContainer: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    minHeight: { xs: '300px', sm: '400px', md: 'auto' },
  },
  imageWrapper: {
    width: '100%',
    maxWidth: { xs: '280px', sm: '350px', md: '500px' },
    height: { xs: '300px', sm: '400px', md: '500px' },
    position: 'relative',
    borderRadius: '0.75rem',
    overflow: 'hidden',
  },
  image: {
    objectFit: 'contain' as const,
  },
};

export default useCasesSectionStyle;