const platformStyles = {
	menuBox: {
	  display: 'flex',
	  flexDirection: 'column',
	  width: '100%',
	  backgroundColor: '#0a0a0a',
	  maxHeight: 'calc(100vh - 8rem)',
	  overflowY: 'auto',
	  '&::-webkit-scrollbar': {
	    display: 'none',
	  },
	  msOverflowStyle: 'none',
	  scrollbarWidth: 'none',
	},
	container: {
	  display: 'flex',
	  width: '100%',
	  height: '100%',
	},
	sidebar: {
	  width: '270px',
	  backgroundColor: '#121212',
	  borderRight: '1px solid #262626',
	  padding: '1rem 0',
	  flexShrink: 0,
	},
	mainContent: {
	  flex: 1,
	  padding: '1.5rem 2rem',
	  display: 'flex',
	  flexDirection: 'column',
	},
	sidebarHeader: {
	  padding: '0.75rem 1.5rem',
	  fontSize: '0.875rem',
	  fontWeight: 600,
	  color: '#9ca3af',
	  textTransform: 'uppercase',
	  letterSpacing: '0.05em',
	},
	sizeOptionContainer: {
	  display: 'flex',
	  alignItems: 'center',
	  padding: '0.75rem 1.5rem',
	  cursor: 'pointer',
	  '&:hover': {
	    backgroundColor: '#1f1f1f',
	  },
	},
	mobileSizeOptionContainer: {
	  display: 'flex',
	  alignItems: 'flex-start',
	  padding: '1rem 0',
	  marginBottom: '0.75rem',
	  cursor: 'pointer',
	  borderBottom: '1px solid #262626',
	},
	sizeOptionIcon: {
	  width: '2.5rem',
	  height: '2.5rem',
	  display: 'flex',
	  alignItems: 'center',
	  justifyContent: 'center',
	  marginRight: '1rem',
	  backgroundColor: '#115e59',
      borderRadius: '0.5rem',
	  '& svg': {
	    color: '#ffffff',
	    fontSize: '1.5rem',
	  },
	},
	sizeOptionTitle: {
	  fontSize: '0.875rem',
	  fontWeight: 600,
	  color: '#f9fafb',
	  marginBottom: '0.25rem',
	},
	sizeOptionDescription: {
	  fontSize: '0.75rem',
	  color: '#9ca3af',
	  lineHeight: 1.4,
	},
	solutionItem: {
	  padding: '0.75rem 1.5rem',
	  cursor: 'pointer',
	  '&:hover': {
	    backgroundColor: '#1f1f1f',
	  },
	},
	mobileSolutionItem: {
	  padding: '0.75rem 0',
	  marginBottom: '0.5rem',
	  cursor: 'pointer',
	  borderBottom: '1px solid #262626',
	},
	solutionItemText: {
	  fontSize: '0.875rem',
	  color: '#f9fafb',
	  fontWeight: 500,
	},
	featuresGrid: {
	  display: 'grid',
	  gridTemplateColumns: 'repeat(2, 1fr)',
	  gap: '1.5rem',
	},
	featureItem: {
	  display: 'flex',
	  alignItems: 'flex-start',
	  cursor: 'pointer',
	  '&:hover': {
	    '& $featureTitle': {
	      color: '#3B82F6',
	    },
	  },
	},
	mobileFeatureItem: {
	  display: 'flex',
	  alignItems: 'flex-start',
	  cursor: 'pointer',
	  padding: '1rem 0',
	  marginBottom: '0.5rem',
	  borderBottom: '1px solid #262626',
	},
	featureIcon: {
	  width: '2.5rem',
	  height: '2.5rem',
	  display: 'flex',
	  alignItems: 'center',
	  justifyContent: 'center',
	  backgroundColor: '#115e59',
      borderRadius: '0.5rem',
	  marginRight: '1rem',
	  flexShrink: 0,
	  '& svg': {
	    color: '#ffffff',
	    fontSize: '1.5rem',
	  },
	},
	featureContent: {
	  flex: 1,
	  display: 'flex',
	  flexDirection: 'column',
	},
	featureTitle: {
	  fontSize: '0.875rem',
	  fontWeight: 600,
	  color: '#f9fafb',
	  marginBottom: '0.25rem',
	  display: 'flex',
	  alignItems: 'center',
	},
	featureDescription: {
	  fontSize: '0.75rem',
	  color: '#9ca3af',
	  lineHeight: 1.4,
	  marginBottom: '0.25rem',
	},
	newBadge: {
	  backgroundColor: '#FBBF24',
	  color: '#000000',
	  fontSize: '0.625rem',
	  fontWeight: 600,
	  padding: '0.125rem 0.375rem',
	  borderRadius: '0.25rem',
	  marginLeft: '0.5rem',
	},
	sectionTitle: {
	  fontSize: '0.875rem',
	  fontWeight: 600,
	  color: '#9ca3af',
	  marginBottom: '1.5rem',
	  textTransform: 'uppercase',
	  letterSpacing: '0.05em',
	  paddingBottom: '0.5rem',
	  borderBottom: '1px solid #262626',
	},
	sidebarSection: {
	  marginBottom: '1.5rem',
	},
	mobileContainer: {
	  width: '100%',
	  padding: '0 1rem',
	  paddingTop: '0',
	  backgroundColor: '#0a0a0a',
	  color: '#f9fafb',
	},
	mobileCategory: {
	  padding: '0.75rem 0',
	  borderBottom: '1px solid #262626',
	  fontWeight: 600,
	  color: '#f9fafb',
	},
	mobileFeaturesList: {
	  marginTop: '0.5rem',
	},
	mobileCategoriesContainer: {
	  marginBottom: '1.5rem',
	},
};

export default platformStyles;