import theme from '../../../../theme';

const soc2HeroSectionStyles = {
  container: {
    paddingTop: '1rem',
    paddingBottom: '1rem',
    background: theme.palette.background.default,
    padding: { xs: '5rem 1rem', sm: '1rem 1rem' },
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      background: `radial-gradient(circle at 70% 30%, ${theme.palette.primary.light}15, transparent 45%)`,
      pointerEvents: 'none',
    },
  },
  containerBox: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    gap: '2rem',
    position: 'relative',
    zIndex: 2,
  },
  leftContentBox: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
    padding: { xs: '1rem', md: '2rem' },
  },
  contentBox: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
  },
  formBox: {
    flex: 1,
		borderRadius: { xs: '1rem', md: '1.5rem' },
		maxWidth: { xs: '100%', md: '600px' },
		padding: { xs: '0rem', md: '2rem' },
		marginTop: { xs: '0', sm: '0.5rem' },
		transition: 'transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out',
		width: { xs: '100%', md: 'auto' },
  },
  formContainer: {
    padding: { xs: '1rem', md: '2rem' },
		borderRadius: { xs: '1rem', md: '1.5rem' },
		background: theme.palette.background.paper,
		width: '100%',
		maxWidth: { xs: '100%', md: '600px' },
		marginTop: { xs: '1rem', sm: '1.5rem' },
		border: `1px solid ${theme.palette.divider}`,
		boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
  },
  formHeading: {
    fontSize: { xs: '20px', md: '1.8rem' },
		fontWeight: '600',
		color: theme.palette.text.primary,
		marginBottom: '0.5rem',
		textAlign: { xs: 'left', md: 'left' },
  },
  compliancesLabel: {
    fontWeight: 'bold',
    marginBottom: '0.5rem',
    color: theme.palette.text.primary,
  },
  tag: {
    display: 'inline-block',
    padding: '0.5rem 1rem',
    borderRadius: '1rem',
    background: '#115e59',
    marginBottom: '1rem',
  },
  tagText: {
    color: 'white',
    fontWeight: 'bold',
  },
  mainTitle: {
    fontSize: { xs: '1.6rem', sm: '2rem' },
    fontWeight: '600',
    marginBottom: '1rem',
    color: theme.palette.text.primary,
  },
  highlightText: {
    color: theme.palette.primary.light,
  },
  description: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: theme.palette.text.secondary,
    lineHeight: '1.7',
    marginBottom: '1.5rem',
    maxWidth: '550px',
  },
  featuresContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: { xs: 'space-between', md: 'space-between' },
    alignItems: 'flex-start',
    gap: { xs: '1rem', md: '2rem' },
    marginTop: '0.5rem',
    width: '100%',
    flexWrap: 'nowrap',
  },
  featureItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    gap: '0.5rem',
    flex: '1 1 33%',
    maxWidth: '33%',
  },
  iconWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    minHeight: '2.5rem',
  },
  featureIcon: {
    fontSize: { xs: '1.8rem', md: '2.5rem' },
    color: '#115e59',
  },
  featureTextWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: '100%',
  },
  featureTitle: {
    fontSize: { xs: '0.9rem', md: '1.2rem' },
    fontWeight: 'bold',
    color: theme.palette.text.primary,
  },
  featureSubtitle: {
    fontSize: { xs: '0.8rem', md: '0.9rem' },
    color: '#6B7280',
  },
  button: {
    backgroundColor: '#115e59',
    color: '#f9fafb',
    borderRadius: '0.5rem',
    padding: {
      xs: '0.25rem 0.5rem',
      sm: '0.375rem 0.75rem',
      md: '0.25rem 0.5rem',
    },
    textTransform: 'none',
    fontSize: '1rem',
    whiteSpace: 'nowrap',
    border: '1px solid #0d9488',
    transition: 'all 150ms ease',
    '&:hover': {
      backgroundColor: '#0f766e',
    },
  },
  formLabel: {
    color: theme.palette.text.primary,
    marginBottom: '8px',
    display: 'block',
  },
  formInput: {
    backgroundColor: 'rgba(38, 38, 38, 0.5)',
    color: theme.palette.text.primary,
    '& .MuiOutlinedInput-notchedOutline': {
      borderColor: theme.palette.divider,
    },
  },
  checkbox: {
    color: theme.palette.secondary.main,
  },
  formHelperText: {
    marginTop: '4px',
    color: theme.palette.error.main,
  },
  secondaryText: {
    color: theme.palette.text.secondary,
    fontSize: '0.875rem',
    marginTop: '8px',
  },
  gridItem: {
    marginBottom: '16px',
  },
  checkboxLabel: {
    color: '#000000',
    '& .MuiFormControlLabel-label': {
      color: '#ffffff',
      fontSize: '0.9rem',
    },
  },
};

export default soc2HeroSectionStyles;