import theme from '../../../theme';

const callToActionStyle = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
    marginTop: { xs: '0rem', md: '6rem' },
    marginBottom: { xs: '0rem', md: '4rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  container: {
    width: '100%',
    position: 'relative',
    zIndex: 1,
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '2rem',
    textAlign: 'center',
  },
  tagline: {
    fontFamily: 'monospace',
    fontSize: '0.875rem',
    color: '#0d9488',
    letterSpacing: '0.05em',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  mainTitle: {
    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    textAlign: 'center',
    marginBottom: '0.5rem',
    marginTop:{xs:'3rem'}
  },
  mainSubtitle: {
    fontSize: { xs: '1rem', sm: '1.1rem' },
    color: '#0d9488',
    textAlign: 'center',
    fontWeight: 500,
  },
  contentWrapper: {
    backgroundColor: '#171717',
    borderRadius: '1rem',
    padding: { xs: '2rem', md: '3rem' },
    display: 'flex',
    flexDirection: { xs: 'column', lg: 'row' },
    alignItems: 'center',
    gap: { xs: '2rem', lg: '4rem' },
    border: '1px solid #374151',
    width: '100%',
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '4px',
      background: 'linear-gradient(90deg, #0d9488, #115e59)',
      borderTopLeftRadius: '1rem',
      borderTopRightRadius: '1rem',
    },
  },
  textContent: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: { xs: 'flex-start', lg: 'flex-start' },
    textAlign: { xs: 'left', lg: 'left' },
    maxWidth: { lg: '500px' },
    width: '100%',
  },
  title: {
    fontSize: { xs: '1.25rem', md: '1.5rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    marginBottom: '0.5rem',
    textAlign: { xs: 'center', sm: 'left' },
    width: '100%',
  },
  subtitle: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: '#0d9488',
    marginBottom: '1rem',
    fontWeight: 500,
    textAlign: { xs: 'center', sm: 'left' },
    width: '100%',
  },
  description: {
    color: '#6b7280',
    fontSize: '1rem',
    lineHeight: 1.6,
    marginBottom: '1.5rem',
    textAlign: { xs: 'center', sm: 'left' },
    width: '100%',
  },
  benefitsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    marginBottom: '2rem',
    alignItems: 'flex-start',
    width: '100%',
  },
  benefitItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    width: '100%',
    justifyContent: 'flex-start',
  },
  benefitIcon: {
    color: '#0d9488',
    fontSize: '1.1rem',
    flexShrink: 0,
  },
  benefitText: {
    color: '#6b7280',
    fontSize: '0.875rem',
    fontWeight: 500,
    textAlign: 'left',
    flex: 1,
  },
  imageContainer: {
    flex: '1',
    display: { xs: 'none', sm: 'flex' },
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    maxWidth: { sm: '100%', lg: '400px' },
  },
  imageWrapper: {
    position: 'relative',
    width: '100%',
    maxWidth: '350px',
  },
  imageGlow: {
    position: 'absolute',
    top: '-20%',
    left: '-20%',
    width: '140%',
    height: '140%',
    background: 'radial-gradient(circle, rgba(17, 94, 89, 0.15) 0%, transparent 60%)',
    zIndex: 1,
    animation: 'pulse 3s ease-in-out infinite',
  },
  ctaButton: {
    display: 'inline-flex',
    alignItems: 'center',
    px: { xs: '1rem', md: '1.5rem' },
    py: { xs: '0.5rem', md: '0.75rem' },
    backgroundColor: '#115e59',
    '&:hover': {
      backgroundColor: '#0f766e',
      transform: 'translateY(-2px)',
    },
    color: 'white',
    fontSize: '1rem',
    fontWeight: 600,
    borderRadius: '0.5rem',
    transition: 'all 0.3s ease',
    border: '1px solid #0d9488',
    textTransform: 'none',
    gap: '0.5rem',
    boxShadow: '0 4px 12px rgba(17, 94, 89, 0.25)',
    alignSelf: { xs: 'center', sm: 'flex-start' },
    '& .MuiSvgIcon-root': {
      fontSize: '1.1rem',
    },
  },
};

export default callToActionStyle;