import theme from '../../../theme';

const infoSectionStyle = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '2.5rem', md: '12rem', '2xl': '18rem' },
    marginTop: { xs: '0rem', md: '6rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  alternateBackground: {
    backgroundColor: theme.palette.background.default,
  },
  container: {
    width: '100%',
    position: 'relative',
    zIndex: 1,
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '3rem',
    textAlign: 'center',
  },
  tagline: {
    fontFamily: 'monospace',
    fontSize: '0.875rem',
    color: '#0d9488',
    letterSpacing: '0.05em',
    textAlign: 'center',
    textTransform: 'uppercase',
    marginBottom: '0.5rem',

  },
  title: {
    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    textAlign: 'left',
    marginBottom: '1rem',
    marginTop:{xs:'2rem'},
  },
  subtitle: {
    fontSize: { xs: '1rem', sm: '1.1rem' },
    color: '#6b7280',
    textAlign: 'left',
    lineHeight: 1.6,
    maxWidth: '600px',
  },
  contentWrapper: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    gap: { xs: '2rem', md: '4rem' },
  },
  contentWrapperReversed: {
    flexDirection: { xs: 'column', md: 'row-reverse' },
  },
  imageContainer: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '300px',
    position: 'relative',
  },
  imageWrapper: {
    width: '100%',
    maxWidth: '500px',
    height: { xs: '300px', sm: '400px', md: '450px' },
    position: 'relative',
    borderRadius: '1rem',
    overflow: 'hidden',
    flexShrink: 0,
  },

  sectionImage: {
    objectFit: 'cover' as const,
  },
  imagePlaceholder: {
    width: '100%',
    maxWidth: '500px',
    height: '300px',
    borderRadius: '1rem',
    border: '1px solid #374151',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#6b7280',
    padding: '1rem',
    fontSize: '0.875rem',
    textAlign: 'center',
  },
  textContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  highlight: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0.75rem 1.5rem',
    color: '#0d9488',
    fontWeight: 600,
    borderRadius: '0.5rem',
    marginBottom: '1rem',
    fontSize: '1rem',
    backgroundColor: 'rgba(17, 94, 89, 0.1)',
    border: '1px solid rgba(17, 94, 89, 0.2)',
    width: 'fit-content',
  },
  description: {
    fontSize: '1rem',
    color: '#6b7280',
    lineHeight: 1.7,
    marginBottom: '1rem',
  },
  subheading: {
    fontSize: '1.125rem',
    fontWeight: 600,
    color: theme.palette.text.primary,
    fontStyle: 'italic',
    marginTop: '1rem',
  },
  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)' },
    gap: '1rem',
    marginTop: '1rem',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem',
    padding: '1rem',
    borderRadius: '0.5rem',
    backgroundColor: '#171717',
    border: '1px solid #374151',
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      borderColor: '#0d9488',
      boxShadow: '0 4px 12px rgba(17, 94, 89, 0.15)',
    },
  },
  featureIconContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    borderRadius: '0.5rem',
    backgroundColor: '#115e59',
    flexShrink: 0,
  },
  featureIcon: {
    fontSize: '1.25rem',
    color: 'white',
  },
  featureTitle: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: theme.palette.text.primary,
    marginBottom: '0.25rem',
  },
  featureDescription: {
    fontSize: '0.75rem',
    color: '#6b7280',
    lineHeight: 1.5,
  },
};

export default infoSectionStyle;