import theme from '../../../theme';

const pitfallsSectionStyle = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '1rem', md: '10rem', '2xl': '15rem' },
    marginTop: {  md: '6rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  container: {
    width: '100%',
    position: 'relative',
    zIndex: 1,
  },
  contentBox: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    gap: { xs: '2rem', md: '4rem' },
  },
  textContent: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
  },
  title: {
    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    marginBottom: '1rem',
    textAlign: { xs: 'center', md: 'left' },
  },
  subtitle: {
    fontSize: { xs: '1rem', md: '1.2rem' },
    fontWeight: 500,
    marginBottom: '1rem',
    color: '#0d9488',
    textAlign: { xs: 'center', md: 'left' },
  },
  highlightText: {
    fontSize: '1.125rem',
    fontWeight: 600,
    color: 'white',
    marginBottom: '1rem',
    display: 'block',
    backgroundColor: 'rgba(17, 94, 89, 0.1)',
    padding: '0.75rem 1.5rem',
    borderRadius: '0.5rem',
    borderLeft: '3px solid #0d9488',
    width: 'fit-content',
    textAlign: 'left',
    marginLeft: { xs: 'auto', md: '0' },
    marginRight: { xs: 'auto', md: 'auto' },
  },
  description: {
    fontSize: '1rem',
    color: '#6b7280',
    marginBottom: '1.5rem',
    lineHeight: 1.7,
    textAlign: { xs: 'center', md: 'left' },
  },
  pitfallsContainer: {
    flex: 1,
    width: '100%',
  },
  pitfallList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  pitfallItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: { xs: '0.75rem', sm: '1.5rem' },
    padding: { xs: '1rem', sm: '1.5rem' },
    borderRadius: '0.5rem',
    background: '#171717',
    border: '1px solid #374151',
    transition: 'transform 0.3s ease, border-color 0.3s ease',

  },
  numberBox: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '0.5rem',
    backgroundColor: '#115e59',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: 'white',
    fontWeight: 'bold',
    fontSize: '1rem',
  },
  pitfallContent: {
    flex: 1,
  },
  pitfallHeading: {
    fontSize: '1.125rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    marginBottom: '0.5rem',
  },
  pitfallSubheading: {
    fontSize: '0.875rem',
    color: '#6b7280',
    lineHeight: 1.7,
  },
};

export default pitfallsSectionStyle;