import theme from '../../../theme';

const platformHighlightsStyle = {
  section: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    paddingBottom: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.darkPaper,
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      left: '-5%',
      top: '-10%',
      width: '30%',
      height: '30%',
      background: `radial-gradient(ellipse, ${theme.palette.secondary.dark}10, transparent 70%)`,
      borderRadius: '50%',
      opacity: 0.6,
      zIndex: 0,
    },
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: { xs: '0 1rem', sm: '0 2rem' },
    position: 'relative',
    zIndex: 1,
  },
  header: {
    marginBottom: '3rem',
    textAlign: 'center',
  },
  title: {
    fontSize: { xs: '1.8rem', sm: '2.5rem' },
    fontWeight: 700,
    color: theme.palette.text.primary,
    marginBottom: '1rem',
    textAlign: 'center',
    position: 'relative',
    paddingBottom: '1rem',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: '50%',
      transform: 'translateX(-50%)',
      width: '4rem',
      height: '4px',
      background: `linear-gradient(90deg, ${theme.palette.secondary.main}, ${theme.palette.secondary.dark})`,
      borderRadius: '2px',
    },
  },
  subtitle: {
    fontSize: { xs: '1rem', sm: '1.1rem' },
    color: theme.palette.text.secondary,
    marginBottom: '2rem',
    textAlign: 'center',
    maxWidth: '800px',
    marginLeft: 'auto',
    marginRight: 'auto',
    lineHeight: 1.6,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr', md: 'repeat(4, 1fr)' },
    gap: '1.75rem',
  },
  feature: {
    backgroundColor: theme.palette.background.paper,
    padding: '1.75rem',
    borderRadius: '1rem',
    transition: 'all 0.3s ease',
    height: { sm: '16rem', xs: 'auto', md: '19rem' },
    display: 'flex',
    flexDirection: 'column',
    boxShadow: theme.customShadows?.card,
    border: `1px solid ${theme.palette.divider}`,
    position: 'relative',
    overflow: 'hidden',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: 0,
      width: '100%',
      height: '0',
      background: `linear-gradient(90deg, ${theme.palette.secondary.main}30, ${theme.palette.secondary.dark}30)`,
      transition: 'height 0.3s ease',
      zIndex: 0,
      borderBottomLeftRadius: '1rem',
      borderBottomRightRadius: '1rem',
    },
    '&:hover': {
      transform: 'translateY(-8px)',
      boxShadow: '0 16px 30px rgba(0, 0, 0, 0.2)',
      '&::after': {
        height: '4px',
      },
    },
  },
  iconContainer: {
    color: theme.palette.secondary.dark,
    marginBottom: '1.25rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    width: '3.5rem',
    height: '3.5rem',
    position: 'relative',
    zIndex: 1,
    backgroundColor: 'rgba(17, 94, 89, 0.1)',
    padding: '0.5rem',
  },
  icon: {
    fontSize: '2rem',
    transition: 'transform 0.3s ease',
    '&:hover': {
      transform: 'scale(1.1) rotate(5deg)',
    },
  },
  featureTitle: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    marginBottom: '0.75rem',
    position: 'relative',
    zIndex: 1,
  },
  featureDescription: {
    fontSize: '1rem',
    color: theme.palette.text.secondary,
    lineHeight: 1.7,
    position: 'relative',
    zIndex: 1,
  },
};

export default platformHighlightsStyle;
