import theme from '../../../theme';

const featuresSectionStyle = {
  box: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
    position: 'relative',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginX: 'auto',
    maxWidth: '1200px',
    px: { xs: '1rem', sm: '2rem' },
    position: 'relative',
    zIndex: 1,
  },
  containerBox: {
    textAlign: 'center',
    width: '100%',
    maxWidth: '60rem',
    marginX: 'auto',
    marginBottom: '3rem',
  },
  heading: {
    fontWeight: '600',
    fontSize: { xs: '1.8rem', sm: '2.5rem', md: '2rem' },
    color: theme.palette.text.primary,
    paddingBottom: { sm: '1rem', xs: '0.75rem' },
    position: 'relative',
  },
  subheading: {
    color: theme.palette.text.secondary,
    fontSize: { xs: '1rem', md: '1.1rem' },
    lineHeight: '1.6',
    maxWidth: '40rem',
    marginX: 'auto',
  },
  featureStep: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: '4rem',
    gap: '2rem',
    borderRadius: '1rem',
    padding: '2.5rem',
    transition: 'all 0.35s ease',
   
  },
  featureStepReverse: {
    flexDirection: { xs: 'column', md: 'row-reverse' },
  },
  textContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: { xs: 'center', md: 'flex-start' },
    textAlign: { xs: 'center', md: 'left' },
    maxWidth: { xs: '100%', md: '26rem' },
  },
  stepNumber: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50px',
    height: '50px',
    borderRadius: '8px',
    background: '#115e59',
    color: 'white',
    fontWeight: 'bold',
    fontSize: '1.25rem',
    marginBottom: '1.25rem',
  },
  stepTitle: {
    color: theme.palette.text.primary,
    fontWeight: '600',
    fontSize: { xs: '1.1rem', sm: '1.2rem' },
    marginBottom: '0.75rem',
    lineHeight: 1.3,
  },
  stepDescription: {
    color: theme.palette.text.secondary,
    fontSize: '1rem',
    lineHeight: 1.7,
    marginBottom: '1rem',
  },
  featureIcon: {
    fontSize: '24px',
    color: 'white',
    width: '24px',
    height: '24px',
  },
  imageContainer: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imagePlaceholder: {
    width: '100%',
    maxWidth: '26rem',
    aspectRatio: '16/9',
    borderRadius: '0.75rem',
    backgroundColor: '#115e5920',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: theme.palette.text.secondary,

    padding: '1.5rem',
    fontSize: '0.9rem',
    textAlign: 'center',
    fontStyle: 'italic',
  },
};

export default featuresSectionStyle;