import theme from '../../../theme';

const heroSectionStyle = {
  container: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
    position: 'relative',
  },
  containerBox: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: 'center',
    maxWidth: '1200px',
    width: '100%',
    margin: '0 auto',
    gap: { xs: '2rem', sm: '3rem' },
    padding: { xs: '1rem', sm: '2rem' },
  },
  contentBox: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    alignItems: { xs: 'center', md: 'flex-start' },
  },
  tagline: {
    display: 'inline-block',
    padding: '0.5rem 1rem',
    borderRadius: '1rem',
    background: '#115e59',
    marginBottom: '1rem',
    color: 'white',
    fontWeight: 'bold',
    fontSize: '0.9rem',
    width: { xs: 'auto', sm: 'fit-content' },
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  title: {
    fontWeight: '600',
    fontSize: { xs: '1.8rem', sm: '2.5rem', md: '2rem' },
    color: theme.palette.text.primary,
    lineHeight: 1.3,
    marginBottom: '1rem',
  },
  subtitle: {
    fontSize: { xs: '1.1rem', sm: '1.3rem' },
    color: theme.palette.primary.light,
    lineHeight: 1.4,
    marginBottom: '1rem',
  },
  description: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: theme.palette.text.secondary,
    lineHeight: '1.5',
    marginBottom: '1.5rem',
    maxWidth: '600px',
  },
  ctaButton: {
    marginTop: '1.5rem',
    color: theme.palette.common.white,
    fontWeight: 800,
    padding: {
      xs: '0.25rem 0.5rem',
      sm: '0.375rem 0.75rem',
      md: '0.7rem 1rem',
    },
    borderRadius: '0.5rem',
    backgroundColor: '#1f2937',
    border: '1px solid #4b5563',
    textTransform: 'none',
    fontSize: '0.9rem',
    whiteSpace: 'nowrap',
    transition: 'background-color 150ms ease',
    '&:hover': {
      backgroundColor: '#374151',
      borderColor: '#4b5563',
      transform: 'translateY(-2px)',
    },
  },
  imageBox: {
    flex: 1,
    display: 'flex',
    justifyContent: { xs: 'center', md: 'flex-end' },
    alignItems: 'center',
  },
  imagePlaceholder: {
    width: '100%',
    aspectRatio: '16/9',
    borderRadius: '0.75rem',
    backgroundColor: '#115e5920',
    border: `1px dashed ${theme.palette.secondary.dark}60`,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1.5rem',
    color: theme.palette.text.secondary,
    fontSize: '0.9rem',
    textAlign: 'center',
    fontStyle: 'italic',
  },
};

export default heroSectionStyle;