import theme from '../../../theme';

const heroSectionStyle = {
 heroContainer: {
   display: 'flex',
   flexDirection: { xs: 'column', md: 'row' },
   alignItems: 'center',
   justifyContent: 'center',
   gap: { xs: '2rem', md: '4rem', lg: '6rem', xl: '8rem' },
   px: {
     xs: '1.5rem',
     md: '4rem',
     lg: '8rem',
     xl: '12rem',
     '2xl': '16rem'
   },
   paddingTop: { xs: '8rem', md: '8rem', lg: '10rem', xl: '12rem' },
   paddingBottom: { xs: '2.5rem', md: '6rem', lg: '6rem', xl: '6rem' },
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   maxWidth: '1600px',
   margin: '0 auto',
 },
 contentBox: {
   flex: 1,
   textAlign: { xs: 'center', md: 'left' },
   display: 'flex',
   flexDirection: 'column',
   gap: { xs: '0.8rem', md: '1rem', lg: '1.2rem', xl: '1.5rem' },
   maxWidth: { xs: '100%', md: '600px', lg: '650px', xl: '700px' },
   alignItems: { xs: 'center', md: 'flex-start' },
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textTransform: 'uppercase',
   marginBottom: { xs: '0.5rem', lg: '0.75rem', xl: '1rem' },
 },
 title: {
   fontSize: { xs: '1.8rem', md: '2.2rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   lineHeight: 1.2,
   marginBottom: { xs: '0.5rem', md: '0.8rem', lg: '1rem', xl: '1.2rem' },
 },
 subtitle: {
   fontSize: { xs: '1rem', md: '1.2rem' },
   color: '#0d9488',
   lineHeight: 1.5,
   marginBottom: { xs: '0.8rem', md: '1rem', lg: '1.2rem', xl: '1.5rem' },
 },
 description: {
   color: '#6b7280',
   fontSize: { xs: '0.95rem', md: '1rem' },
   lineHeight: 1.6,
   marginBottom: { xs: '1.5rem', md: '2rem', lg: '2.5rem', xl: '3rem' },
   maxWidth: { lg: '90%', xl: '85%' },
 },
 button: {
   fontSize: '0.9rem',
   padding: { xs: '0.6rem 1.2rem', lg: '0.75rem 1.5rem', xl: '0.9rem 1.8rem' },
   minWidth: 'auto',
   width: 'fit-content',
   whiteSpace: 'nowrap',
   alignSelf: { xs: 'center', md: 'flex-start' },
   marginBottom: { lg: '1rem', xl: '2rem' },
 },
 imageBox: {
   flex: 1,
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   maxWidth: { xs: '100%', md: '500px', lg: '550px', xl: '600px' },
   width: '100%',
 },
 imageWrapper: {
   width: '100%',
   maxWidth: { xs: '500px', lg: '550px', xl: '600px' },
   height: { xs: '350px', md: '400px', lg: '450px', xl: '500px' },
   position: 'relative',
   borderRadius: '1rem',
   overflow: 'hidden',
   display: 'block',
 },
};

export default heroSectionStyle;