import theme from '../../../theme';

const platformFeaturesStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
   marginTop: { xs: '3.5rem', md: '6rem' },
   gap: '2rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   paddingBottom: { xs: '2rem', sm: '4rem' },
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '3rem',
   textAlign: 'center',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 subtitle: {
   fontSize: { xs: '1rem', sm: '1.1rem' },
   color: '#6b7280',
   lineHeight: 1.6,
   textAlign: 'center',
   maxWidth: '700px',
 },
 carouselContainer: {
   position: 'relative',
   width: '100%',
   maxWidth: '1200px',
   display: 'flex',
   alignItems: 'center',
   gap: { xs: '0.25rem', md: '1rem' },
   px: { xs: '0.5rem', md: '0' },
 },
 navigationButton: {
   minWidth: { xs: '36px', sm: '48px' },
   height: { xs: '36px', sm: '48px' },
   borderRadius: '50%',
   fontSize: '0.875rem',
   padding: { xs: '0.25rem', sm: '0.5rem' },
   flexShrink: 0,
   zIndex: 2,
 },
 carouselWrapper: {
   flex: 1,
   overflow: 'hidden',
   borderRadius: '0.5rem',
   width: '100%',
 },
 carouselTrack: {
   display: 'flex',
   transition: 'transform 0.5s ease-in-out',
   gap: { xs: '0.75rem', md: '1.5rem' },
   width: '70%',
   minWidth: '100%',
 },
 card: {
   display: 'flex',
   flexDirection: 'column',
   gap: '1rem',
   padding: { xs: '1.25rem', sm: '2rem' },
   borderRadius: '0.5rem',
   backgroundColor: '#171717',
   border: '1px solid #374151',
   borderStyle: 'solid',
   borderWidth: '1px',
   transition: 'transform 0.3s ease, border-color 0.3s ease',
   height: 'auto',
   minHeight: { xs: '260px', sm: '300px', md: '320px' },
   boxSizing: 'border-box',
   position: 'relative',
   flexShrink: 0,
 },
 iconContainer: {
   display: 'flex',
   alignItems: 'center',
   justifyContent: 'center',
   width: { xs: '50px', sm: '60px' },
   height: { xs: '50px', sm: '60px' },
   borderRadius: '12px',
   backgroundColor: '#115e59',
   flexShrink: 0,
 },
 icon: {
   fontSize: { xs: '20px', sm: '24px' },
   color: 'white',
 },
 cardTitle: {
   fontWeight: 'bold',
   color: theme.palette.text.primary,
   fontSize: { xs: '1rem', sm: '1.125rem' },
   marginBottom: '0.5rem',
   display: 'flex',
   alignItems: 'center',
   gap: '0.5rem',
   flexWrap: 'wrap',
   lineHeight: 1.3,
 },
 cardDescription: {
   color: '#6b7280',
   fontSize: { xs: '0.8rem', sm: '0.875rem' },
   lineHeight: 1.6,
   flex: 1,
 },
 newBadge: {
   display: 'inline-flex',
   alignItems: 'center',
   justifyContent: 'center',
   background: '#0d9488',
   color: 'white',
   borderRadius: '12px',
   fontSize: '0.65rem',
   padding: '2px 6px',
   fontWeight: 600,
   flexShrink: 0,
 },
 learnMoreLink: {
   fontSize: { xs: '0.8rem', sm: '0.875rem' },
   fontWeight: 500,
   cursor: 'pointer',
   marginTop: 'auto',
   paddingTop: '1rem',
   display: 'inline-block',
   color: '#0d9488',
   textDecoration: 'none',
   '&:hover': {
     textDecoration: 'underline',
   },
 },
 indicatorsContainer: {
   display: 'flex',
   justifyContent: 'center',
   marginTop: '2rem',
   gap: '0.5rem',
 },
 indicator: {
   width: '12px',
   height: '12px',
   borderRadius: '50%',
   backgroundColor: '#374151',
   cursor: 'pointer',
   transition: 'all 0.3s ease',
   border: '2px solid transparent',
   '&:hover': {
     backgroundColor: '#6b7280',
   },
 },
 activeIndicator: {
   backgroundColor: '#0d9488',
   transform: 'scale(1.2)',
   border: '2px solid rgba(13, 148, 136, 0.3)',
 },
};

export default platformFeaturesStyle;