import theme from '../../../theme';

const aiFeaturesSectionStyle = {
	section: {
		padding: { xs: '4rem 1rem', md: '6rem 2rem' },
		background: '#101010',
		position: 'relative',
		overflow: 'hidden',
	},
	container: {
		maxWidth: '1200px',
		margin: '0 auto',
		position: 'relative',
		zIndex: 5,
	},
	title: {
		color: 'white',
		fontSize: { xs: '2rem', sm: '2.5rem', md: '2.8rem' },
		fontWeight: '700',
		marginBottom: '3rem',
		textAlign: 'center',
	},
	content: {
		display: 'flex',
		flexDirection: { xs: 'column-reverse', md: 'row' },
		alignItems: 'center',
		gap: { xs: '3rem', md: '4rem' },
	},
	featuresList: {
		flex: { xs: '1 1 100%', md: '1 1 60%' },
		display: 'flex',
		flexDirection: 'column',
		gap: '1.5rem',
	},
	featureItem: {
		display: 'flex',
		alignItems: 'flex-start',
		gap: '1.5rem',
		padding: '1.5rem',
		borderRadius: '1rem',
		background: 'rgba(23, 23, 23, 0.4)',
		backdropFilter: 'blur(5px)',
		border: `1px solid ${theme.palette.divider}`,
		transition: 'transform 0.3s ease, border-color 0.3s ease',
		'&:hover': {
			transform: 'translateY(-5px)',
			borderColor: '#115e59',
		},
	},
	featureNumberContainer: {
		width: '2.5rem',
		height: '2.5rem',
		borderRadius: '0.5rem',
		background: 'rgba(94, 234, 212, 0.2)',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		flexShrink: 0,
	},
	featureNumber: {
		color: '#5eead4',
		fontSize: '1.25rem',
		fontWeight: '700',
	},
	featureContent: {
		flex: 1,
	},
	featureTitle: {
		color: 'white',
		fontSize: '1.2rem',
		fontWeight: 'bold',
		marginBottom: '0.5rem',
	},
	featureDescription: {
		color: theme.palette.text.secondary,
		fontSize: '0.95rem',
		lineHeight: 1.6,
	},
	visualizationContainer: {
		flex: { xs: '1 1 100%', md: '1 1 40%' },
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	aiVisualization: {
		position: 'relative',
		width: '100%',
		maxWidth: '400px',
		height: '400px',
	},
	aiCore: {
		position: 'absolute',
		top: '50%',
		left: '50%',
		transform: 'translate(-50%, -50%)',
		width: '100px',
		height: '100px',
		borderRadius: '50%',
		background: 'linear-gradient(145deg, #115e59, #14b8a6)',
		boxShadow: '0 0 30px rgba(94, 234, 212, 0.5)',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		zIndex: 2,
	},
	aiCoreText: {
		color: 'white',
		fontSize: '2rem',
		fontWeight: 'bold',
	},
	aiNodeContainer: {
		position: 'absolute',
		top: '0',
		left: '0',
		width: '100%',
		height: '100%',
	},
	aiNode: {
		position: 'absolute',
		width: '20px',
		height: '20px',
		borderRadius: '50%',
		backgroundColor: '#5eead4',
		boxShadow: '0 0 15px rgba(94, 234, 212, 0.7)',
	},
	aiConnection: {
		position: 'absolute',
		height: '2px',
		background: 'linear-gradient(90deg, transparent, #5eead4, transparent)',
		transformOrigin: 'left center',
	},
	aiPulse: {
		position: 'absolute',
		top: '50%',
		left: '50%',
		transform: 'translate(-50%, -50%)',
		width: '250px',
		height: '250px',
		borderRadius: '50%',
		border: '2px solid rgba(94, 234, 212, 0.3)',
		opacity: 0.6,
		animation: 'pulse 3s infinite',
		'@keyframes pulse': {
			'0%': {
				transform: 'translate(-50%, -50%) scale(0.5)',
				opacity: 0.8,
			},
			'100%': {
				transform: 'translate(-50%, -50%) scale(1.2)',
				opacity: 0,
			},
		},
	},
	aiLabel: {
		position: 'absolute',
		bottom: '0',
		left: '50%',
		transform: 'translateX(-50%)',
		color: '#5eead4',
		fontSize: '1.1rem',
		fontWeight: 'bold',
		textAlign: 'center',
		width: '100%',
	},
	backgroundGradient: {
		position: 'absolute',
		top: '0',
		left: '0',
		width: '100%',
		height: '100%',
		background: 'radial-gradient(ellipse at center, rgba(17, 94, 89, 0.2) 0%, rgba(0, 0, 0, 0) 70%)',
		zIndex: 1,
	},
};

export default aiFeaturesSectionStyle;