import theme from '../../../theme';

const ctaSectionStyle = {
	section: {
		padding: { xs: '6rem 1rem', md: '8rem 2rem' },
		background: '#101010',
		position: 'relative',
		overflow: 'hidden',
	},
	container: {
		maxWidth: '1200px',
		margin: '0 auto',
		position: 'relative',
		zIndex: 5,
	},
	content: {
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		alignItems: 'center',
		gap: { xs: '3rem', md: '4rem' },
	},
	textContent: {
		flex: { xs: '1 1 100%', md: '1 1 50%' },
	},
	title: {
		color: 'white',
		fontSize: { xs: '2.2rem', sm: '2.8rem', md: '3.2rem' },
		fontWeight: '700',
		marginBottom: '1.5rem',
		lineHeight: 1.1,
	},
	description: {
		color: theme.palette.text.secondary,
		fontSize: { xs: '1.1rem', md: '1.2rem' },
		marginBottom: '2.5rem',
		lineHeight: 1.6,
		maxWidth: '500px',
	},
	buttonContainer: {
		display: 'flex',
		gap: '1rem',
	},
	primaryButton: {
		background: '#5eead4',
		color: '#171717',
		padding: '0.75rem 2rem',
		borderRadius: '0.5rem',
		fontWeight: 'bold',
		textTransform: 'none',
		fontSize: '1rem',
		boxShadow: '0 4px 14px rgba(94, 234, 212, 0.4)',
		transition: 'all 0.3s ease',
		'&:hover': {
			background: '#42c6b2',
			transform: 'translateY(-3px)',
			boxShadow: '0 6px 20px rgba(94, 234, 212, 0.5)',
		},
	},
	formContainer: {
		flex: { xs: '1 1 100%', md: '1 1 50%' },
		background: 'rgba(23, 23, 23, 0.6)',
		backdropFilter: 'blur(10px)',
		borderRadius: '1rem',
		padding: { xs: '2rem', md: '3rem' },
		border: `1px solid rgba(94, 234, 212, 0.2)`,
		boxShadow: '0 20px 40px rgba(0, 0, 0, 0.2)',
	},
	formTitle: {
		color: 'white',
		fontSize: '1.5rem',
		fontWeight: 'bold',
		marginBottom: '1rem',
	},
	formDescription: {
		color: theme.palette.text.secondary,
		marginBottom: '2rem',
	},
	inputContainer: {
		marginBottom: '1.5rem',
	},
	inputLabel: {
		color: 'white',
		marginBottom: '0.5rem',
		display: 'block',
		fontSize: '0.9rem',
	},
	input: {
		width: '100%',
		padding: '0.75rem 1rem',
		borderRadius: '0.5rem',
		background: 'rgba(255, 255, 255, 0.05)',
		border: '1px solid rgba(255, 255, 255, 0.1)',
		color: 'white',
		fontSize: '1rem',
		transition: 'all 0.3s ease',
		'&:focus': {
			outline: 'none',
			borderColor: '#5eead4',
			boxShadow: '0 0 0 2px rgba(94, 234, 212, 0.2)',
		},
	},
	formButton: {
		width: '100%',
		background: 'linear-gradient(to right, #5eead4, #14b8a6)',
		color: '#171717',
		padding: '0.75rem',
		borderRadius: '0.5rem',
		fontWeight: 'bold',
		textTransform: 'none',
		fontSize: '1rem',
		border: 'none',
		cursor: 'pointer',
		transition: 'all 0.3s ease',
		'&:hover': {
			background: 'linear-gradient(to right, #14b8a6, #0f766e)',
			transform: 'translateY(-3px)',
			boxShadow: '0 6px 20px rgba(94, 234, 212, 0.3)',
		},
	},
	featuresContainer: {
		display: 'flex',
		justifyContent: 'center',
		gap: '2rem',
		marginTop: '4rem',
	},
	featureItem: {
		flex: 1,
		display: 'flex',
		alignItems: 'center',
		gap: '1rem',
	},
	featureIcon: {
		color: '#5eead4',
		fontSize: '1.5rem',
	},
	featureText: {
		color: theme.palette.text.secondary,
		fontSize: '0.9rem',
	},
	backgroundGradient: {
		position: 'absolute',
		top: '0',
		left: '0',
		width: '100%',
		height: '100%',
		background: 'radial-gradient(ellipse at 70% 50%, rgba(17, 94, 89, 0.2) 0%, rgba(0, 0, 0, 0) 70%)',
		zIndex: 1,
	},
	shapesContainer: {
		position: 'absolute',
		top: '0',
		left: '0',
		width: '100%',
		height: '100%',
		zIndex: 0,
		overflow: 'hidden',
	},
	shape1: {
		position: 'absolute',
		top: '-100px',
		right: '-100px',
		width: '300px',
		height: '300px',
		borderRadius: '50%',
		background: 'rgba(17, 94, 89, 0.15)',
		filter: 'blur(40px)',
	},
	shape2: {
		position: 'absolute',
		bottom: '-50px',
		left: '-150px',
		width: '400px',
		height: '400px',
		borderRadius: '50%',
		background: 'rgba(17, 94, 89, 0.1)',
		filter: 'blur(60px)',
	},
};

export default ctaSectionStyle;