import theme from '../../../theme';

const ctaSectionStyle = {
	section: {
		display: 'flex',
		flexDirection: 'column',
		px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
		marginTop: { xs: '3.5rem', md: '10rem' },
		gap: '2rem',
		alignItems: 'center',
		background: theme.palette.background.default,
		position: 'relative',
		overflow: 'hidden',
		paddingBottom: { xs: '2rem', sm: '4rem' },
	},
	headerContainer: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: '0.5rem',
	},
	tagline: {
		fontFamily: 'monospace',
		fontSize: '0.875rem',
		color: '#0d9488',
		letterSpacing: '0.05em',
		textAlign: 'center',
		textTransform: 'uppercase',
	},
	title: {
		fontSize: { xs: '1.5rem', md: '1.875rem' },
		textAlign: 'center',
		color: 'white',
		fontWeight: '600',
	},
	subtitle: {
		color: '#6b7280',
		textAlign: 'center',
	},
	contentWrapper: {
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		alignItems: 'center',
		gap: { xs: '2rem', md: '3rem' },
		backgroundColor: '#171717',
		borderRadius: '0.5rem',
		padding: { xs: '1.5rem', md: '2rem' },
		border: '1px solid #374151',
		width: '100%',
	},
	textContent: {
		flex: '1',
		display: 'flex',
		flexDirection: 'column',
		alignItems: { xs: 'center', md: 'flex-start' },
		textAlign: { xs: 'center', md: 'left' },
	},
	ctaTitle: {
		fontWeight: '600',
		fontSize: '1.125rem',
		color: 'white',
		marginBottom: '1rem',
	},
	description: {
		color: '#6b7280',
		fontSize: '0.875rem',
		lineHeight: 1.6,
		marginBottom: '1.5rem',
		maxWidth: '500px',
	},
	featureList: {
		marginBottom: '1.5rem',
		display: 'flex',
		flexDirection: 'column',
		gap: '0.5rem',
		alignItems: { xs: 'center', md: 'flex-start' },
	},
	featureItem: {
		display: 'flex',
		alignItems: 'center',
		gap: '0.5rem',
	},
	featureIcon: {
		color: '#0d9488',
		fontSize: '1rem',
	},
	featureText: {
		color: '#6b7280',
		fontSize: '0.875rem',
	},
	button: {
		display: 'inline-flex',
		px: { xs: '0.75rem', sm: '1rem', md: '1.5rem' },
		py: { xs: '0.375rem', sm: '0.5rem', md: '0.5rem' },
		backgroundColor: '#0d9488',
		'&:hover': {
			backgroundColor: '#0f766e',
		},
		color: 'white',
		fontSize: '0.875rem',
		borderRadius: '0.5rem',
		transition: 'background-color 150ms ease',
		border: '1px solid #0d9488',
		textTransform: 'none',
	},
	imageContainer: {
		flex: '1',
		display: { xs: 'none', md: 'flex' },
		justifyContent: 'center',
		alignItems: 'center',
		position: 'relative',
	},
	backgroundGradient: {
		position: 'absolute',
		top: '0',
		left: '0',
		width: '100%',
		height: '100%',
		background: 'radial-gradient(circle at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 70%)',
		zIndex: 1,
	},
};

export default ctaSectionStyle;