import theme from '../../../theme';

const heroSectionStyle = {
	section: {
		padding: { xs: '6rem 1rem 0rem', md: '8rem 2rem 1rem' },
		background: theme.palette.background.default,
		position: 'relative',
		overflow: 'hidden',
		minHeight: '90vh',
		display: 'flex',
		alignItems: 'center',
	},
	container: {
		maxWidth: '1200px',
		margin: '0 auto',
		position: 'relative',
		zIndex: 5,
	},
	content: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		textAlign: 'center',
	},
	title: {
		color: 'white',
		fontSize: { xs: '2rem', sm: '3.5rem', md: '4.5rem' },
		fontWeight: '600',
		marginBottom: '1.5rem',
		lineHeight: 1.1,
		maxWidth: '900px',
	},
	description: {
		color: '#6B7280',
		fontSize: { xs: '1.1rem', md: '1.25rem' },
		marginBottom: '3rem',
		maxWidth: '800px',
		lineHeight: 1.6,
	},
	buttonsContainer: {
		display: 'flex',
		gap: '1rem',
		flexWrap: 'wrap',
		justifyContent: 'center',
		marginBottom: '5rem',
	},
	primaryButton: {
		bmarginTop: '1.5rem',
		color: '#f9fafb',
		fontWeight: 800,
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.7rem 1rem',
		},
		borderRadius: '0.5rem',
		backgroundColor: '#1f2937',
		border: '1px solid #4b5563',
		textTransform: 'none',
		fontSize: '1rem',
		whiteSpace: 'nowrap',
		transition: 'background-color 150ms ease',
		'&:hover': {
			backgroundColor: '#374151',
			borderColor: '#4b5563',
		},
		'&.Mui-disabled': {
			color: '#f9fafb',
			opacity: 0.5,
			backgroundColor: '#1f2937',
			border: '1px solid #374151',
		},
	},
	secondaryButton: {
		background: 'rgba(23, 23, 23, 0.8)',
		color: 'white',
		padding: '0.75rem 2rem',
		borderRadius: '0.375rem',
		fontWeight: 'bold',
		textTransform: 'none',
		fontSize: '1rem',
		border: '1px solid rgba(255, 255, 255, 0.2)',
		transition: 'all 0.3s ease',
		'&:hover': {
			background: 'rgba(30, 30, 30, 0.9)',
			borderColor: 'rgba(255, 255, 255, 0.3)',
			transform: 'translateY(-2px)',
		},
	},
	featuresContainer: {
		display: 'flex',
		justifyContent: 'center',
		gap: { xs: '1rem', md: '4rem' },
		width: '100%',
		maxWidth: '900px',
	},
	featureItem: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		textAlign: 'center',
	},
	featureIconContainer: {
		width: '3.5rem',
		height: '3.5rem',
		borderRadius: '50%',
		background: 'rgba(17, 17, 17, 0.4)',
		backdropFilter: 'blur(5px)',
		border: '1px solid rgba(94, 234, 212, 0.3)',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: '1rem',
	},
	featureIcon: {
		fontSize: '1.5rem',
		color: '#5eead4',
	},
	featureTitle: {
		color: 'white',
		fontWeight: 'bold',
		fontSize: '1rem',
		marginBottom: '0.5rem',
	},
	featureDescription: {
		color: theme.palette.text.secondary,
		fontSize: '0.8rem',
	},
	backgroundGradient: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
		background: 'radial-gradient(50% 50% at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 100%)',
		zIndex: 1,
	},
};

export default heroSectionStyle;