import theme from '../../../theme';

const heroSectionStyle = {
	section: {
		padding: { xs: '8rem 1rem 6rem', md: '10rem 2rem 8rem' },
		background: '#101010',
		position: 'relative',
		overflow: 'hidden',
		minHeight: '90vh',
		display: 'flex',
		alignItems: 'center',
	},
	container: {
		maxWidth: '1200px',
		margin: '0 auto',
		position: 'relative',
		zIndex: 5,
	},
	content: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		textAlign: 'center',
	},
	title: {
		color: 'white',
		fontSize: { xs: '2.5rem', sm: '3.5rem', md: '4.5rem' },
		fontWeight: '700',
		marginBottom: '1.5rem',
		lineHeight: 1.1,
		maxWidth: '900px',
	},
	description: {
		color: theme.palette.text.secondary,
		fontSize: { xs: '1.1rem', md: '1.25rem' },
		marginBottom: '3rem',
		maxWidth: '800px',
		lineHeight: 1.6,
	},
	buttonsContainer: {
		display: 'flex',
		gap: '1rem',
		flexWrap: 'wrap',
		justifyContent: 'center',
		marginBottom: '5rem',
	},
	primaryButton: {
		background: '#5eead4',
		color: '#171717',
		padding: '0.75rem 2rem',
		borderRadius: '0.375rem',
		fontWeight: 'bold',
		textTransform: 'none',
		fontSize: '1rem',
		boxShadow: '0 4px 14px rgba(94, 234, 212, 0.4)',
		transition: 'all 0.3s ease',
		'&:hover': {
			background: '#42c6b2',
			transform: 'translateY(-2px)',
			boxShadow: '0 6px 20px rgba(94, 234, 212, 0.5)',
		},
	},
	secondaryButton: {
		background: 'rgba(23, 23, 23, 0.8)',
		color: 'white',
		padding: '0.75rem 2rem',
		borderRadius: '0.375rem',
		fontWeight: 'bold',
		textTransform: 'none',
		fontSize: '1rem',
		border: '1px solid rgba(255, 255, 255, 0.2)',
		transition: 'all 0.3s ease',
		'&:hover': {
			background: 'rgba(30, 30, 30, 0.9)',
			borderColor: 'rgba(255, 255, 255, 0.3)',
			transform: 'translateY(-2px)',
		},
	},
	featuresContainer: {
		display: 'flex',
		justifyContent: 'center',
		gap: { xs: '1rem', md: '4rem' },
		width: '100%',
		maxWidth: '900px',
	},
	featureItem: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		textAlign: 'center',
	},
	featureIconContainer: {
		width: '3.5rem',
		height: '3.5rem',
		borderRadius: '50%',
		background: 'rgba(17, 17, 17, 0.4)',
		backdropFilter: 'blur(5px)',
		border: '1px solid rgba(94, 234, 212, 0.3)',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: '1rem',
	},
	featureIcon: {
		fontSize: '1.5rem',
		color: '#5eead4',
	},
	featureTitle: {
		color: 'white',
		fontWeight: 'bold',
		fontSize: '1.1rem',
		marginBottom: '0.5rem',
	},
	featureDescription: {
		color: theme.palette.text.secondary,
		fontSize: '0.9rem',
	},
	backgroundGradient: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
		background: 'radial-gradient(50% 50% at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 100%)',
		zIndex: 1,
	},
};

export default heroSectionStyle;