import theme from '../../../theme';

const impactSectionStyle = {
	section: {
		display: 'flex',
		flexDirection: 'column',
		px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
		marginTop: { xs: '3.5rem', md: '6rem' },
		gap: '2rem',
		alignItems: 'center',
		background: theme.palette.background.default,
		position: 'relative',
		overflow: 'hidden',
	},
	headerContainer: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: '0.5rem',
	},
	tagline: {
		fontFamily: 'monospace',
		fontSize: '0.875rem',
		color: '#0d9488',
		letterSpacing: '0.05em',
		textAlign: 'center',
		textTransform: 'uppercase',
	},
	title: {
		fontSize: { xs: '1.5rem', md: '1.875rem' },
		textAlign: 'center',
		color: 'white',
		fontWeight: '600',
	},
	subtitle: {
		color: '#6b7280',
		textAlign: 'center',
	},
	impactGrid: {
		display: 'grid',
		gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' },
		gap: '1rem',
	},
	impactItem: {
		display: 'flex',
		flexDirection: 'column',
		gap: '1rem',
		padding: '1rem',
		borderRadius: '0.5rem',
		backgroundColor: '#171717',
		border: '1px solid #374151',
		backgroundOpacity: 0.6,
		transition: 'transform 0.3s ease, border-color 0.3s ease',
		minHeight: { xs: '140px', sm: 'auto' },
		'&:hover': {
			transform: 'translateY(-5px)',
			borderColor: '#0d9488',
		},
	},
	iconContainer: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontSize: '1.25rem',
		padding: '0.5rem',
		borderRadius: '0.5rem',
		backgroundColor: '#115e59',
		color: 'white',
		width: '45px',
		height: '45px',
	},
	icon: {
		color: 'white',
		fontSize: { xs: '1.25rem', sm: '1.5rem' },
	},
	textContainer: {
		display: 'flex',
		flexDirection: 'column',
		gap: '0.25rem',
	},
	impactTitle: {
		fontSize: '1.125rem',
		color: 'white',
		fontWeight: '600',
	},
	impactDescription: {
		fontSize: '0.875rem',
		color: '#6b7280',
		lineHeight: 1.6,
	},
	metricsTitle: {
		color: 'white',
		fontSize: { xs: '1.4rem', sm: '2rem', md: '2.5rem' },
		fontWeight: '600',
		marginBottom: { xs: '1.5rem', sm: '2.5rem' },
		textAlign: 'center',
	},
	metricsRow: {
		display: 'flex',
		justifyContent: 'center',
		gap: { xs: '1rem', md: '4rem' },
		flexWrap: 'wrap',
	},
	metricItem: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		textAlign: 'center',
	},
	metricValue: {
		color: '#0d9488',
		fontSize: { xs: '2rem', md: '3.5rem' },
		fontWeight: 'bold',
		lineHeight: 1,
		marginBottom: { xs: '0.25rem', sm: '0.5rem' },
	},
	metricLabel: {
		color: 'white',
		fontSize: { xs: '0.875rem', sm: '1rem', md: '1.125rem' },
		fontWeight: 'bold',
		marginBottom: { xs: '0.25rem', sm: '0.5rem' },
	},
	metricDescription: {
		color: '#6b7280',
		fontSize: { xs: '0.625rem', sm: '0.75rem', md: '0.875rem' },
		maxWidth: '200px',
	},
	backgroundGradient: {
		position: 'absolute',
		top: '0',
		left: '0',
		width: '100%',
		height: '100%',
		background: 'radial-gradient(circle at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 70%)',
		zIndex: 1,
	},
};

export default impactSectionStyle;