import theme from '../../../../theme';

const heroSectionStyle = {
	container: {
		background: theme.palette.background.default,
		paddingTop: { sm: '4rem', xs: '2rem' },
		paddingBottom: { sm: '2rem', xs: '1rem' },
	},
	containerBox: {
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		justifyContent: 'space-between',
		alignItems: 'center',
		maxWidth: '75rem',
		width: '100%',
		margin: '0 auto',
		gap: { xs: '1.5rem', sm: '2rem' },
		padding: { xs: '2rem 1rem', sm: '3rem 2rem' },
	},
	contentBox: {
		flex: 1,
		textAlign: { xs: 'center', md: 'left' },
		display: 'flex',
		flexDirection: 'column' as const,
		gap: '1rem',
		alignItems: { xs: 'center', md: 'flex-start' },
	},
	tagline: {
		display: 'inline-block',
		padding: '0.4rem 1rem',
		borderRadius: '1.3rem',
		fontSize: '0.9rem',
		marginBottom: '1rem',
		background: theme.palette.secondary.light,
		color: theme.palette.text.primary,
		fontWeight: 'bold',
		width: { xs: 'auto', sm: 'fit-content' },
		textAlign: 'center' as const,
		whiteSpace: 'nowrap' as const,
		marginTop: '3rem',
	},
	title: {
		fontWeight: '600',
		fontSize: { xs: '1.6rem', sm: '2rem' },
		color: theme.palette.text.primary,
		lineHeight: 1.3,
	},
	subtitle: {
		fontSize: { xs: '1rem', md: '1.1rem' },
		color: theme.palette.secondary.main,
		lineHeight: 1.6,
	},
	listContainer: {
		display: 'flex',
		flexDirection: 'column' as const,
		gap: '0.5rem',
		marginTop: '1rem',
	},
	listItem: {
		fontSize: '1rem',
		lineHeight: 1.6,
		color: '#6B7280',
	},
	ctaButton: {
		marginTop: '1.5rem',
		color: '#f9fafb',
		fontWeight: 800,
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.7rem 1rem',
		},
		borderRadius: '0.5rem',
		backgroundColor: '#1f2937',
		border: '1px solid #4b5563',
		textTransform: 'none',
		fontSize: '0.9rem',
		whiteSpace: 'nowrap',
		transition: 'background-color 150ms ease',
		'&:hover': {
			backgroundColor: '#374151',
			borderColor: '#4b5563',
		},
		'&.Mui-disabled': {
			color: '#f9fafb',
			opacity: 0.5,
			backgroundColor: '#1f2937',
			border: '1px solid #374151',
		},
	},
	imageBox: {
		flex: 1,
		display: 'flex',
		justifyContent: { xs: 'center', md: 'flex-end' },
		alignItems: 'center',
		marginBottom: { xs: '2rem', sm: '2rem' },
		marginTop: { xs: '1rem', sm: '1rem' },
		textAlign: 'center',
		width: '100%',
	},
	imagePlaceholder: {
		width: '100%',
		maxWidth: '28rem',
		minHeight: '16rem',
		borderRadius: '1rem',
		backgroundColor: theme.palette.background.paper,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
};

export default heroSectionStyle;
