import theme from '../../../theme';

const featuredIntegrationsStyle = {
  section: {
    paddingBottom: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: { xs: '0 1rem', sm: '0 2rem' },
  },
  header: {
    textAlign: 'center',
    marginBottom: '3rem',
  },
  title: {
    fontSize: { xs: '1.6rem', sm: '2rem' },
    fontWeight: 600,
    marginBottom: '1rem',
    color: theme.palette.text.primary,
  },
  description: {
    fontSize: '1.1rem',
    color: theme.palette.text.secondary,
    maxWidth: '700px',
    margin: '0 auto',
    lineHeight: 1.6,
  },
  integrationButtons: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: '2rem',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  filterButton: {
    marginRight: '0.5rem',
    marginBottom: '0.5rem',
    borderRadius: '2rem',
    textTransform: 'none',
    fontSize: '0.9rem',
    color: theme.palette.text.secondary,
    borderColor: theme.palette.divider,
    '&.active': {
      backgroundColor: theme.palette.secondary.main,
      color: theme.palette.common.white,
      borderColor: theme.palette.secondary.main,
    },
  },
  integrationsGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(3, 1fr)',
      lg: 'repeat(4, 1fr)',
    },
    gap: { xs: '1.5rem', sm: '1.5rem', md: '1.5rem' },
    width: '100%',
  },
  integrationCard: {
    padding: '1.5rem',
    borderRadius: '1rem',
    background: '#17171799',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    border: `1px solid ${theme.palette.divider}`,
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    position: 'relative',
    overflow: 'hidden',
    '&:hover': {
      transform: 'translateY(-5px)',
    },
  },
  newBadge: {
    position: 'absolute',
    top: '1rem',
    right: '1rem',
    backgroundColor: theme.palette.secondary.main,
    color: theme.palette.common.white,
    padding: '0.25rem 0.75rem',
    borderRadius: '1rem',
    fontSize: '0.75rem',
    fontWeight: 'bold',
  },
  comingSoonBadge: {
    position: 'absolute',
    top: '1rem',
    right: '1rem',
    backgroundColor: theme.palette.grey[700],
    color: theme.palette.common.white,
    padding: '0.25rem 0.75rem',
    borderRadius: '1rem',
    fontSize: '0.75rem',
    fontWeight: 'bold',
  },
  logoContainer: {
    width: '70px',
    height: '70px',
    borderRadius: '0.75rem',
    backgroundColor: theme.palette.background.default,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '1.25rem',
    padding: '0.5rem',
  },
  logoPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '0.5rem',
    backgroundColor: theme.palette.background.darkTransparent,
    color: theme.palette.text.primary,
    fontWeight: 'bold',
    fontSize: '1.rem',
  },
  integrationName: {
    fontSize: '1.1rem',
    fontWeight: 600,
    marginBottom: '0.75rem',
    color: theme.palette.text.primary,
  },
  integrationDescription: {
    fontSize: '0.85rem',
    color: theme.palette.text.secondary,
    lineHeight: 1.6,
    marginBottom: '1.25rem',
    flex: 1,
  },
  categoryChip: {
    display: 'inline-block',
    padding: '0.25rem 0.75rem',
    borderRadius: '1rem',
    color: theme.palette.secondary.dark,
    fontSize: '0.8rem',
    fontWeight: 500,
    marginTop: 'auto',
  },
};

export default featuredIntegrationsStyle;