import theme from '../../../theme';

const featuredIntegrationsStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '10rem', '2xl': '18rem' },
   marginTop: { xs: '0rem', md: '0rem' },
   gap: '2rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   paddingBottom: { xs: '2rem', sm: '4rem' },
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '0rem',
   textAlign: 'center',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 subtitle: {
   fontSize: { xs: '1rem', sm: '1.1rem' },
   color: '#6b7280',
   lineHeight: 1.6,
   textAlign: 'center',
   maxWidth: '700px',
 },
 filterContainer: {
   display: 'flex',
   justifyContent: 'center',
   marginBottom: '2rem',
   flexWrap: 'wrap',
   gap: '0.5rem',
 },
 filterButton: {
   fontSize: '0.875rem',
   padding: '0.5rem 1rem',
   borderRadius: '2rem',
   textTransform: 'none',
   minWidth: 'auto',
   width: 'fit-content',
   whiteSpace: 'nowrap',
 },
 card: {
   display: 'flex',
   flexDirection: 'column',
   gap: '1rem',
   padding: { xs: '1.5rem', sm: '2rem' },
   borderRadius: '0.5rem',
   backgroundColor: '#171717',
   border: '1px solid #374151',
   transition: 'transform 0.3s ease, border-color 0.3s ease',
   height: '100%',
   position: 'relative',
   overflow: 'hidden',
   '&:hover': {
     transform: 'translateY(-5px)',
     borderColor: '#0d9488',
   },
 },
 newBadge: {
   position: 'absolute',
   top: '1rem',
   right: '1rem',
   backgroundColor: '#0d9488',
   color: 'white',
   padding: '0.25rem 0.75rem',
   borderRadius: '1rem',
   fontSize: '0.75rem',
   fontWeight: 'bold',
 },
 comingSoonBadge: {
   position: 'absolute',
   top: '1rem',
   right: '1rem',
   backgroundColor: '#6b7280',
   color: 'white',
   padding: '0.25rem 0.75rem',
   borderRadius: '1rem',
   fontSize: '0.75rem',
   fontWeight: 'bold',
 },
 logoContainer: {
   width: '70px',
   height: '70px',
   borderRadius: '0.75rem',
   backgroundColor: theme.palette.background.paper,
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   marginBottom: '1rem',
   padding: '0.5rem',
 },
 cardTitle: {
   fontSize: '1.125rem',
   fontWeight: 600,
   color: theme.palette.text.primary,
   marginBottom: '0.5rem',
 },
 cardDescription: {
   fontSize: '0.875rem',
   color: '#6b7280',
   lineHeight: 1.7,
   marginBottom: '1rem',
   flex: 1,
 },
 categoryChip: {
   display: 'inline-block',
   padding: '0.25rem 0.75rem',
   borderRadius: '1rem',
   backgroundColor: '#115e59',
   color: 'white',
   fontSize: '0.75rem',
   fontWeight: 500,
   marginTop: 'auto',
   width: 'fit-content',
 },
};

export default featuredIntegrationsStyle;