import theme from '../../../../theme';

const nistComplianceWorkFlowStyles = {
  box: {
    paddingTop: { sm: '3rem', xs: '2rem', md: '1rem' },
    paddingBottom: { sm: '2rem', xs: '1.5rem',md:'5rem'},
    marginTop: '0rem',
    backgroundColor: theme.palette.background.default,
  },
  workflowOuterContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingX: { xs: '1rem', sm: '2rem' },
  },
  workflowContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    textAlign: 'left',
    backgroundColor: "#17171799",
    borderRadius: '1.5rem',
    width: '100%',
    maxWidth: '72rem',
    marginX: 'auto',
    padding: { xs: '2rem', sm: '3rem' },
    border: `1px solid ${theme.palette.divider}`,

  },
  gridWrapper: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: '2rem',
  },
  leftSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    textAlign: 'left',
    gap: '1rem',
  },
  rightSection: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    textAlign: 'left',
  },
  chip: {
    background: theme.palette.secondary.light,
    color: 'white',
    fontWeight: 'bold',
    borderRadius: '2rem',
    padding: '0.4rem 1rem',
    boxShadow: '0rem 0.25rem 0.375rem rgba(0, 0, 0, 0.3)',
    fontSize: '0.9rem',
    display: 'inline-block',
  },
  title: {
    fontWeight: '600',
    color: theme.palette.text.primary,
    fontSize: { xs: '1.6rem', sm: '2rem' },
    lineHeight: 1.2,
    marginTop: '0.5rem',
  },
  description: {
    color: '#9CA3AF',
    fontSize: { xs: '1rem', md: '1.1rem' },
    lineHeight: '1.6',
    maxWidth: '100%',
  },
  cardsGrid: {
    width: '100%',
    marginTop: '2rem',
  },
  card: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "transparent",
    borderRadius: '1rem',
    border: `1px solid ${theme.palette.divider}`,
    padding: '3rem 1.5rem',
    textAlign: 'center',
  },
  cardTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: 'white',
    marginTop: '1.5rem',
    lineHeight: '1.5',
    maxWidth: '80%',
  },
  iconContainer: {
    width: '4rem',
    height: '4rem',
    background: '#115e59',
    borderRadius: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    fontSize: '1.8rem',
    color: 'white',
  },
};

export default nistComplianceWorkFlowStyles;