import theme from '../../../../theme';

const heroSectionStyle = {
   container: {
   	paddingTop: '1rem',
   	paddingBottom: '1rem',
   	background: theme.palette.background.default,
   	padding: { xs: '0.5rem 0.5rem', sm: '1rem 1rem' },
   	position: 'relative',
   	overflow: 'hidden',
   	'&::before': {
   		content: '""',
   		position: 'absolute',
   		top: 0,
   		left: 0,
   		width: '100%',
   		height: '100%',
   		background: `radial-gradient(circle at 70% 30%, ${theme.palette.primary.light}15, transparent 45%)`,
   		pointerEvents: 'none',
   	},
   },
   containerBox: {
   	display: 'flex',
   	flexDirection: { xs: 'column', md: 'row' },
   	justifyContent: 'space-between',
   	alignItems: 'center',
   	width: '100%',
   	maxWidth: '1200px',
   	margin: '0 auto',
   	gap: { xs: '1rem', md: '2rem' },
   	position: 'relative',
   	zIndex: 2,
   },
   leftContentBox: {
   	flex: 1,
   	textAlign: { xs: 'center', md: 'left' },
   	padding: { xs: '0.5rem', md: '2rem' },
   },
   contentBox: {
   	flex: 1,
   	textAlign: { xs: 'center', md: 'left' },
   },
   formBox: {
   	flex: 1,
   	borderRadius: { xs: '0.75rem', md: '1.5rem' },
   	maxWidth: { xs: '100%', md: '600px' },
   	padding: { xs: '0.75rem', md: '2rem' },
   	marginTop: { xs: '0', sm: '0.5rem' },
   	transition: 'transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out',
   	width: { xs: '100%', md: 'auto' },
   },
   formContainer: {
   	padding: { xs: '1rem', md: '2rem' },
   	borderRadius: { xs: '0.75rem', md: '1.5rem' },
   	background: theme.palette.background.paper,
   	width: '100%',
   	maxWidth: { xs: '100%', md: '600px' },
   	marginTop: { xs: '0.5rem', sm: '1.5rem' },
   	border: `1px solid ${theme.palette.divider}`,
   	boxShadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
   },
   formHeading: {
   	fontSize: { xs: '1.4rem', md: '1.8rem' },
   	fontWeight: { xs: 600, md: '600' },
   	color: theme.palette.text.primary,
   	marginBottom: '0.5rem',
   	textAlign: { xs: 'left', md: 'left' },
   },
   compliancesLabel: {
   	fontWeight: 'bold',
   	marginBottom: '0.5rem',
   	color: theme.palette.text.primary,
   	fontSize: { xs: '0.85rem', md: '1rem' },
   },
   tag: {
   	display: 'inline-block',
   	padding: { xs: '0.3rem 0.6rem', md: '0.5rem 1rem' },
   	borderRadius: { xs: '0.75rem', md: '1rem' },
   	background: '#115e59',
   	marginBottom: { xs: '0.5rem', md: '1rem' },
	   marginTop:{xs:'5rem'}
   },
   tagText: {
   	color: 'white',
   	fontWeight: 'bold',
   	fontSize: { xs: '0.7rem', md: '0.9rem' },
   },
   tagline: {
   	background: '#115e59',
   	display: 'inline-block',
   	padding: { xs: '0.3rem 0.8rem', md: '0.5rem 1.2rem' },
   	borderRadius: '2rem',
   	fontSize: { xs: '0.7rem', md: '0.9rem' },
   	marginBottom: { xs: '0.5rem', md: '1rem' },
   	fontWeight: 'bold',
   	transition: 'transform 0.2s ease, box-shadow 0.2s ease',
   	'&:hover': {
   		transform: 'translateY(-3px)',
   		background: theme.customGradients?.buttonHover,
   	},
   	'&:active': {
   		transform: 'translateY(-1px)',
   	},
   },
   title: {
   	fontSize: { xs: '1.4rem', md: '2.8rem' },
   	fontWeight: { xs: 600, md: 'bold' },
   	marginBottom: { xs: '0.5rem', md: '1rem' },
   	color: theme.palette.text.primary,
   	lineHeight: 1.2,
   },
   highlight: {
   	background: theme.customGradients?.primary,
   	WebkitBackgroundClip: 'text',
   	WebkitTextFillColor: 'transparent',
   	display: 'inline',
   },
   chip: {
   	background: '#115e59',
   	color: theme.palette.text.primary,
   	fontWeight: 'bold',
   	marginBottom: { xs: '1rem', md: '1.5rem' },
   	borderRadius: { xs: '0.75rem', md: '1rem' },
   	padding: { xs: '0.3rem 0.6rem', md: '0.5rem 1rem' },
   	boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.1)',
   	alignSelf: { xs: 'center', md: 'flex-start' } as any,

   },
   chipTypography: {
   	fontWeight: 'bold',
   	fontSize: { xs: '0.7rem', md: '0.9rem' },
   },
   mainTitle: {
   	fontSize: { xs: '1.4rem', sm: '2rem' },
   	fontWeight: { xs: 600, md: '600' },
   	marginBottom: { xs: '0.5rem', md: '1rem' },
   	color: theme.palette.text.primary,
   },
   highlightText: {
   	color: theme.palette.primary.light,
   },
   description: {
   	fontSize: { xs: '0.85rem', md: '1.1rem' },
   	color: theme.palette.text.secondary,
   	lineHeight: '1.7',
   	marginBottom: { xs: '1rem', md: '1.5rem' },
   	maxWidth: '550px',
   },
   button: {
   	backgroundColor: '#115e59',
   	color: '#f9fafb',
   	borderRadius: '0.5rem',
   	padding: {
   		xs: '0.2rem 0.4rem',
   		sm: '0.375rem 0.75rem',
   		md: '0.25rem 0.5rem',
   	},
   	textTransform: 'none' as any,
   	fontSize: { xs: '0.85rem', md: '1rem' },
   	whiteSpace: 'nowrap' as any,
   	border: '1px solid #0d9488',
   	transition: 'all 150ms ease',
   	'&:hover': {
   		backgroundColor: '#0f766e',
   	},
   },
   statsContainer: {
   	display: 'flex',
   	flexDirection: 'row' as any,
   	justifyContent: 'center',
   	alignItems: 'flex-start',
   	gap: { xs: '0.5rem', md: '1.5rem' },
   	width: '100%',
   	marginBottom: { xs: '1rem', md: '2rem' },
   },
   statItem: {
   	display: 'flex',
   	flexDirection: 'column' as any,
   	alignItems: 'center',
   	justifyContent: 'center',
   	textAlign: 'center' as any,
   	width: '30%',
   	minWidth: { xs: '60px', md: '80px' },
   },
   statValue: {
   	fontWeight: 'bold',
   	fontSize: { xs: '0.8rem', md: '1rem' },
   	color: theme.palette.text.primary,
   	marginTop: { xs: '0.25rem', md: '0.5rem' },
   },
   statLabel: {
   	color: '#6B7280',
   	fontSize: { xs: '0.7rem', md: '0.9rem' },
   	marginTop: { xs: '0.1rem', md: '0.25rem' },
   	textAlign: 'center' as any,
   	maxWidth: { xs: '70px', md: '90px' },
   },
   featuresContainer: {
   	display: 'flex',
   	flexDirection: { xs: 'column', sm: 'row' } as any,
   	alignItems: { xs: 'center', sm: 'flex-start' } as any,
   	gap: { xs: '0.75rem', md: '1.5rem' },
   	width: '100%',
   	marginBottom: { xs: '1rem', md: '1.5rem' },
   },
   featureItem: {
   	display: 'flex',
   	alignItems: 'center',
   	gap: { xs: '0.5rem', md: '0.8rem' },
   	width: { xs: '100%', sm: 'auto' },
   	justifyContent: { xs: 'flex-start', md: 'center' },
   	maxWidth: { xs: '200px', sm: 'none' },
   },
   iconWrapper: {
   	width: { xs: '2rem', md: '2.5rem' },
   	height: { xs: '2rem', md: '2.5rem' },
   	display: 'flex',
   	alignItems: 'center',
   	justifyContent: 'center',
   	backgroundColor: '#115e59',
   	borderRadius: '50%',
   	boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
   	flexShrink: 0,
   },
   featureIcon: {
   	color: theme.palette.text.primary,
   	fontSize: { xs: '1rem', md: '1.2rem' },
   },
   featureTextWrapper: {
   	display: 'flex',
   	flexDirection: 'column' as any,
   	textAlign: { xs: 'left', md: 'left' } as any,
   },
   featureTitle: {
   	color: theme.palette.text.primary,
   	fontWeight: 'bold',
   	fontSize: { xs: '0.85rem', md: '1rem' },
   	lineHeight: '1.2',
   },
   featureSubtitle: {
   	marginTop: { xs: '0.25rem', md: '0.5rem' },
   	color: '#6B7280',
   	fontSize: { xs: '0.75rem', md: '0.9rem' },
   	lineHeight: '1.2',
   },
   formTitle: {
   	fontSize: { xs: '1.1rem', md: '1.3rem' },
   	fontWeight: 600,
   	marginBottom: { xs: '1rem', md: '1.5rem' },
   	textAlign: 'center',
   	color: theme.palette.text.primary,
   },
   formField: {
   	marginBottom: { xs: '1rem', md: '1.5rem' },
   },
   ctaButton: {
   	marginTop: { xs: '1rem', md: '1.5rem' },
   	color: '#f9fafb',
   	fontWeight: 800,
   	padding: {
   		xs: '0.6rem 1rem',
   		sm: '0.375rem 0.75rem',
   		md: '0.7rem 1rem',
   	},
   	borderRadius: '0.5rem',
   	backgroundColor: '#115e59',
   	border: '1px solid #0d9488',
   	textTransform: 'none' as any,
   	fontSize: { xs: '0.85rem', md: '0.9rem' },
   	whiteSpace: 'nowrap' as any,
   	transition: 'background-color 150ms ease',
   	'&:hover': {
   		backgroundColor: '#0f766e',
   	},
   },
   subtitle: {
   	fontSize: { xs: '0.85rem', md: '1.1rem' },
   	color: theme.palette.text.secondary,
   	lineHeight: 1.6,
   },
   checkboxLabel: {
   	color: '#000000',
   	'& .MuiFormControlLabel-label': {
   		color: '#ffffff',
   		fontSize: { xs: '0.8rem', md: '0.9rem' },
   	},
   },
   formLabel: {
   	color: theme.palette.text.primary,
   	marginBottom: '8px',
   	display: 'block',
   	fontSize: { xs: '0.85rem', md: '1rem' },
   },
   formInput: {
   	backgroundColor: 'rgba(38, 38, 38, 0.5)',
   	color: theme.palette.text.primary,
   	'& .MuiOutlinedInput-root': {
   		fontSize: { xs: '0.85rem', md: '1rem' },
   	},
   	'& .MuiOutlinedInput-notchedOutline': {
   		borderColor: theme.palette.divider,
   	},
   },
   checkbox: {
   	color: theme.palette.secondary.main,
   	padding: { xs: '4px', md: '9px' },
   },
   formHelperText: {
   	marginTop: '4px',
   	color: theme.palette.error.main,
   	fontSize: { xs: '0.7rem', md: '0.875rem' },
   },
   secondaryText: {
   	color: theme.palette.text.secondary,
   	fontSize: { xs: '0.75rem', md: '0.875rem' },
   	marginTop: '8px',
   },
   gridItem: {
   	marginBottom: { xs: '8px', md: '16px' },
   },
};

export default heroSectionStyle;