import theme from '../../../../theme';

const heroSectionStyle = {
  container: {
    background: theme.palette.background.default,
    paddingTop: { sm: '4rem', xs: '2rem' },
    paddingBottom: { sm: '2rem', xs: '1rem' },
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      background: `radial-gradient(circle at 70% 30%, ${theme.palette.primary.light}15, transparent 45%)`,
      pointerEvents: 'none',
    },
  },
  contentWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    maxWidth: '65rem',
    margin: '0 auto',
    padding: { xs: '2rem 1rem', sm: '3rem 2rem' },
  },
  containerBox: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    gap: '2rem',
    position: 'relative',
    zIndex: 2,
  },
  contentBox: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
  },
  formBox: {
    flex: 1,
    borderRadius: '1.5rem',
    maxWidth: '600px',
    padding: '2rem',
    marginTop: { xs: '0.5rem', sm: '0.5rem' },
    transition: 'transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out',
  },
  tagline: {
    display: 'inline-block',
    padding: '0.4rem 1rem',
    borderRadius: '1.3rem',
    fontSize: '0.9rem',
    marginBottom: '1rem',
    background: theme.palette.background.paper,
    color: theme.palette.text.primary,
    fontWeight: 'bold',
    width: { xs: 'auto', sm: 'fit-content' },
    textAlign: 'center' as const,
    whiteSpace: 'nowrap' as const,
    border: `1px solid ${theme.palette.divider}`,
  },
  title: {
    fontWeight: '600',
    fontSize: { xs: '1.6rem', sm: '2rem' },
    color: theme.palette.text.primary,
    lineHeight: 1.3,
    marginBottom: '1rem',
    maxWidth: '45rem',
  },
  subtitle: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: theme.palette.secondary.dark,
    lineHeight: 1.6,
    marginBottom: '1.5rem',
    maxWidth: '40rem',
  },
  description: {
    fontSize: '1rem',
    lineHeight: 1.6,
    color: theme.palette.text.secondary,
    marginBottom: '2rem',
    maxWidth: '35rem',
  },
  ctaButton: {
    marginTop: '1rem',
    color: theme.palette.common.white,
    fontWeight: 800,
    padding: {
      xs: '0.25rem 0.5rem',
      sm: '0.375rem 0.75rem',
      md: '0.7rem 1rem',
    },
    borderRadius: '0.5rem',
    backgroundColor: theme.palette.grey[900],
    border: `1px solid ${theme.palette.grey[600]}`,
    textTransform: 'none',
    fontSize: '0.9rem',
    whiteSpace: 'nowrap',
    transition: 'background-color 150ms ease',
    '&:hover': {
      backgroundColor: theme.palette.grey[800],
      borderColor: theme.palette.grey[600],
    },
  },
  // Form styles
  formContainer: {
    padding: '2rem',
    borderRadius: '1.5rem',
    backgroundColor: theme.palette.background.paper,

    width: '100%',
    maxWidth: '600px',
    marginTop: { xs: '2rem', sm: '1.5rem' },
    border: `1px solid ${theme.palette.divider}`,
  },
  formHeading: {
    fontSize: '1.8rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    marginBottom: '0.5rem',
    textAlign: 'center',
  },
  formLabel: {
    fontWeight: 'bold',
    marginBottom: '0.5rem',
    color: theme.palette.text.primary,
  },
  formField: {
    marginBottom: '1.5rem',
  },
  formButton: {
    marginTop: '1.5rem',
    color: theme.palette.common.white,
    fontWeight: 800,
    padding: {
      xs: '0.5rem 1rem',
      sm: '0.75rem 1.5rem',
    },
    borderRadius: '0.5rem',
    backgroundColor: theme.palette.grey[900],
    border: `1px solid ${theme.palette.grey[600]}`,
    textTransform: 'none',
    fontSize: '0.9rem',
    whiteSpace: 'nowrap',
    transition: 'all 150ms ease',
    '&:hover': {
      backgroundColor: theme.palette.grey[800],
      borderColor: theme.palette.grey[600],
      transform: 'translateY(-2px)',
    },
  },
};

export default heroSectionStyle;
