import type { Metadata } from 'next';
import { Figtree, Atkinson_Hyperlegible } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '../themeRegistry';

const figtree = Figtree({
  variable: '--font-figtree-sans',
  subsets: ['latin'],
});

const atkinsonMono = Atkinson_Hyperlegible({
  variable: '--font-atkinson-mono',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Hexafort Secure - Enterprise Security Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${atkinsonMono.variable} antialiased`}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}