import type { Metadata } from 'next';
import { Figtree, Atkinson_Hyperlegible } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '../themeRegistry';
import Footer from './components/Footer';
import AppBarB2B from './components/Navbar/AppBarB2B';
import CookieBanner from './components/CookieBanner';
import GTM from './components/Gtm';

const figtree = Figtree({
  variable: '--font-figtree-sans',
  subsets: ['latin'],
});

const atkinsonMono = Atkinson_Hyperlegible({
  variable: '--font-atkinson-mono',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Hexafort Secure - Enterprise Security Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${figtree.variable} ${atkinsonMono.variable}`}>
      <head>
        <meta name="emotion-insertion-point" content="" />
      </head>
      <body>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-KR6FJCG6"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          />
        </noscript>
        <ThemeRegistry>
          <GTM />
          <AppBarB2B />
          {children}
          <CookieBanner/>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}