
import type { Metadata } from 'next';
import { Figtree, Atkinson_Hyperlegible } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '../themeRegistry';
import Footer from './components/Footer';
import AppBarB2B from './components/Navbar/AppBarB2B';
import CookieBanner from './components/CookieBanner';

const figtree = Figtree({
  variable: '--font-figtree-sans',
  subsets: ['latin'],
});

const atkinsonMono = Atkinson_Hyperlegible({
  variable: '--font-atkinson-mono',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Hexafort Secure - Enterprise Security Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${figtree.variable} ${atkinsonMono.variable}`}>
      <body>
        <ThemeRegistry>
          <AppBarB2B />
          {children}
         <CookieBanner/>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}

