import theme from '../../../../theme';

const certificationJourneyStyle = {
	box: {
		paddingTop: { sm: '1.5rem', xs: '1rem' },
		paddingBottom: { sm: '2rem', xs: '1.5rem' },
		marginTop: '0rem',
		backgroundColor: theme.palette.background.default,
		px: { xs: 2, sm: 4 },
	},
	container: {
		maxWidth: '1200px',
		marginX: 'auto',
		px: { xs: '1.5rem', sm: '2rem' },
	},
	title: {
		fontWeight: '600',
		color: theme.palette.text.primary,
		fontSize: { xs: '1.6rem', sm: '2rem' },
		marginBottom: '3rem',
		textAlign: 'center',
		marginTop:'2rem'
	},
	gridContainer: {
		display: 'grid',
		gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(3, 1fr)' },
		gap: '1.5rem',
	},
	card: {
		backgroundColor: "#17171799",
		border: `1px solid ${theme.palette.divider}`,
		borderRadius: '1rem',
		padding: '2.5rem 1.5rem',
		transition: 'transform 0.3s ease, box-shadow 0.3s ease',
		minHeight: '220px',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		position: 'relative',
		overflow: 'hidden',
		'&:hover': {
			transform: 'translateY(-7px)',
			boxShadow: '0 10px 20px rgba(0, 0, 0, 0.3)',
			borderColor: theme.palette.primary.main,
		},
		textAlign: 'center',
	},
	stepBadge: {
		position: 'absolute',
		top: '0',
		left: '0',
		backgroundColor: theme.palette.primary.main,
		color: 'white',
		fontSize: '0.85rem',
		fontWeight: '600',
		padding: '0.35rem 1rem',
		borderBottomRightRadius: '0.8rem',
		zIndex: 2,
	},
	iconBox: {
		width: '75px',
		height: '75px',
		borderRadius: '20px',
		background: theme.palette.secondary.main,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: '1.5rem',
		boxShadow: '0 5px 10px rgba(0, 0, 0, 0.3)',
		transition: 'transform 0.3s ease',
	},
	icon: {
		fontSize: '2.2rem',
		color: 'white',
	},
	cardTitle: {
		fontSize: '1.1rem',
		fontWeight: 'bold',
		color: theme.palette.text.primary,
		lineHeight: 1.4,
		marginBottom: '0.5rem',
	},
	cardContent: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		width: '100%',
		zIndex: 1,
	},
	connectingLine: {
		position: 'absolute',
		bottom: '20px',
		right: '-15px',
		width: '30px',
		height: '2px',
		backgroundColor: theme.palette.primary.main,
		display: { xs: 'none', md: 'block' },
		zIndex: 0,
	},
};

export default certificationJourneyStyle;