import theme from '../../../theme';

const bookADemoStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
   marginTop: { xs: '3.5rem', md: '6rem' },
   gap: '2rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   paddingBottom: { xs: '2rem', sm: '4rem' },
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '2rem',
   textAlign: 'center',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 subtitle: {
   fontSize: { xs: '1rem', sm: '1.1rem' },
   color: '#6b7280',
   lineHeight: 1.6,
   textAlign: 'center',
 },
 contentWrapper: {
   display: 'flex',
   flexDirection: { xs: 'column', lg: 'row' },
   alignItems: 'center',
   gap: { xs: '2rem', lg: '4rem' },
   backgroundColor: '#171717',
   borderRadius: '1rem',
   padding: { xs: '2rem', md: '2rem' },
   border: '1px solid #374151',
   width: '100%',
 },
 textContent: {
   flex: '1',
   display: 'flex',
   flexDirection: 'column',
   alignItems: { xs: 'flex-start', lg: 'flex-start' },
   textAlign: { xs: 'left', lg: 'left' },
   width: '100%',
 },
 ctaTitle: {
   fontWeight: '600',
   fontSize: '1.125rem',
   color: 'white',
   marginBottom: '1rem',
 },
 description: {
   color: '#6b7280',
   fontSize: '0.875rem',
   lineHeight: 1.6,
   marginBottom: '1.5rem',
   maxWidth: '500px',
 },
 benefitsList: {
   display: 'flex',
   flexDirection: 'column',
   gap: '0.75rem',
   marginBottom: '2rem',
   alignItems: 'flex-start',
   width: '100%',
 },
 benefitItem: {
   display: 'flex',
   alignItems: 'center',
   gap: '0.75rem',
   width: '100%',
 },
 benefitIcon: {
   color: '#0d9488',
   fontSize: '1.1rem',
 },
 benefitText: {
   color: '#6b7280',
   fontSize: '0.875rem',
   fontWeight: 500,
   textAlign: 'left',
 },
 button: {
   display: 'inline-flex',
   px: { xs: '1rem', md: '1.5rem' },
   py: { xs: '0.5rem', md: '0.75rem' },
   backgroundColor: '#115e59',
   '&:hover': {
     backgroundColor: '#0f766e',
     transform: 'translateY(-2px)',
   },
   color: 'white',
   fontSize: '1rem',
   borderRadius: '0.5rem',
   transition: 'all 0.3s ease',
   border: '1px solid #0d9488',
   textTransform: 'none',
   fontWeight: 600,
 },
 imageContainer: {
   flex: '1',
   display: { xs: 'none', sm: 'flex' },
   justifyContent: 'center',
   alignItems: 'center',
 },
};

export default bookADemoStyle;