import theme from '../../../theme';

const callToActionStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
   marginTop: { xs: '3.5rem', md: '10rem' },
   gap: '2rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   paddingBottom: { xs: '2rem', sm: '4rem' },
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '3rem',
   textAlign: 'center',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 subtitle: {
   fontSize: { xs: '1rem', sm: '1.1rem' },
   color: '#6b7280',
   lineHeight: 1.6,
   textAlign: 'center',
 },
 contentWrapper: {
   display: 'flex',
   flexDirection: { xs: 'column', lg: 'row' },
   alignItems: 'center',
   gap: { xs: '2rem', lg: '4rem' },
   backgroundColor: '#171717',
   borderRadius: '1rem',
   padding: { xs: '2rem', md: '3rem' },
   border: '1px solid #374151',
   width: '100%',
 },
 textContent: {
   flex: '1',
   display: 'flex',
   flexDirection: 'column',
   alignItems: { xs: 'flex-start', lg: 'flex-start' },
   textAlign: { xs: 'left', lg: 'left' },
   width: '100%',
 },
 ctaTitle: {
   fontWeight: '600',
   fontSize: '1.125rem',
   color: 'white',
   marginBottom: '1rem',
 },
 description: {
   color: '#6b7280',
   fontSize: '0.875rem',
   lineHeight: 1.6,
   marginBottom: '1.5rem',
   maxWidth: '500px',
 },
 formBox: {
   flex: '1',
   maxWidth: { xs: '100%', lg: '400px' },
   background: '#262626',
   borderRadius: '0.5rem',
   padding: '1.5rem',
   border: '1px solid #374151',
   width: '100%',
 },
 formTitle: {
   fontSize: '1.125rem',
   fontWeight: 'bold',
   color: theme.palette.text.primary,
   marginBottom: '1rem',
   textAlign: 'center',
 },
};

export default callToActionStyle;