import theme from '../../../theme';

const heroSectionStyle = {
 heroContainer: {
   display: 'flex',
   flexDirection: { xs: 'column', md: 'row' },
   alignItems: 'center',
   gap: { xs: '2rem', md: '4rem' },
   px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
   paddingTop: { xs: '8rem', sm: '8rem', md: '12rem' },
   paddingBottom: { xs: '2.5rem', sm: '2rem', md: '6rem' },
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
 },
 contentBox: {
   flex: 1,
   textAlign: { xs: 'center', md: 'left' },
   display: 'flex',
   flexDirection: 'column',
   gap: { xs: '0.8rem', md: '1rem' },
   maxWidth: { xs: '100%', md: '600px' },
   alignItems: { xs: 'center', md: 'flex-start' },
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textTransform: 'uppercase',
   marginBottom: '0.5rem',
 },
 title: {
   fontSize: { xs: '1.8rem', md: '2.2rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   lineHeight: 1.2,
   marginBottom: { xs: '0.5rem', md: '0.8rem' },
 },
 subtitle: {
   fontSize: { xs: '1rem', sm: '1.1rem', md: '1.2rem' },
   color: '#0d9488',
   lineHeight: 1.5,
   marginBottom: { xs: '0.8rem', md: '1rem' },
 },
 description: {
   color: '#6b7280',
   fontSize: { xs: '0.95rem', md: '1rem' },
   lineHeight: 1.6,
   marginBottom: { xs: '0.5rem', md: '0.8rem' },
   '&:last-of-type': {
     marginBottom: { xs: '1.5rem', md: '2rem' },
   },
 },
 button: {
   fontSize: '0.9rem',
   padding: '0.6rem 1.2rem',
   minWidth: 'auto',
   width: 'fit-content',
   whiteSpace: 'nowrap',
   alignSelf: { xs: 'center', md: 'flex-start' },
   marginBottom: { xs: '1.5rem', md: '2rem' },
 },
 featuresContainer: {
   display: 'flex',
   flexDirection: { xs: 'column', sm: 'row' },
   justifyContent: { xs: 'center', md: 'flex-start' },
   alignItems: 'flex-start',
   gap: { xs: '1rem', md: '2rem' },
   width: '100%',
   marginTop: '1rem',
 },
 featureItem: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   textAlign: 'center',
   gap: '0.5rem',
   flex: { xs: 'none', sm: '1' },
 },
 iconContainer: {
   display: 'flex',
   alignItems: 'center',
   justifyContent: 'center',
   width: '50px',
   height: '50px',
   borderRadius: '10px',
   backgroundColor: '#115e59',
   flexShrink: 0,
 },
 featureIcon: {
   fontSize: '20px',
   color: 'white',
 },
 featureTextWrapper: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   textAlign: 'center',
 },
 featureTitle: {
   fontSize: '1rem',
   fontWeight: 'bold',
   color: theme.palette.text.primary,
   marginBottom: '0.25rem',
 },
 featureSubtitle: {
   fontSize: '0.8rem',
   color: '#6b7280',
 },
 imageBox: {
   flex: 1,
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   maxWidth: { xs: '100%', md: '500px' },
   width: '100%',
 },
 imageWrapper: {
   width: '100%',
   maxWidth: '500px',
   height: { xs: '280px', sm: '350px', md: '400px' },
   position: 'relative',
   borderRadius: '1rem',
   overflow: 'hidden',
   display: 'block', // Ensure it's always displayed
 },
};

export default heroSectionStyle;