
import theme from '../../../theme';

const heroSectionStyle = {
heroContainer: {
  display: 'flex',
  flexDirection: { xs: 'column', md: 'row' },
  alignItems: 'center',
  justifyContent: 'center',
  gap: { xs: '2rem', md: '4rem', lg: '6rem', xl: '8rem' },
  px: {
    xs: '1.5rem',
    sm: '2rem',
    md: '4rem',
    lg: '8rem',
    xl: '12rem',
    '2xl': '16rem'
  },
  paddingTop: { xs: '8rem', sm: '8rem', md: '12rem', lg: '10rem', xl: '8rem' },
  paddingBottom: { xs: '2.5rem', sm: '2rem', md: '6rem', lg: '8rem', xl: '0rem' },
  background: theme.palette.background.default,
  position: 'relative',
  overflow: 'hidden',
  maxWidth: '1600px',
  margin: '0 auto',
  minHeight: { lg: '85vh', xl: '90vh' },
},
contentBox: {
  flex: 1,
  textAlign: { xs: 'center', md: 'left' },
  display: 'flex',
  flexDirection: 'column',
  gap: { xs: '0.8rem', md: '1rem', lg: '1.2rem', xl: '1.5rem' },
  maxWidth: { xs: '100%', md: '600px', lg: '650px', xl: '700px' },
  alignItems: { xs: 'center', md: 'flex-start' },
},
tagline: {
  fontFamily: 'monospace',
  fontSize: { xs: '0.875rem', lg: '0.95rem', xl: '1rem' },
  color: '#0d9488',
  letterSpacing: '0.05em',
  textTransform: 'uppercase',
  marginBottom: { xs: '0.5rem', lg: '0.75rem', xl: '1rem' },
},
title: {
  fontSize: { xs: '1.8rem', md: '2.2rem', lg: '2rem', xl: '2.5rem' },
  fontWeight: 600,
  color: theme.palette.text.primary,
  lineHeight: { xs: 1.2, lg: 1.25, xl: 1.3 },
  marginBottom: { xs: '0.5rem', md: '0.8rem', lg: '1rem', xl: '1.2rem' },
},
subtitle: {
  fontSize: { xs: '1rem', sm: '1.1rem', md: '1.2rem', lg: '1.3rem', xl: '1.4rem' },
  color: '#0d9488',
  lineHeight: 1.5,
  marginBottom: { xs: '0.8rem', md: '1rem', lg: '1rem', xl: '0.5rem' },
},
description: {
  color: '#6b7280',
  fontSize: { xs: '0.95rem', md: '1rem', lg: '1.05rem', xl: '1.1rem' },
  lineHeight: { xs: 1.6, lg: 1.65, xl: 1.7 },
  marginBottom: { xs: '0.5rem', md: '0.8rem', lg: '1rem', xl: '1.2rem' },
  maxWidth: { lg: '90%', xl: '85%' },
  '&:last-of-type': {
    marginBottom: { xs: '1.5rem', md: '2rem', lg: '2.5rem', xl: '3rem' },
  },
},
button: {
  fontSize: { xs: '0.9rem', lg: '1rem', xl: '1.1rem' },
  padding: { xs: '0.6rem 1.2rem', lg: '0.75rem 1.5rem', xl: '0.9rem 1.8rem' },
  minWidth: 'auto',
  width: 'fit-content',
  whiteSpace: 'nowrap',
  alignSelf: { xs: 'center', md: 'flex-start' },
  marginBottom: { xs: '1.5rem', md: '2rem', lg: '2.5rem', xl: '3rem' },
},
featuresContainer: {
  display: 'flex',
  flexDirection: { xs: 'column', sm: 'row' },
  justifyContent: { xs: 'center', md: 'flex-start' },
  alignItems: 'flex-start',
  gap: { xs: '1rem', md: '2rem', lg: '2.5rem', xl: '3rem' },
  width: '100%',
  marginTop: { xs: '1rem', lg: '1.5rem', xl: '2rem' },
},
featureItem: {
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  textAlign: 'center',
  gap: { xs: '0.5rem', lg: '0.75rem', xl: '1rem' },
  flex: { xs: 'none', sm: '1' },
},
iconContainer: {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  width: { xs: '50px', lg: '55px', xl: '60px' },
  height: { xs: '50px', lg: '55px', xl: '60px' },
  borderRadius: '10px',
  backgroundColor: '#115e59',
  flexShrink: 0,
},
featureIcon: {
  fontSize: { xs: '20px', lg: '22px', xl: '24px' },
  color: 'white',
},
featureTextWrapper: {
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  textAlign: 'center',
},
featureTitle: {
  fontSize: { xs: '1rem', lg: '1.05rem', xl: '1.1rem' },
  fontWeight: 'bold',
  color: theme.palette.text.primary,
  marginBottom: '0.25rem',
},
featureSubtitle: {
  fontSize: { xs: '0.8rem', lg: '0.85rem', xl: '0.9rem' },
  color: '#6b7280',
},
imageBox: {
  flex: 1,
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  maxWidth: { xs: '100%', md: '500px', lg: '550px', xl: '600px' },
  width: '100%',
},
imageWrapper: {
  width: '100%',
  maxWidth: { xs: '500px', lg: '550px', xl: '600px' },
  height: { xs: '280px', sm: '350px', md: '400px', lg: '450px', xl: '500px' },
  position: 'relative',
  borderRadius: { xs: '1rem', lg: '1.2rem', xl: '1.5rem' },
  overflow: 'hidden',
  display: 'block',
},
};

export default heroSectionStyle;
