import theme from '../../../theme';

const keyCapabilitiesStyle = {
section: {
  display: 'flex',
  flexDirection: 'column',
  px: { xs: '1.5rem', md: '12rem', xl: '16rem', '2xl': '18rem' },
  marginTop: { xs: '0rem', md: '6rem', xl: '8rem' },
  gap: { xs: '2rem', xl: '3rem' },
  alignItems: 'center',
  background: theme.palette.background.default,
  position: 'relative',
  overflow: 'hidden',
  maxWidth: { xl: '1700px' },
  margin: { xl: '0 auto' },
  paddingBottom: { xl: '2rem' },
},
headerContainer: {
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'center',
  gap: { xs: '0.5rem', xl: '0.75rem' },
  marginBottom: { xs: '3rem', xl: '4rem' },
  textAlign: 'center',
  maxWidth: { xl: '900px' },
},
tagline: {
  fontFamily: 'monospace',
  fontSize: { xs: '0.875rem', xl: '0.95rem' },
  color: '#0d9488',
  letterSpacing: '0.05em',
  textAlign: 'center',
  textTransform: 'uppercase',
},
title: {
  fontSize: { xs: '1.5rem', md: '1.875rem', xl: '2.2rem' },
  fontWeight: 600,
  color: theme.palette.text.primary,
  textAlign: 'center',
},
subtitle: {
  fontSize: { xs: '1rem', sm: '1.1rem', xl: '1.2rem' },
  color: '#6b7280',
  lineHeight: 1.6,
  textAlign: 'center',
},
card: {
  display: 'flex',
  flexDirection: 'column',
  gap: { xs: '1rem', xl: '1.5rem' },
  padding: { xs: '1rem', sm: '2rem', xl: '2.5rem' },
  borderRadius: '0.5rem',
  backgroundColor: '#171717',
  border: '1px solid #374151',
  transition: 'transform 0.3s ease, border-color 0.3s ease',
  height: '100%',
  minHeight: { xs: '200px', sm: '220px', md: '240px', xl: '280px' },
  '&:hover': {
    transform: { xs: 'translateY(-5px)', xl: 'translateY(-8px)' },
    borderColor: '#0d9488',
  },
},
iconContainer: {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  width: { xs: '60px', xl: '70px' },
  height: { xs: '60px', xl: '70px' },
  borderRadius: '12px',
  backgroundColor: '#115e59',
  flexShrink: 0,
},
icon: {
  fontSize: { xs: '24px', xl: '28px' },
  color: 'white',
},
cardTitle: {
  fontWeight: 'bold',
  color: theme.palette.text.primary,
  fontSize: { xs: '1.125rem', xl: '1.25rem' },
  marginBottom: { xs: '0.5rem', xl: '0.75rem' },
  textAlign: 'left',
},
cardDescription: {
  color: '#6b7280',
  fontSize: { xs: '0.875rem', xl: '0.95rem' },
  lineHeight: 1.7,
  flex: 1,
},
};

export default keyCapabilitiesStyle;