import theme from '../../../theme';

const platformWalkthroughStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '14rem', '2xl': '18rem' },
   marginTop: { xs: '3.5rem', md: '2rem' },
   gap: '2rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '0rem',
   textAlign: 'center',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 subtitle: {
   fontSize: { xs: '1rem', sm: '1.1rem' },
   color: '#6b7280',
   lineHeight: 1.6,
   textAlign: 'center',
 },
 carouselContainer: {
   width: '100%',
   position: 'relative',
 },
 carouselWrapper: {
   display: 'flex',
   alignItems: 'center',
   justifyContent: 'center',
   position: 'relative',
   overflow: 'hidden',
 },
 arrowButton: {
   color: 'white',
   position: 'absolute',
   zIndex: 2,
   backgroundColor: 'rgba(23, 23, 23, 0.8)',
   '&:hover': {
     backgroundColor: 'rgba(23, 23, 23, 1)',
   },
   '&:first-of-type': {
     left: { xs: 0, sm: 10 },
   },
   '&:last-of-type': {
     right: { xs: 0, sm: 10 },
   },
 },
 slideContainer: {
   flex: 1,
   width: '100%',
 },
 slide: {
   display: 'flex',
   flexDirection: { xs: 'column', md: 'row' },
   alignItems: 'center',
   justifyContent: 'center',
   gap: '2rem',
   padding: '1rem',
 },
 imageBox: {
   flex: 1,
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   maxWidth: { xs: '100%', md: '50%' },
 },
 image: {
   objectFit: 'contain' as const,
   borderRadius: '1rem',
   maxWidth: '100%',
   height: 'auto',
 },
 imagePlaceholder: {
   width: '100%',
   maxWidth: '400px',
   minHeight: { xs: '200px', sm: '300px', md: '350px' },
   borderRadius: '1rem',
   backgroundColor: '#171717',
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   border: '1px solid #374151',
 },
 contentBox: {
   flex: 1,
   display: 'flex',
   flexDirection: 'column',
   alignItems: { xs: 'center', md: 'flex-start' },
   textAlign: { xs: 'center', md: 'left' },
   maxWidth: { xs: '100%', md: '50%' },
 },
 caption: {
   fontSize: '1.125rem',
   fontWeight: 'bold',
   color: theme.palette.text.primary,
   marginBottom: '0.5rem',
 },
 navigationDots: {
   display: 'flex',
   justifyContent: 'center',
   gap: '0.5rem',
   marginTop: '2rem',
 },
 dot: {
   width: '10px',
   height: '10px',
   borderRadius: '50%',
   backgroundColor: '#374151',
   cursor: 'pointer',
   transition: 'all 0.2s ease',
 },
 activeDot: {
   backgroundColor: '#0d9488',
   transform: 'scale(1.2)',
 },
};

export default platformWalkthroughStyle;