import theme from '../../../theme';

const quickStartOnboardingStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
   marginTop: { xs: '3.5rem', md: '6rem' },
   gap: '3rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   paddingBottom: { xs: '3rem', sm: '5rem' },
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   textAlign: 'center',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 card: {
   display: 'flex',
   flexDirection: 'column',
   borderRadius: '0.75rem',
   backgroundColor: 'transparent',
   border: '1px solid #374151',
   transition: 'transform 0.3s ease, border-color 0.3s ease',
   height: '100%',
   overflow: 'hidden',
   '&:hover': {
     transform: 'translateY(-5px)',
     borderColor: '#0d9488',
   },
 },
 imageContainer: {
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   padding: '2rem',
   backgroundColor: '#115e59',
   height: '150px',
   borderRadius: '0.75rem 0.75rem 0 0',
 },
 contentContainer: {
   padding: '1.5rem',
   backgroundColor: '#171717',
   display: 'flex',
   flexDirection: 'column',
   flexGrow: 1,
   borderRadius: '0 0 0.75rem 0.75rem',
 },
 cardTitle: {
   fontSize: '1.125rem',
   fontWeight: 'bold',
   color: theme.palette.text.primary,
   marginBottom: '0.75rem',
   textAlign: 'center',
 },
 cardDescription: {
   fontSize: '0.875rem',
   color: '#6b7280',
   lineHeight: 1.6,
   flex: 1,
   textAlign: 'center',
 },
};

export default quickStartOnboardingStyle;