import { Theme } from '@mui/material/styles';

const heroSectionStyle = (theme: Theme) => ({
	container: {
		padding: '3rem 1rem',
		background: theme.palette.background.default,
		width: '100%',
	},
	containerBox: {
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		justifyContent: 'space-between',
		alignItems: 'center',
		maxWidth: { xs: '1200px', lg: '1400px', xl: '1600px' },
		margin: '0 auto',
		gap: { xs: '1rem', lg: '3rem', xl: '4rem' },
		marginTop: '2rem',
		px: {
			lg: '8rem',
			xl: '6rem',
			'2xl': '8rem'
		},
	},
	leftContentBox: {
		flex: 1,
		textAlign: { xs: 'center', md: 'left' },
		padding: { xs: '1rem', md: '2rem', lg: '0' },
		maxWidth: { lg: '700px', xl: '800px' },
	},
	rightBox: {
		marginTop: { xs: '1rem', md: '3', lg: '0' },
		flex: 1,
		maxWidth: { xs: '600px', lg: '650px', xl: '700px' },
		width: '100%',
		position: 'relative',
		borderRadius: '12px',
		overflow: 'hidden',
		height: { xs: '550px', lg: '600px', xl: '650px' },
	},
	heroImage: {
		objectFit: 'cover'as const,
	},
	tag: {
		display: 'inline-block',
		padding: '0.5rem 0rem',
		borderRadius: '1rem',
		marginBottom: '0rem',
	},
	tagText: {
		fontFamily: 'monospace',
		fontSize: '0.875rem',
		color: '#0d9488',
		letterSpacing: '0.05em',
		textTransform: 'uppercase',
		marginBottom: '0.5rem',
	},
	title: {
		fontSize: { xs: '1.5rem', md: '1.875rem', lg: '2.2rem', xl: '2.5rem' },
		fontWeight: 600,
		color: theme.palette.text.primary,
		lineHeight: 1.3,
		marginBottom: '1rem',
	},
	highlightText: {
		color: theme.palette.primary.light,
	},
	subtitle: {
		fontSize: { xs: '1rem', sm: '1.1rem', md: '1.2rem', lg: '1.3rem', xl: '1.4rem' },
		color: '#0d9488',
		lineHeight: 1.6,
		marginBottom: '1rem',
	},
	description: {
		fontSize: { xs: '1rem', md: '1.1rem', lg: '1.15rem', xl: '1.2rem' },
		color: theme.palette.text.secondary,
		lineHeight: '1.5',
		marginBottom: '1.5rem',
		maxWidth: { xs: '800px', lg: '90%', xl: '85%' },
	},
	featuresContainer: {
		display: 'flex',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: { xs: '1.5rem', md: '1rem', lg: '2rem', xl: '2.5rem' },
		marginTop: '2rem',
		marginBottom:'3rem',
		width: '100%',
		flexWrap: { xs: 'wrap', md: 'nowrap' },
	},
	featureItem: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		textAlign: 'center',
		gap: '0.5rem',
		flex: '1 1 auto',
		maxWidth: { xs: '100%', sm: '30%' },
	},
	iconWrapper: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		width: '100%',
		minHeight: '2.5rem',
	},
	featureIcon: {
		fontSize: { xs: '1.8rem', md: '2.5rem', lg: '2.8rem', xl: '3rem' },
		color: '#115e59',
	},
	featureTextWrapper: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center',
		width: '100%',
	},
	featureTitle: {
		fontSize: { xs: '0.9rem', md: '1.2rem', lg: '1.3rem', xl: '1.4rem' },
		fontWeight: 'bold',
		color: theme.palette.text.primary,
		textAlign: 'center',
	},
	featureSubtitle: {
		fontSize: { xs: '0.8rem', md: '0.9rem', lg: '0.95rem', xl: '1rem' },
		color: theme.palette.text.secondary,
		textAlign: 'center',
	},
	ctaButton: {
		marginTop: '1.5rem',
		color: theme.palette.common.white,
		fontWeight: 800,
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.7rem 1rem',
		},
		borderRadius: '0.5rem',
		backgroundColor: theme.palette.grey[900],
		border: `1px solid ${theme.palette.grey[600]}`,
		textTransform: 'none',
		fontSize: '0.9rem',
		whiteSpace: 'nowrap',
		transition: 'background-color 150ms ease',
		'&:hover': {
			backgroundColor: theme.palette.grey[800],
			borderColor: theme.palette.grey[600],
		},
		'&.Mui-disabled': {
			color: theme.palette.common.white,
			opacity: 0.5,
			backgroundColor: theme.palette.grey[900],
			border: `1px solid ${theme.palette.grey[700]}`,
		},
	},
});

export default heroSectionStyle;