import theme from '../../../theme';

const processSectionStyle = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
    marginTop: { xs: '3.5rem', md: '6rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
    textAlign: 'center',
  },
  tagline: {
    fontFamily: 'monospace',
    fontSize: '0.875rem',
    color: '#0d9488',
    letterSpacing: '0.05em',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  title: {
    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    textAlign: 'center',
  },
  subtitle: {
    color: '#6b7280',
    textAlign: 'center',
    fontSize: { xs: '1rem', sm: '1.1rem' },
    lineHeight: 1.6,
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    padding: { xs: '1.5rem', sm: '2rem' },
    borderRadius: '0.5rem',
    backgroundColor: '#171717',
    border: '1px solid #374151',
    transition: 'transform 0.3s ease, border-color 0.3s ease',
    height: '100%',
    minHeight: { xs: '200px', sm: '220px', md: '240px' },
    alignItems: 'center',
    textAlign: 'center',
    '&:hover': {
      transform: 'translateY(-5px)',
      borderColor: '#0d9488',
    },
  },
  stepNumber: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    backgroundColor: '#0d9488',
    color: 'white',
    fontSize: '1.5rem',
    fontWeight: 'bold',
    flexShrink: 0,
    marginBottom: '1rem',
  },
  cardTitle: {
    fontSize: '1.125rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    marginBottom: '0.5rem',
    textAlign: 'center',
  },
  cardDescription: {
    fontSize: '0.875rem',
    color: '#6b7280',
    lineHeight: 1.7,
    textAlign: 'center',
    flex: 1,
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flex: 1,
    width: '100%',
  },
};

export default processSectionStyle;