import theme from '../../../theme';

const processSectionStyle = {
  box: {
    paddingTop: { xs: '2rem', sm: '4rem' },
    paddingBottom: { xs: '1rem', sm: '2rem' },
    marginTop: '0rem',
    backgroundColor: theme.palette.background.default,
  },
  workflowOuterContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingX: { xs: '1rem', sm: '1.5rem' },
  },
  workflowContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    borderRadius: '1rem',
    width: '100%',
    maxWidth: '72rem',
    marginX: 'auto',
  },
  centeredTitle: {
    fontWeight: '600',
    color: theme.palette.text.primary,
    fontSize: { xs: '1.6rem', sm: '2rem' },
    textAlign: 'center',
    marginBottom: { xs: '0.75rem', sm: '1rem', md: '1.25rem' },
    paddingX: { xs: '0.5rem', sm: '0' },
  },
  gridWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  gridContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'stretch',
    flexDirection: { xs: 'column', sm: 'row' },
    flexWrap: 'nowrap',
    gap: { xs: '1rem', sm: '1.5rem' },
    maxWidth: { xs: '100%', sm: '100%', md: '72rem' },
  },
  card: {
    flex: { xs: '1 1 100%', sm: '1 1 0' },
    minWidth: { xs: '100%', sm: '0' },
    maxWidth: { xs: '100%', sm: 'none' },
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: theme.palette.background.darkTransparent || '#17171799',
    borderRadius: '1rem',
    padding: { xs: '1.5rem', sm: '2rem' },
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    border: `1px solid ${theme.palette.divider}`,
    margin: { xs: '0', sm: '0' },
    minHeight: { xs: '10rem', sm: '15rem' },
    height: '100%',
    '&:hover': {
      transform: 'scale(1.05)',
      boxShadow: '0rem 0.5rem 1.25rem rgba(0, 0, 0, 0.6)',
      backgroundColor: theme.palette.background.paper,
    },
  },
  cardContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '1rem',
    flex: 1,
    width: '100%',
    textAlign: 'center',
  },
  stepNumber: {
    fontSize: '1rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.secondary.main,
    borderRadius: '50%',
    width: '3rem',
    height: '3rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '0.5rem',
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: 'center',
    marginBottom: '0.5rem',
    lineHeight: 1.6,
  },
  stepDescription: {
    color: theme.palette.text.secondary,
    fontSize: '1rem',
    textAlign: 'center',
    lineHeight: 1.6,
    flex: 1,
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flex: 1,
    width: '100%',
  },
};

export default processSectionStyle;