import theme from '../../../theme';

const processSectionStyle = {
  box: {
    paddingTop: { xs: '0.5rem', sm: '1rem', md: '1rem' },
    paddingBottom: { xs: '0.5rem', sm: '1rem', md: '1rem' },
    marginTop: '0rem',
    backgroundColor: theme.palette.background.default,
  },
  workflowOuterContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingX: { xs: '1rem', sm: '1.5rem' },
  },
  workflowContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    borderRadius: '1rem',
    width: '100%',
    maxWidth: '72rem',
    marginX: 'auto',
  },
  centeredTitle: {
    fontWeight: '600',
    color: theme.palette.text.primary,
    fontSize: { xs: '1.5rem', sm: '2.2rem', md: '2rem' },
    textAlign: 'center',
    marginBottom: { xs: '0.75rem', sm: '1rem', md: '1.25rem' },
    paddingX: { xs: '0.5rem', sm: '0' },
  },
  gridWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
  },
  gridContainer: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'stretch',
    flexDirection: { xs: 'column', sm: 'row' },
    flexWrap: 'nowrap',
    gap: { xs: '0.4rem', sm: '1.2rem' },
    maxWidth: { xs: '100%', sm: '100%', md: '72rem' },
  },
  card: {
    flex: { xs: '1 1 100%', sm: '1 1 0' },
    minWidth: { xs: '100%', sm: '0' },
    maxWidth: { xs: '100%', sm: 'none' },
    display: 'flex',
    flexDirection: { xs: 'row', sm: 'column' },
    justifyContent: { xs: 'flex-start', sm: 'flex-start' },
    alignItems: { xs: 'center', sm: 'center' },
    backgroundColor: '#17171799',
    borderRadius: { xs: '0.4rem', sm: '0.6rem' },
    padding: { xs: '0.6rem', sm: '0.8rem' },
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    border: `1px solid ${theme.palette.divider}`,
    margin: { xs: '0', sm: '0' },
    minHeight: { xs: 'auto', sm: '120px' },
    maxHeight: { xs: '70px', sm: 'auto' },
    '&:hover': {
      transform: { xs: 'none', sm: 'scale(1.02)' },
      boxShadow: { xs: 'none', sm: '0rem 0.2rem 0.5rem rgba(94, 234, 212, 0.12)' },
      backgroundColor: { xs: '#17171799', sm: '#1f1f1f' },
    },
  },
  cardContent: {
    display: 'flex',
    flexDirection: { xs: 'row', sm: 'column' },
    alignItems: { xs: 'center', sm: 'center' },
    justifyContent: { xs: 'flex-start', sm: 'flex-start' },
    gap: { xs: '0.6rem', sm: '0.3rem' },
    flex: 1,
    width: '100%',
  },
  stepNumber: {
    fontSize: { xs: '0.75rem', sm: '0.85rem' },
    fontWeight: 'bold',
    color: 'white',
    backgroundColor: '#115e59',
    borderRadius: '50%',
    width: { xs: '1.6rem', sm: '1.8rem' },
    height: { xs: '1.6rem', sm: '1.8rem' },
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: { xs: '0', sm: '0.3rem' },
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: { xs: '0.85rem', sm: '0.9rem' },
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: { xs: 'left', sm: 'center' },
    marginBottom: { xs: '0.1rem', sm: '0.15rem' },
    lineHeight: { xs: '1.1', sm: '1.2' },
    paddingX: { xs: '0', sm: '0' },
  },
  stepDescription: {
    color: '#6B7280',
    fontSize: { xs: '0.7rem', sm: '0.75rem' },
    textAlign: { xs: 'left', sm: 'center' },
    lineHeight: { xs: '1.2', sm: '1.3' },
    paddingX: { xs: '0', sm: '0' },
    flex: 1,
    display: 'flex',
    alignItems: { xs: 'flex-start', sm: 'center' },
  },
  textContainer: {
    display: { xs: 'flex', sm: 'contents' },
    flexDirection: { xs: 'column', sm: 'column' },
    alignItems: { xs: 'flex-start', sm: 'center' },
    flex: { xs: 1, sm: 'auto' },
  },
};

export default processSectionStyle;