import theme from '../../../theme';

const heroSectionStyle = {
  section: {
    paddingTop: { sm: '4rem', xs: '2rem' },
    backgroundColor: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: { xs: '0 1rem', sm: '0 2rem' },
    position: 'relative',
    zIndex: 1,
  },
  contentContainer: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '2rem',
    backdropFilter: 'blur(6px)',
    borderRadius: '1rem',
    padding: '2.5rem',
  },
  textContent: {
    flex: 1,
    textAlign: { xs: 'center', md: 'left' },
  },
  tagline: {
    display: 'inline-block',
    padding: '0.5rem 1rem',
    borderRadius: '1rem',
    background: '#115e59',
    marginBottom: '1rem',
    color: 'white',
    fontWeight: 'bold',
    fontSize: '0.9rem',
    alignItems: 'center',
    width: { xs: 'auto', sm: 'fit-content' },
  },
  title: {
    fontSize: { xs: '1.8rem', sm: '2.5rem', md: '2rem' },
    fontWeight: '600',
    marginBottom: '1rem',
    color: theme.palette.text.primary,
    lineHeight: 1.3,
  },
  subtitle: {
    fontSize: { xs: '1.1rem', sm: '1.3rem' },
    fontWeight: 500,
    marginBottom: '1rem',
    color: theme.palette.primary.light,
    lineHeight: 1.4,
  },
  description: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: theme.palette.text.secondary,
    lineHeight: '1.5',
    marginBottom: '1.5rem',
    maxWidth: '600px',
  },
  ctaButton: {
    marginTop: '1.5rem',
    color: theme.palette.common.white,
    fontWeight: 800,
    padding: {
      xs: '0.25rem 0.5rem',
      sm: '0.375rem 0.75rem',
      md: '0.7rem 1rem',
    },
    borderRadius: '0.5rem',
    backgroundColor: '#1f2937',
    border: '1px solid #4b5563',
    textTransform: 'none',
    fontSize: '0.9rem',
    whiteSpace: 'nowrap',
    transition: 'background-color 150ms ease',
    '&:hover': {
      backgroundColor: '#374151',
      borderColor: '#4b5563',
      transform: 'translateY(-2px)',
    },
  },
  imageContainer: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    width: '100%',
    maxWidth: '500px',
  },
  imageWrapper: {
    width: '100%',
    aspectRatio: '18/14',
    position: 'relative',
    borderRadius: '0.75rem',
    overflow: 'hidden',
    transition: 'all 0.3s ease',
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: '0 15px 35px rgba(0, 0, 0, 0.3)',
    },
  },
  heroImage: {
    objectFit: 'cover'as const,
  },
  imagePlaceholder: {
    width: '100%',
    aspectRatio: '16/9',
    backgroundColor: '#115e5920',
    borderRadius: '0.75rem',
    border: `1px dashed ${theme.palette.secondary.dark}60`,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '1.5rem',
    color: theme.palette.text.secondary,
    fontSize: '0.9rem',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  highlightText: {
    color: theme.palette.primary.light,
  },
};

export default heroSectionStyle;