import theme from '../../../theme';

const featuresSectionStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
   marginTop: { xs: '3.5rem', md: '6rem' },
   gap: '2rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   paddingBottom: { xs: '2rem', sm: '4rem' },
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '0rem',
   textAlign: 'center',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 subtitle: {
   fontSize: { xs: '1rem', sm: '1.1rem' },
   color: '#6b7280',
   lineHeight: 1.6,
   textAlign: 'center',
 },
 stepsContainer: {
   display: 'flex',
   flexDirection: 'column',
   gap: '0rem',
   width: '90%',
   maxWidth: '1200px',
 },
 stepWrapper: {
   display: 'flex',
   flexDirection: { xs: 'column', md: 'row' },
   alignItems: 'center',
   gap: { xs: '2rem', md: '4rem' },
   width: '100%',
 },
 stepWrapperReverse: {
   flexDirection: { xs: 'column', md: 'row-reverse' },
 },
 imageContainer: {
   flex: 1,
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   maxWidth: { xs: '80%', md: '50%' },
 },
 textContainer: {
   flex: 1,
   display: 'flex',
   flexDirection: 'column',
   alignItems: { xs: 'center', md: 'flex-start' },
   textAlign: { xs: 'center', md: 'left' },
   maxWidth: { xs: '100%', md: '50%' },
   gap: '0.5rem',
 },
 stepNumber: {
   color: '#0d9488',
   fontSize: '0.875rem',
   fontWeight: 'medium',
   textTransform: 'uppercase',
   fontFamily: 'monospace',
   letterSpacing: '0.05em',
 },
 stepTitle: {
   color: theme.palette.text.primary,
   fontWeight: 'bold',
   fontSize: { xs: '1.25rem', md: '1.5rem' },
   marginBottom: '0.5rem',
   lineHeight: 1.2,
 },
 stepDescription: {
   color: '#6b7280',
   fontSize: '1rem',
   lineHeight: 1.6,
 },
};

export default featuresSectionStyle;