import theme from '../../../theme';

const overviewSectionStyle = {
 section: {
   display: 'flex',
   flexDirection: 'column',
   px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
   marginTop: { xs: '0rem', md: '6rem' },
   gap: '2rem',
   alignItems: 'center',
   background: theme.palette.background.default,
   position: 'relative',
   overflow: 'hidden',
   paddingBottom: { xs: '2rem', sm: '4rem' },
 },
 headerContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '2rem',
   textAlign: 'center',
   maxWidth: '900px',
 },
 tagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
   marginBottom: '0.5rem',
 },
 title: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
   marginBottom: '1rem',
 },
 description: {
   fontSize: { xs: '1rem', md: '1.1rem' },
   color: '#6b7280',
   textAlign: 'center',
   lineHeight: 1.6,
   marginBottom: '1rem',
   '&:last-of-type': {
     marginBottom: '0',
   },
 },
 featuresHeaderContainer: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   justifyContent: 'center',
   gap: '0.5rem',
   marginBottom: '0rem',
   textAlign: 'center',
 },
 featuresTagline: {
   fontFamily: 'monospace',
   fontSize: '0.875rem',
   color: '#0d9488',
   letterSpacing: '0.05em',
   textAlign: 'center',
   textTransform: 'uppercase',
 },
 featuresTitle: {
   fontSize: { xs: '1.5rem', md: '1.875rem' },
   fontWeight: 600,
   color: theme.palette.text.primary,
   textAlign: 'center',
 },
 card: {
   display: 'flex',
   flexDirection: 'column',
   gap: '1rem',
   padding: { xs: '1.5rem', sm: '2rem' },
   borderRadius: '0.5rem',
   backgroundColor: '#171717',
   border: '1px solid #374151',
   transition: 'transform 0.3s ease, border-color 0.3s ease',
   height: '100%',
   '&:hover': {
     transform: 'translateY(-5px)',
     borderColor: '#0d9488',
   },
 },
 cardTitle: {
   fontWeight: 'bold',
   color: theme.palette.text.primary,
   fontSize: '1.125rem',
   marginBottom: '0.5rem',
 },
 cardDescription: {
   color: '#6b7280',
   fontSize: '0.875rem',
   lineHeight: 1.7,
   flex: 1,
 },
};

export default overviewSectionStyle;