import theme from '../../../../theme';

export const hipaaComplianceStyles = {
  section: {
    paddingTop: '1rem',
    paddingBottom: '6rem',
    background: theme.palette.background.default,
  },
  containerBox: {
    textAlign: 'center',
    marginBottom: '3rem',
    width: { xs: '100%', md: '80%' },
    margin: '0 auto',
  },
  heading: {
    fontWeight: '600',
    fontSize: { xs: '1.6rem', sm: '2rem' },
    color: theme.palette.text.primary,
  },
  subheading: {
    fontSize: '1.1rem',
    color: theme.palette.text.muted,
    marginBottom: '1rem',
    maxWidth: '800px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#17171799',
    backdropFilter: 'blur(10px)',
    borderRadius: '1rem',
    boxShadow: '0px 6px 15px rgba(0, 0, 0, 0.2)',
    padding: { xs: '1.5rem', sm: '2.5rem' },
    height: '70%',
    minHeight: { xs: '12.5rem', sm: '15.625rem' },
    border: `1px solid ${theme.palette.divider}`,
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    '&:hover': {
      transform: 'scale(1.05)',
      boxShadow: '0rem 0.5rem 1.25rem rgba(0, 0, 0, 0.6)',
    },
  },
  iconContainer: {
    width: '70px',
    height: '70px',
    backgroundColor: '#115e59',
    borderRadius: '6px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '1.5rem',
    padding: '12px',
  },
  iconImage: {
    width: '100%',
    height: '100%',
    objectFit: 'contain'as const,
    maxWidth: '46px',
    maxHeight: '46px'
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    width: '100%',
    flex: 1,
    justifyContent: 'flex-start',
  },
  title: {
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    marginBottom: '1.25rem',
    fontSize: '1.25rem',
    width: '100%',
    textAlign: 'center',
  },
  description: {
    color: '#6B7280',
    textAlign: 'center',
    fontSize: '1rem',
    lineHeight: 1,
    width: '100%',
    padding: '0 0.5rem',
  },
};