import theme from '../../../../theme';

const hipaaComplianceWorkFlowStyles = {
	box: {
		paddingTop: '1rem',
	},
	workflowOuterContainer: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
		padding: '3rem 0',
	},
	workflowContainer: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center',
		background: '#17171799',
		borderRadius: { xs: '0rem', sm: '12px' },
		padding: { xs: '3rem', sm: '4rem 5rem' },
		width: '95%',
		maxWidth: '75rem',
		margin: 'auto',
	},
	gridWrapper: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
		width: '100%',
	},
	leftSection: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-start',
		justifyContent: 'center',
		textAlign: 'left',
		paddingLeft: '1.5rem',
	},
	rightSection: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'left',
	},
	chip: {
		background: '#115e59',
		color: theme.palette.text.primary,
		fontWeight: 'bold',
		marginBottom: '1rem',
		borderRadius: '1rem',
		padding: '0.5rem 1rem',
		zIndex: 2,
	},
	title: {
		fontWeight: '600',
		fontSize: { xs: '1.6rem', sm: '2rem' },
		color: theme.palette.text.primary,
		marginBottom: '1rem',
	},
	description: {
		color: '#6B7280',
		fontSize: 'clamp(1rem, 1.3vw, 1.2rem)',
		lineHeight: '1.6',
		maxWidth: '90%',
	},
	gridContainer: {
		width: '100%',
		marginTop: '3rem',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'stretch',
	},
	cardContainer: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'stretch',
		height: '100%',
		marginTop: '2.5rem',
	},
	card: {
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		background: '#17171799',
		backdropFilter: 'blur(10px)',
		borderRadius: '1rem',
		boxShadow: '0px 6px 15px rgba(0, 0, 0, 0.2)',
		padding: { xs: '1.5rem', sm: '2.5rem' },
		height: '70%',
		minHeight: { xs: '12.5rem', sm: '15.625rem' },
		transition: 'transform 0.3s ease, box-shadow 0.3s ease',
		'&:hover': {
			transform: 'scale(1.05)',
			boxShadow: '0rem 0.5rem 1.25rem rgba(0, 0, 0, 0.6)',
		},
	},
	cardContent: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: '1.2rem',
		flex: 1,
	},
	cardTitle: {
		fontSize: '1rem',
		fontWeight: 'bold',
		color: theme.palette.text.primary,
		textAlign: 'center',
	},
	iconContainer: {
		width: '3.5rem',
		height: '3.5rem',
		backgroundColor: '#115e59',
		borderRadius: '50%',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',

	},
};

export default hipaaComplianceWorkFlowStyles;
