const complianceStyles = {
	menuBox: {
		display: 'flex',
		flexDirection: 'column',
		width: '100%',
		backgroundColor: '#0a0a0a',
		maxHeight: 'calc(100vh - 8rem)',
		overflowY: 'auto',
		'&::-webkit-scrollbar': {
			display: 'none',
		},
		msOverflowStyle: 'none',
		scrollbarWidth: 'none',
	},
	container: {
		display: 'flex',
		width: '100%',
		height: '100%',
	},
	sidebar: {
		width: '270px',
		backgroundColor: '#121212',
		borderRight: '1px solid #262626',
		padding: '1rem 0',
		display: 'flex',
		flexDirection: 'column',
		height: '100%',
		flexShrink: 0,
	},
	sidebarHeader: {
		padding: '0.75rem 1.5rem',
		fontSize: '0.875rem',
		fontWeight: 600,
		color: '#9ca3af',
		textTransform: 'uppercase',
		letterSpacing: '0.05em',
	},
	categoryOption: {
		padding: '0.75rem 1.5rem',
		cursor: 'pointer',
		'&:hover': {
			backgroundColor: '#1f1f1f',
		},
	},
	activeCategoryOption: {
		backgroundColor: '#1f1f1f',
	},
	categoryOptionText: {
		fontSize: '0.875rem',
		fontWeight: 500,
		color: '#f9fafb',
	},
	mainContent: {
		flex: 1,
		padding: '1.5rem 2rem',
		backgroundColor: '#0a0a0a',
		display: 'flex',
		flexDirection: 'column',
	},
	sectionTitle: {
		fontSize: '0.875rem',
		fontWeight: 600,
		color: '#9ca3af',
		marginBottom: '1.5rem',
		textTransform: 'uppercase',
		letterSpacing: '0.05em',
		paddingBottom: '0.5rem',
		borderBottom: '1px solid #262626',
	},
	featureItem: {
		display: 'flex',
		alignItems: 'flex-start',
		cursor: 'pointer',
		marginBottom: '1rem',
		'&:hover': {
			'& $featureTitle': {
				color: '#3B82F6',
			},
		},
	},
	featureIcon: {
		width: '2.5rem',
		height: '2.5rem',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#115e59',
		borderRadius: '0.5rem',
		marginRight: '1rem',
		flexShrink: 0,
	},
	featureContent: {
		flex: 1,
		display: 'flex',
		flexDirection: 'column',
	},
	featureTitle: {
		fontSize: '0.875rem',
		fontWeight: 600,
		color: '#f9fafb',
		marginBottom: '0.25rem',
		display: 'flex',
		alignItems: 'center',
	},
	featureDescription: {
		fontSize: '0.75rem',
		color: '#9ca3af',
		lineHeight: 1.4,
		marginBottom: '0.25rem',
	},
	viewFullButtonContainer: {
		display: 'flex',
		alignItems: 'center',
		marginTop: '1rem',
		padding: '1rem',
		borderRadius: '0.5rem',
		cursor: 'pointer',
		marginBottom: '1rem',
		'&:hover': {
			backgroundColor: 'rgba(49, 46, 46, 0.5)',
		},
	},
	viewButtonIcon: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#115e59',
		width: '2rem',
		height: '2rem',
		borderRadius: '0.25rem',
		marginRight: '1rem',
	},
	viewButtonText: {
		color: '#14b8a6',
		fontWeight: 500,
		fontSize: '0.875rem',
	},
	viewButtonSubText: {
		color: '#9ca3af',
		fontSize: '0.75rem',
		marginTop: '0.25rem',
	},
	mobileContainer: {
		width: '100%',
		padding: '0 1rem',
		paddingTop: '0.5rem',
		backgroundColor: '#0a0a0a',
		color: '#f9fafb',
	},
	complianceItem: {
		display: 'flex',
		alignItems: 'flex-start',
		padding: '0.75rem',
		borderRadius: '0.5rem',
		cursor: 'pointer',
		height: '100%',
		transition: 'all 0.2s ease',
		'&:hover': {
			backgroundColor: '#1f1f1f',
		},
	},
	activeComplianceItem: {
		backgroundColor: '#1f1f1f',
	},
	iconContainer: {
		width: '3.5rem',
		height: '3.5rem',
		display: 'flex',
		backgroundColor: '#115e59',
		borderRadius: '0.5rem',
		alignItems: 'center',
		justifyContent: 'center',
		marginRight: '0.75rem',
		flexShrink: 0,
	},
	itemTitle: {
		fontSize: '0.875rem',
		fontWeight: 600,
		color: '#f9fafb',
		marginBottom: '0.25rem',
	},
	itemDescription: {
		fontSize: '0.75rem',
		color: '#9ca3af',
		lineHeight: 1.4,
	},
	// Mobile View All Item
	viewAllItem: {
		display: 'flex',
		alignItems: 'flex-start',
		padding: '0.75rem',
		borderRadius: '0.5rem',
		cursor: 'pointer',
		height: '100%',
		transition: 'all 0.2s ease',
		'&:hover': {
			backgroundColor: 'rgba(49, 46, 46, 0.5)',
		},
	},
	viewAllIconContainer: {
		width: '3.5rem',
		height: '3.5rem',
		display: 'flex',
		backgroundColor: '#115e59',
		borderRadius: '0.5rem',
		alignItems: 'center',
		justifyContent: 'center',
		marginRight: '0.75rem',
		flexShrink: 0,
	},
	viewAllTitle: {
		fontSize: '0.875rem',
		fontWeight: 600,
		color: '#14b8a6',
		marginBottom: '0.25rem',
	},
	viewAllDescription: {
		fontSize: '0.75rem',
		color: '#9ca3af',
		lineHeight: 1.4,
	},
};

export default complianceStyles;