import theme from '../../../theme';

const testimonialsCarouselStyles = {
 box: {
   background: theme.palette.background.default,
   paddingTop: { xs: '0.5rem', sm: '1.5rem' },
   paddingBottom: { xs: '1rem', sm: '3rem' },
 },
 container: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'center',
   paddingTop: { xs: '0.5rem', sm: '1rem' },
   color: theme.palette.text.primary,
 },
 sectionTitle: {
   fontWeight: { xs: 600, sm: 'bold' },
   color: theme.palette.text.primary,
   textAlign: 'center',
   fontSize: { xs: '1.4rem', sm: '2rem' },
   marginBottom: { xs: '0.75rem', sm: '1.5rem' },
 },
 carouselContainer: {
   width: '100%',
   padding: { xs: '0 0.5rem', sm: '0 1rem' },
   marginTop: { xs: '0.75rem', sm: '1.5rem' },
 },
 cardContainer: {
   display: 'flex',
   justifyContent: 'center',
   padding: { xs: '0.25rem', sm: '0.5rem' },
   marginTop: { xs: '0.25rem', sm: '0.5rem' },
   height: { xs: '350px', sm: '500px' },
 },
 testimonialCard: {
   width: '100%',
   maxWidth: { xs: 280, sm: 350 },
   height: '100%',
   borderRadius: { xs: '0.75rem', sm: '16px' },
   backgroundColor: theme.palette.background.paper,
   backdropFilter: 'blur(10px)',
   padding: 0,
   display: 'flex',
   flexDirection: 'column',
   transition: 'transform 0.3s ease, box-shadow 0.3s ease',
   border: `1px solid ${theme.palette.divider}`,
   overflow: 'hidden',
   '&:hover': {
     transform: 'translateY(-4px)',
     boxShadow: '0 8px 25px rgba(0, 0, 0, 0.15)',
   },
 },
 cardContent: {
   display: 'flex',
   flexDirection: 'column',
   height: '100%',
 },
 contentSection: {
   flex: 1,
   padding: { xs: '1rem 1rem 0.5rem 1rem', sm: '2rem 2rem 1rem 2rem' },
   display: 'flex',
   flexDirection: 'column',
 },
 quoteIcon: {
   fontSize: { xs: '1.5rem', sm: '2rem' },
   color: '#115e59',
   marginBottom: { xs: '0.5rem', sm: '1rem' },
   alignSelf: 'flex-start',
 },
 quoteContainer: {
   flex: 1,
   display: 'flex',
   flexDirection: 'column',
   justifyContent: 'space-between',
 },
 quoteText: {
   color: theme.palette.text.primary,
   textAlign: 'left',
   lineHeight: '1.6',
   fontSize: { xs: '12px', sm: '0.95rem' },
   flex: 1,
 },
 readMoreButton: {
   alignSelf: 'flex-start',
   padding: { xs: '0.2rem 0.4rem', sm: '0.25rem 0.5rem' },
   fontSize: { xs: '12px', sm: '0.8rem' },
   color: '#115e59',
   textTransform: 'none',
   minWidth: 'auto',
   marginTop: { xs: '0.25rem', sm: '0.5rem' },
   '&:hover': {
     backgroundColor: 'rgba(17, 94, 89, 0.1)',
     color: '#0f766e',
   },
 },
 authorContainer: {
   display: 'flex',
   alignItems: 'center',
   gap: { xs: '0.5rem', sm: '1rem' },
   padding: { xs: '0.75rem 1rem', sm: '1.5rem 2rem' },
   backgroundColor: '#115e59',
   marginTop: 'auto',
 },
 avatar: {
   width: { xs: 35, sm: 50 },
   height: { xs: 35, sm: 50 },
   border: '2px dotted white',
   backgroundColor: '#115e59',
   color: 'white',
   fontWeight: 'bold',
   fontSize: { xs: '0.9rem', sm: '1.2rem' },
 },
 authorInfo: {
   display: 'flex',
   flexDirection: 'column',
   alignItems: 'flex-start',
 },
 authorName: {
   fontWeight: 600,
   color: 'white',
   fontSize: { xs: '12px', sm: '1rem' },
   lineHeight: 1.2,
 },
 authorPosition: {
   color: '#115e59',
   fontSize: { xs: '11px', sm: '0.85rem' },
   fontWeight: 500,
   lineHeight: 1.1,
   marginTop: '0.1rem',
 },
 authorCompany: {
   color: 'rgba(255, 255, 255, 0.8)',
   fontSize: { xs: '10px', sm: '0.8rem' },
   marginTop: '0.05rem',
 },
 arrowButtons: {
   display: 'flex',
   justifyContent: 'center',
   alignItems: 'center',
   marginTop: { xs: '1rem', sm: '2rem' },
   gap: { xs: '0.5rem', sm: '1rem' },
 },
 arrowButton: {
   backgroundColor: 'transparent',
   color: theme.palette.text.primary,
   transition: 'background-color 0.2s ease',
   '&:hover': {
     backgroundColor: theme.palette.background.paper,
   },
   borderRadius: '50%',
   padding: { xs: '0.25rem', sm: '0.5rem' },
 },
 arrowIcon: {
   fontSize: { xs: '1rem', sm: '1.5rem' },
 },
 modalPaper: {
   backgroundColor: theme.palette.background.paper,
   color: 'white',
   borderRadius: { xs: '0.75rem', sm: '16px' },
 },
 modalTitle: {
   display: 'flex',
   justifyContent: 'space-between',
   alignItems: 'center',
   borderBottom: `1px solid ${theme.palette.divider}`,
   pb: 2,
 },
 modalTitleText: {
   color: theme.palette.text.primary,
 },
 modalCloseButton: {
   color: theme.palette.text.primary,
 },
 modalContent: {
   pt: 3,
 },
 modalQuoteSection: {
   mb: 3,
 },
 modalQuoteIcon: {
   fontSize: { xs: '1.5rem', sm: '2rem' },
   color: '#115e59',
   mb: 2,
 },
 modalQuoteText: {
   fontStyle: 'italic',
   lineHeight: 1.6,
   fontSize: { xs: '0.85rem', sm: '1rem' },
   color: theme.palette.text.primary,
   mb: 3,
 },
 modalAuthorSection: {
   display: 'flex',
   alignItems: 'center',
   gap: 2,
   p: 2,
   backgroundColor: '#115e59',
   borderRadius: { xs: '0.75rem', sm: '12px' },
 },
 modalAvatar: {
   width: { xs: 45, sm: 60 },
   height: { xs: 45, sm: 60 },
   border: '2px dotted white',
   backgroundColor: '#115e59',
   color: 'white',
   fontWeight: 'bold',
   fontSize: { xs: '1.1rem', sm: '1.4rem' },
 },
 modalAuthorName: {
   fontWeight: 600,
   color: 'white',
   fontSize: { xs: '0.9rem', sm: '1.1rem' },
 },
 modalAuthorPosition: {
   color: '#115e59',
   fontSize: { xs: '12px', sm: '0.9rem' },
   fontWeight: 500,
   lineHeight: 1.1,
   marginTop: '0.1rem',
 },
 modalAuthorCompany: {
   color: 'rgba(255, 255, 255, 0.8)',
   fontSize: { xs: '11px', sm: '0.85rem' },
   lineHeight: 1.1,
   marginTop: '0.05rem',
 },
};

export default testimonialsCarouselStyles;