import theme from '../../../theme';

const testimonialsCarouselStyles = {
  box: {
    background: theme.palette.background.default,
    paddingTop: '1.5rem',
    paddingBottom: '3rem',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    paddingTop: '1rem',
    color: theme.palette.text.primary,
  },
  sectionTitle: {
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: 'center',
    fontSize: { xs: '1.5rem', sm: '2rem' },
    marginBottom: '1.5rem',
  },
  carouselContainer: {
    width: '100%',
    padding: '0 1rem',
    marginTop: '1.5rem',
  },
  cardContainer: {
    display: 'flex',
    justifyContent: 'center',
    padding: '0.5rem',
    marginTop: '0.5rem',
    height: '500px',
  },
  testimonialCard: {
    width: '100%',
    maxWidth: 350,
    height: '100%',
    borderRadius: '16px',
    backgroundColor: theme.palette.background.paper,
    backdropFilter: 'blur(10px)',
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    border: `1px solid ${theme.palette.divider}`,
    overflow: 'hidden',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 8px 25px rgba(0, 0, 0, 0.15)',
    },
  },
  cardContent: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  contentSection: {
    flex: 1,
    padding: '2rem 2rem 1rem 2rem',
    display: 'flex',
    flexDirection: 'column',
  },
  quoteIcon: {
    fontSize: '2rem',
    color: '#115e59',
    marginBottom: '1rem',
    alignSelf: 'flex-start',
  },
  quoteContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  quoteText: {
    color: theme.palette.text.primary,
    textAlign: 'left',
    lineHeight: '1.6',
    fontSize: '0.95rem',
    flex: 1,
  },
  readMoreButton: {
    alignSelf: 'flex-start',
    padding: '0.25rem 0.5rem',
    fontSize: '0.8rem',
    color: '#115e59',
    textTransform: 'none',
    minWidth: 'auto',
    marginTop: '0.5rem',
    '&:hover': {
      backgroundColor: 'rgba(17, 94, 89, 0.1)',
      color: '#0f766e',
    },
  },
  authorContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.5rem 2rem',
    backgroundColor: '#115e59',
    marginTop: 'auto',
  },
  avatar: {
    width: 50,
    height: 50,
    border: '2px dotted white',
    backgroundColor: '#115e59',
    color: 'white',
    fontWeight: 'bold',
    fontSize: '1.2rem',
  },
  authorInfo: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  authorName: {
    fontWeight: 600,
    color: 'white',
    fontSize: '1rem',
    lineHeight: 1.2,
  },
  authorPosition: {
    color: '#115e59',
    fontSize: '0.85rem',
    fontWeight: 500,
    lineHeight: 1.1,
    marginTop: '0.1rem',
  },
  authorCompany: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: '0.8rem',
    marginTop: '0.05rem',
  },
  arrowButtons: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '2rem',
    gap: '1rem',
  },
  arrowButton: {
    backgroundColor: 'transparent',
    color: theme.palette.text.primary,
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: theme.palette.background.paper,
    },
    borderRadius: '50%',
    padding: '0.5rem',
  },
  arrowIcon: {
    fontSize: '1.5rem',
  },
  modalPaper: {
    backgroundColor: theme.palette.background.paper,
    color: 'white',
    borderRadius: '16px',
  },
  modalTitle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: `1px solid ${theme.palette.divider}`,
    pb: 2,
  },
  modalTitleText: {
    color: theme.palette.text.primary,
  },
  modalCloseButton: {
    color: theme.palette.text.primary,
  },
  modalContent: {
    pt: 3,
  },
  modalQuoteSection: {
    mb: 3,
  },
  modalQuoteIcon: {
    fontSize: '2rem',
    color: '#115e59',
    mb: 2,
  },
  modalQuoteText: {
    fontStyle: 'italic',
    lineHeight: 1.6,
    fontSize: '1rem',
    color: theme.palette.text.primary,
    mb: 3,
  },
  modalAuthorSection: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    p: 2,
    backgroundColor: '#115e59',
    borderRadius: '12px',
  },
  modalAvatar: {
    width: 60,
    height: 60,
    border: '2px dotted white',
    backgroundColor: '#115e59',
    color: 'white',
    fontWeight: 'bold',
    fontSize: '1.4rem',
  },
  modalAuthorName: {
    fontWeight: 600,
    color: 'white',
    fontSize: '1.1rem',
  },
  modalAuthorPosition: {
    color: '#115e59',
    fontSize: '0.9rem',
    fontWeight: 500,
    lineHeight: 1.1,
    marginTop: '0.1rem',
  },
  modalAuthorCompany: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: '0.85rem',
    lineHeight: 1.1,
    marginTop: '0.05rem',
  },
};

export default testimonialsCarouselStyles;