import theme from '../../../../theme';

const featuresSectionStyle = {
  box: {
      paddingTop: { xs: '0.5rem', sm: '1rem' },
      paddingBottom: { xs: '0.5rem', sm: '1rem' },
      backgroundColor: theme.palette.background.default,
  },
  container: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'center',
      gap: { xs: 2, sm: 6 },
      marginX: 'auto',
      maxWidth: '1200px',
  },
  containerBox: {
      width: { xs: '100%', sm: '80%', md: '60%' },
      textAlign: 'center' as const,
      marginBottom: { xs: '1.5rem', sm: '2rem' },
  },
  heading: {
      fontWeight: 600,
      fontSize: { xs: '1.4rem', sm: '2rem' },
      color: theme.palette.text.primary,
      marginTop: { xs: '1rem', sm: '1rem' },
  },
  subheading: {
      color: '#6B7280',
      fontSize: { xs: '0.85rem', sm: '1.1rem' },
      maxWidth: '700px',
      marginX: 'auto',
  },
  stepContainer: {
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'flex-start',
      gap: { xs: '1rem', sm: '1.5rem' },
      padding: { xs: '0.75rem', sm: '1rem', md: '1.5rem' },
      background: { xs: '#17171799', md: '#17171799' },
      borderRadius: { xs: '0.75rem', sm: '1rem' },
      boxShadow: '0rem 0.375rem 0.9375rem rgba(0, 0, 0, 0.4)',
      minHeight: { xs: '12rem', sm: '18rem', md: '20rem' },
      textAlign: 'left' as const,
      border: { xs: `1px solid ${theme.palette.divider}`, md: `2px solid ${theme.palette.divider}` },
      transition: 'transform 0.3s ease, box-shadow 0.3s ease',
      '&:hover': {
          transform: 'scale(1.02)',
          boxShadow: '0rem 0.5rem 1.25rem rgba(0, 0, 0, 0.6)',
      },
  },
  iconContainer: {
      width: { xs: '48px', sm: '60px', md: '60px' },
      height: { xs: '48px', sm: '60px', md: '60px' },
      minWidth: { xs: '48px', sm: '60px', md: '60px' },
      minHeight: { xs: '48px', sm: '60px', md: '60px' },
      backgroundColor: '#115e59',
      borderRadius: '0.5rem',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: '0',
      flexShrink: 0,
      '& svg': {
          fontSize: { xs: '24px !important', sm: '32px !important', md: '40px !important' },
          color: 'white !important',
          width: { xs: '24px', sm: '32px', md: '40px' },
          height: { xs: '24px', sm: '32px', md: '40px' },
      },
  },
  icon: {
      fontSize: { xs: '24px', sm: '32px', md: '40px' },
      color: 'white',
      width: { xs: '24px', sm: '32px', md: '40px' },
      height: { xs: '24px', sm: '32px', md: '40px' },
  },
  textContainer: {
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'flex-start',
      width: '100%',
  },
  featureTitle: {
      fontWeight: 'bold',
      color: '#ffffff',
      marginBottom: { xs: '0.5rem', sm: '0.75rem', md: '1rem' },
      fontSize: { xs: '14px', sm: '1.25rem', md: '1.5rem' },
      width: '100%',
      textAlign: 'left' as const,
      marginTop: { xs: '1rem', md: '1.5rem' }
  },
  featureDesc: {
      color: '#6B7280',
      textAlign: 'left' as const,
      fontSize: { xs: '12px', sm: '1rem', md: '1.1rem' },
      lineHeight: 1.6,
      width: '100%',
  },
  // For backward compatibility
  title: {
      fontWeight: 600,
      fontSize: { xs: '1.4rem', sm: '2rem' },
      color: theme.palette.text.primary,
      marginTop: { xs: '0.5rem', sm: '1rem' },
  },
  subtitle: {
      color: '#6B7280',
      fontSize: { xs: '0.85rem', sm: '1.1rem' },
      maxWidth: '700px',
      marginX: 'auto',
  },
  description: {
      color: '#6B7280',
      textAlign: 'left' as const,
      fontSize: { xs: '12px', sm: '1rem', md: '1.1rem' },
      lineHeight: 1.6,
      width: '100%',
  },
  card: {
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'flex-start',
      gap: { xs: '1rem', sm: '1.5rem' },
      padding: { xs: '0.75rem', sm: '1rem', md: '1.5rem' },
      background: '#17171799',
      borderRadius: { xs: '0.75rem', sm: '1rem' },
      boxShadow: '0rem 0.375rem 0.9375rem rgba(0, 0, 0, 0.4)',
      height: { xs: '280px', sm: '320px', md: '350px' },
      textAlign: 'left' as const,
      border: { xs: `1px solid ${theme.palette.divider}`, md: `2px solid ${theme.palette.divider}` },
      transition: 'transform 0.3s ease, box-shadow 0.3s ease',
      '&:hover': {
          transform: 'scale(1.02)',
          boxShadow: '0rem 0.5rem 1.25rem rgba(0, 0, 0, 0.6)',
      },
  },
  cardContent: {
      width: '100%',
      height: '100%',
      display: 'flex',
      flexDirection: 'column' as const,
      padding: '0 !important',
  }
};

export default featuresSectionStyle;