import theme from '../../../theme';

const styles = {
	section: {
	  display: 'flex',
	  flexDirection: 'column',
	  px: { xs: '0rem', md: '12rem', '2xl': '18rem' },
	  marginTop: { xs: '0rem', md: '6rem' },
	  gap: '0rem',
	  alignItems: 'center',
	  background: theme.palette.background.default,
	  position: 'relative',
	  overflow: 'hidden',
	},
	backgroundElements: {
	  position: 'absolute',
	  width: '100%',
	  height: '100%',
	  top: 0,
	  left: 0,
	  zIndex: 1,
	  pointerEvents: 'none',
	},
	gridPattern: {
	  position: 'absolute',
	  inset: 0,
	  backgroundImage:
	    'linear-gradient(rgba(94, 234, 212, 0.025) 1px, transparent 1px), linear-gradient(90deg, rgba(94, 234, 212, 0.025) 1px, transparent 1px)',
	  backgroundSize: '40px 40px',
	  zIndex: 1,
	  opacity: 0.5,
	},
	glowEffect1: {
	  position: 'absolute',
	  width: '30%',
	  height: '30%',
	  borderRadius: '50%',
	  background: 'radial-gradient(circle, rgba(17, 94, 89, 0.15) 0%, transparent 70%)',
	  zIndex: 0,
	  top: '20%',
	  right: '10%',
	},
	headerContainer: {
	  display: 'flex',
	  flexDirection: 'column',
	  alignItems: 'center',
	  justifyContent: 'center',
	  gap: '0.5rem',
	  marginBottom: { xs: '2rem', md: '3rem' },
	  textAlign: 'center',
	  position: 'relative',
	  zIndex: 2,
	},
	tagline: {
	  fontFamily: 'monospace',
	  fontSize: '0.875rem',
	  color: '#0d9488',
	  letterSpacing: '0.05em',
	  textTransform: 'uppercase' as const,
	},
	title: {
	  fontSize: { xs: '1.5rem', md: '1.875rem' },
	  fontWeight: 600,
	  color: theme.palette.text.primary,
	  textAlign: 'center',
	},
	subtitle: {
	  color: '#6b7280',
	  fontSize: { xs: '0.95rem', sm: '1.1rem' },
	  lineHeight: 1.6,
	  textAlign: 'center',
	  maxWidth: '800px',
	},
	gridContainer: {
	  position: 'relative',
	  zIndex: 2,
	  width: '100%',
	},
	card: {
	  display: 'flex',
	  flexDirection: 'column',
	  gap: '1rem',
	  padding: { xs: '1rem', sm: '2rem' },
	  borderRadius: '0.5rem',
	  backgroundColor: '#171717',
	  border: '1px solid #374151',
	  transition: 'transform 0.3s ease, border-color 0.3s ease',
	  height: '100%',
	  minHeight: { xs: '170px', sm: '220px', md: '240px' },
	  '&:hover': {
	    transform: 'translateY(-5px)',
	    borderColor: '#0d9488',
	  },
	},
	iconContainer: {
	  display: 'flex',
	  alignItems: 'center',
	  justifyContent: 'center',
	  width: '50px',
	  height: '50px',
	  borderRadius: '0.5rem',
	  backgroundColor: '#115e59',
	  flexShrink: 0,
	  marginBottom: '1rem',
	},
	icon: {
	  fontSize: '30px',
	  color: 'white',
	},
	cardTitle: {
	  fontSize: { xs: '1rem', md: '1.125rem' },
	  fontWeight: 'bold',
	  color: theme.palette.text.primary,
	  marginBottom: '0.5rem',
	},
	cardDescription: {
	  fontSize: { xs: '0.8rem', md: '0.875rem' },
	  color: '#6b7280',
	  lineHeight: 1.7,
	  flex: 1,
	},
      };
export default styles;
