import theme from '../../../theme';

const styles = {
  section: {
    display: 'flex',
    flexDirection: 'column',
    px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
    marginTop: { xs: '3.5rem', md: '6rem' },
    gap: '2rem',
    alignItems: 'center',
    background: theme.palette.background.default,
    position: 'relative',
    overflow: 'hidden',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '3rem',
    textAlign: 'center',
  },
  tagline: {
    fontFamily: 'monospace',
    fontSize: '0.875rem',
    color: '#0d9488',
    letterSpacing: '0.05em',
    textTransform: 'uppercase' as const,
  },
  title: {
    fontSize: { xs: '1.5rem', md: '1.875rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    textAlign: 'center',
  },
  subtitle: {
    color: '#6b7280',
    fontSize: { xs: '1rem', sm: '1.1rem' },
    lineHeight: 1.6,
    textAlign: 'center',
  },
  ctaWrapper: {
    backgroundColor: '#171717',
    borderRadius: '1rem',
    padding: { xs: '2rem', md: '3rem' },
    display: 'flex',
    flexDirection: { xs: 'column', lg: 'row' },
    alignItems: 'center',
    gap: { xs: '2rem', lg: '4rem' },
    border: '1px solid #374151',
    width: '100%',
    maxWidth: '1200px',
  },
  textContent: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: { xs: 'center', lg: 'flex-start' },
    textAlign: { xs: 'center', lg: 'left' },
    width: '100%',
  },
  ctaTitle: {
    fontSize: { xs: '1.3rem', sm: '1.5rem' },
    fontWeight: 600,
    color: theme.palette.text.primary,
    marginBottom: '1rem',
  },
  description: {
    color: '#6b7280',
    fontSize: '1rem',
    lineHeight: 1.6,
    marginBottom: '1.5rem',
  },
  benefitsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    marginBottom: '2rem',
    alignItems: { xs: 'center', lg: 'flex-start' },
    width: '100%',
  },
  benefitItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    width: '100%',
    justifyContent: { xs: 'center', lg: 'flex-start' },
  },
  benefitIcon: {
    color: '#0d9488',
    fontSize: '1.1rem',
  },
  benefitText: {
    color: '#6b7280',
    fontSize: '0.875rem',
    fontWeight: 500,
  },
  ctaButton: {
    display: 'inline-flex',
    px: { xs: '1rem', md: '1.5rem' },
    py: { xs: '0.5rem', md: '0.75rem' },
    backgroundColor: '#115e59',
    '&:hover': {
      backgroundColor: '#0f766e',
      transform: 'translateY(-2px)',
    },
    color: 'white',
    fontSize: '1rem',
    borderRadius: '0.5rem',
    transition: 'all 0.3s ease',
    border: '1px solid #0d9488',
    textTransform: 'none' as const,
    fontWeight: 600,
    alignSelf: { xs: 'center', lg: 'flex-start' },
  },
  imageContainer: {
    flex: '1',
    display: { xs: 'none', sm: 'flex' },
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageWrapper: {
    width: '100%',
    maxWidth: '300px',
    height: '250px',
    position: 'relative',
    borderRadius: '1rem',
    overflow: 'hidden',
  },
};

export default styles;
