import theme from '../../../theme';

const pitfallsSectionStyle = {
  container: {
    paddingTop: { sm: '3rem', xs: '2rem', md: '4rem' },
    paddingBottom: { sm: '3rem', xs: '2rem', md: '4rem' },
    backgroundColor: theme.palette.background.default,
  },
  outerContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingX: { xs: '1rem', sm: '2rem' },
  },
  innerBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    backgroundColor: 'rgba(23, 23, 23, 0.6)',
    borderRadius: '1.5rem',
    width: '100%',
    maxWidth: '75rem',
    marginX: 'auto',
    padding: { xs: '2rem 1rem', sm: '2rem' },
    border: `1px solid ${theme.palette.divider}`,
  },
  titleSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: '100%',
    maxWidth: '800px',
    marginBottom: '1.5rem',
  },
  chip: {
    background: theme.palette.secondary.light,
    color: theme.palette.common.white,
    fontWeight: 'bold',
    borderRadius: '1rem',
    padding: '0.4rem 1rem',
    boxShadow: '0rem 0.25rem 0.375rem rgba(0, 0, 0, 0.3)',
    fontSize: '0.9rem',
    marginBottom: '0.75rem',
  },
  title: {
    fontSize: { xs: '1.6rem', sm: '2.25rem' },
    fontWeight: '600',
    marginBottom: '0.75rem',
    color: theme.palette.text.primary,
  },
  subtitle: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: theme.palette.text.secondary,
    marginBottom: '1rem',
    maxWidth: '800px',
    lineHeight: 1.4,
  },
  gridContainer: {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: 'repeat(2, 1fr)',
      md: 'repeat(4, 1fr)',
    },
    gap: '1rem',
    marginTop: '1rem',
  },
  pitfallCard: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'rgba(23, 23, 23, 0.6)',
    borderRadius: '0.75rem',

    padding: '1.25rem 1rem',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    border: `1px solid ${theme.palette.divider}`,
    height: 'auto',
    '&:hover': {
      transform: 'scale(1.05)',
      boxShadow: '0rem 0.5rem 1.25rem rgba(94, 234, 212, 0.15)',
      backgroundColor: theme.palette.background.paper,
    },
  },
  pitfallContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '0.5rem',
    width: '100%',
  },
  iconContainer: {
    width: '4rem',
    height: '4rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '0.25rem',
  },
  icon: {
    color: theme.palette.error.light,
    fontSize: '2.5rem',
  },
  solutionIconContainer: {
    width: '1.5rem',
    height: '1.5rem',
    borderRadius: '50%',
    backgroundColor: theme.palette.success.dark,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '0.25rem 0',
  },
  solutionIcon: {
    color: theme.palette.common.white,
    fontSize: '0.9rem',
  },
  pitfallTitle: {
    fontSize: '1rem',
    fontWeight: 'bold',
    color: theme.palette.text.primary,
    textAlign: 'center',
    marginBottom: '0.25rem',
  },
  solutionText: {
    color: theme.palette.success.main,
    fontSize: '0.85rem',
    lineHeight: 1.4,
    textAlign: 'center',
    fontWeight: 'medium',
  },
};

export default pitfallsSectionStyle;
