import theme from '../../../theme';

const pitfallsSectionStyle = {
	container: {
		paddingTop: { sm: '3rem', xs: '2rem', md: '3rem' },
		paddingBottom: { sm: '3rem', xs: '2rem', md: '2rem' },
		backgroundColor: theme.palette.background.default,
	},
	outerContainer: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
		paddingX: { xs: '1rem', sm: '2rem' },
	},
	innerBox: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center',
		borderRadius: '1.5rem',
		width: '100%',
		maxWidth: '75rem',
		marginX: 'auto',
		padding: { xs: '2rem 1rem', sm: '2rem' },
	},
	titleSection: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center',
		width: '100%',
		maxWidth: '800px',
		marginBottom: '1.5rem',
	},
	chip: {
		background: theme.palette.secondary.light,
		color: theme.palette.common.white,
		fontWeight: 'bold',
		borderRadius: '1rem',
		padding: '0.4rem 1rem',
		boxShadow: '0rem 0.25rem 0.375rem rgba(0, 0, 0, 0.3)',
		fontSize: '0.9rem',
		marginBottom: '0.75rem',
	},
	title: {
		fontSize: { xs: '1.6rem', sm: '2.25rem', md: '2rem' },
		fontWeight: '600',
		marginBottom: '0.75rem',
		color: theme.palette.text.primary,
	},
	subtitle: {
		fontSize: { xs: '1rem', md: '1.1rem' },
		color: theme.palette.text.secondary,
		marginBottom: '1rem',
		maxWidth: '800px',
		lineHeight: 1.4,
	},
	gridContainer: {
		width: '100%',
		display: 'grid',
		gridTemplateColumns: {
			xs: '1fr',
			sm: 'repeat(2, 1fr)',
			md: 'repeat(4, 1fr)',
		},
		gap: '1rem',
		marginTop: '1rem',
	},
	pitfallCard: {
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'flex-start',
		alignItems: 'stretch',
		borderRadius: '0.75rem',
		overflow: 'hidden',
		boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
		height: '100%',
		transition: 'transform 0.3s ease',
		'&:hover': {
			transform: 'translateY(-5px)',
			boxShadow: '0 8px 16px rgba(0, 0, 0, 0.3)',
		},
	},
	iconTopSection: {
		backgroundColor: '#115e59',
		padding: '2rem 1rem',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	contentBottomSection: {
		backgroundColor: '#121212',
		padding: '1.5rem 1rem',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'flex-start',
		flex: 1,
		borderTop: '1px solid rgba(255, 255, 255, 0.1)',
	},
	iconContainer: {
		width: '5rem',
		height: '5rem',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
	},
	icon: {
		color: 'white',
		fontSize: '3rem',
	},
	pitfallTitle: {
		fontSize: '1.1rem',
		fontWeight: 'bold',
		color: theme.palette.text.primary,
		textAlign: 'center',
		marginBottom: '0.75rem',
	},
	solutionText: {
		color: theme.palette.text.secondary,
		fontSize: '0.9rem',
		lineHeight: 1.6,
		textAlign: 'center',
	},
};

export default pitfallsSectionStyle;
