import theme from '../../../theme';

const styles = {
	section: {
	  display: 'flex',
	  flexDirection: 'column',
	  px: { xs: '1.5rem', md: '12rem', '2xl': '18rem' },
	  marginTop: { xs: '3.5rem', md: '6rem' },
	  gap: '2rem',
	  alignItems: 'center',
	  background: theme.palette.background.default,
	  position: 'relative',
	  overflow: 'hidden',
	  marginBottom: '3rem',
	},
	headerContainer: {
	  display: 'flex',
	  flexDirection: 'column',
	  alignItems: 'center',
	  justifyContent: 'center',
	  gap: '0.5rem',
	  marginBottom: '3rem',
	  textAlign: 'center',
	},
	chip: {
	  background: '#115e59',
	  color: 'white',
	  fontWeight: 'bold',
	  borderRadius: '1rem',
	  padding: '0.4rem 1rem',
	  fontSize: '0.875rem',
	  marginBottom: '0.75rem',
	  fontFamily: 'monospace',
	  letterSpacing: '0.05em',
	  textTransform: 'uppercase' as const,
	},
	title: {
	  fontSize: { xs: '1.5rem', md: '1.875rem' },
	  fontWeight: 600,
	  color: theme.palette.text.primary,
	  textAlign: 'center',
	},
	subtitle: {
	  color: '#6b7280',
	  fontSize: { xs: '1rem', sm: '1.1rem' },
	  lineHeight: 1.6,
	  textAlign: 'center',
	  maxWidth: '800px',
	},
	gridContainer: {
	  width: '100%',
	},
	card: {
	  display: 'flex',
	  flexDirection: 'column',
	  borderRadius: '0.5rem',
	  overflow: 'hidden',
	  transition: 'transform 0.3s ease, box-shadow 0.3s ease',
	  height: '100%',
	  minHeight: { xs: '200px', sm: '220px', md: '240px' },
	  '&:hover': {
	    transform: 'translateY(-5px)',
	    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.3)',
	  },
	},
	iconTopSection: {
	  backgroundColor: '#115e59',
	  padding: '2rem 1rem',
	  display: 'flex',
	  justifyContent: 'center',
	  alignItems: 'center',
	  flex: '0 0 auto',
	},
	contentBottomSection: {
	  backgroundColor: '#171717',
	  padding: '1.5rem 1rem',
	  display: 'flex',
	  flexDirection: 'column',
	  alignItems: 'center',
	  justifyContent: 'flex-start',
	  flex: 1,
	  border: '1px solid #374151',
	  borderTop: 'none',
	},
	iconContainer: {
	  width: '5rem',
	  height: '5rem',
	  display: 'flex',
	  justifyContent: 'center',
	  alignItems: 'center',
	},
	cardTitle: {
	  fontSize: '1.125rem',
	  fontWeight: 'bold',
	  color: theme.palette.text.primary,
	  textAlign: 'center',
	  marginBottom: '0.75rem',
	},
	cardDescription: {
	  color: '#6b7280',
	  fontSize: '0.875rem',
	  lineHeight: 1.6,
	  textAlign: 'center',
	},
      };
export default styles;
