import { alpha } from '@mui/material/styles';

const aboutUsStyle = {
	section: {
		position: 'relative',
		background: '#101010',
		overflow: 'hidden',
		padding: '0 0 4rem 0',
	},
	backgroundGradient: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
		background: 'radial-gradient(50% 50% at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 100%)',
		zIndex: 1,
	},
	container: {
		maxWidth: '1200px',
		width: '100%',
		position: 'relative',
		zIndex: 5,
	},
	heroContent: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		textAlign: 'center',
		padding: { xs: '6rem 1rem 3rem', md: '8rem 2rem 4rem' },
	},
	mainTitle: {
		fontSize: { xs: '2.5rem', md: '3.5rem' },
		fontWeight: 600,
		color: 'white',
		mb: 2,
		lineHeight: 1.2,
	},
	highlightText: {
		color: '#115e59',
	},
	subtitle: {
		fontSize: { xs: '1rem', md: '1.2rem' },
		color: '#6b7280',
		maxWidth: '700px',
		mb: 0,
	},
	sectionContainer: {
		maxWidth: '1200px',
		width: '100%',
		position: 'relative',
		zIndex: 5,
		mb: 6,
	},
	contentBox: {
		padding: { xs: '2rem', md: '3rem' },
		borderRadius: '16px',
		backdropFilter: 'blur(10px)',
		background: 'rgba(25, 25, 25, 0.5)',
		border: '1px solid rgba(255, 255, 255, 0.05)',
	},
	sectionTitle: {
		fontSize: { xs: '1.8rem', md: '2.2rem' },
		fontWeight: 600,
		color: 'white',
		mb: 2,
		position: 'relative',
		'&:after': {
			content: '""',
			position: 'absolute',
			bottom: '-10px',
			left: 0,
			width: '60px',
			height: '3px',
		},
	},
	sectionText: {
		fontSize: { xs: '1rem', md: '1.1rem' },
		color: '#6b7280',
		mt: 4,
		lineHeight: 1.7,
	},
	sectionDescription: {
		fontSize: '1rem',
		color: '#a3a3a3',
		mt: 4,
		mb: 4,
	},
	valuesGrid: {
		mt: 4,
	},
	valueCard: {
		background: 'rgba(30, 30, 30, 0.7)',
		borderRadius: '12px',
		padding: '2rem',
		height: '100%',
		border: '1px solid rgba(255, 255, 255, 0.08)',
		transition: 'transform 0.3s ease, box-shadow 0.3s ease',
		'&:hover': {
			transform: 'translateY(-5px)',
			boxShadow: '0 10px 20px rgba(0, 0, 0, 0.2)',
		},
	},
	valueIconContainer: {
		background: 'rgba(17, 94, 89, 0.3)',
		width: '60px',
		height: '60px',
		borderRadius: '12px',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: '1.2rem',
	},
	valueIcon: {
		fontSize: '2rem',
		color: '#ffff',
	},
	valueTitle: {
		fontSize: '1.2rem',
		fontWeight: 600,
		color: 'white',
		mb: 1.5,
	},
	valueDescription: {
		fontSize: '0.95rem',
		color: '#6b7280',
		lineHeight: 1.6,
	},
	teamGrid: {
		mt: 4,
	},
	teamCard: {
		background: 'rgba(30, 30, 30, 0.7)',
		borderRadius: '12px',
		padding: '2rem',
		height: '100%',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		textAlign: 'center',
		border: '1px solid rgba(255, 255, 255, 0.08)',
		transition: 'transform 0.3s ease',
		'&:hover': {
			transform: 'translateY(-5px)',
		},
	},
	teamAvatar: {
		width: 100,
		height: 100,
		mb: 2,
		boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
		background: '#115e59',
		fontSize: '2.5rem',
	},
	teamName: {
		fontSize: '1.1rem',
		fontWeight: 600,
		color: 'white',
		mb: 0.5,
	},
	teamPosition: {
		fontSize: '0.9rem',
		color: '#5eead4',
		mb: 2,
		fontWeight: 500,
	},
	teamBio: {
		fontSize: '0.9rem',
		color: '#b3b3b3',
		lineHeight: 1.6,
	},
	storyText: {
		fontSize: { xs: '1rem', md: '1.1rem' },
		color: '#6b7280',
		mt: 4,
		lineHeight: 1.7,
	},
	decorationContainer: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
		zIndex: 1,
		pointerEvents: 'none',
	},
	circle1: {
		position: 'absolute',
		width: '300px',
		height: '300px',
		borderRadius: '50%',
		background: 'rgba(17, 94, 89, 0.1)',
		top: '20%',
		right: '5%',
	},
	circle2: {
		position: 'absolute',
		width: '400px',
		height: '400px',
		borderRadius: '50%',
		background: 'rgba(17, 94, 89, 0.05)',
		bottom: '10%',
		left: '5%',
	},
	glowDot1: {
		position: 'absolute',
		width: '10px',
		height: '10px',
		borderRadius: '50%',
		background: '#5eead4',
		boxShadow: '0 0 20px 5px rgba(94, 234, 212, 0.3)',
		top: '30%',
		left: '15%',
	},
	glowDot2: {
		position: 'absolute',
		width: '15px',
		height: '15px',
		borderRadius: '50%',
		background: '#5eead4',
		boxShadow: '0 0 30px 8px rgba(94, 234, 212, 0.3)',
		bottom: '25%',
		right: '20%',
	},
	glowLine1: {
		position: 'absolute',
		width: '200px',
		height: '1px',
		background: 'linear-gradient(90deg, transparent, rgba(94, 234, 212, 0.5), transparent)',
		transform: 'rotate(45deg)',
		top: '45%',
		left: '25%',
	},
	glowLine2: {
		position: 'absolute',
		width: '250px',
		height: '1px',
		background: 'linear-gradient(90deg, transparent, rgba(94, 234, 212, 0.5), transparent)',
		transform: 'rotate(-30deg)',
		bottom: '30%',
		right: '15%',
	},
};

export default aboutUsStyle;
