import theme from '../../../theme';

const ctaSectionStyle = {
	section: {
		display: 'flex',
		flexDirection: 'column',
		px: {
			xs: '1.5rem',
			sm: '2rem',
			md: '4rem',
			lg: '8rem',
			xl: '8rem',
			'2xl': '12rem',
		},
		marginTop: { xs: '0rem', md: '0rem', lg: '0rem', xl: '0rem' },
		gap: { xs: '2rem', lg: '3rem', xl: '2rem' },
		alignItems: 'center',
		background: theme.palette.background.default,
		position: 'relative',
		overflow: 'hidden',
		paddingBottom: { xs: '2rem', sm: '4rem', md: '2rem', lg: '2rem', xl: '3rem' },
		width: '100%',
	},
	headerContainer: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: { xs: '0.5rem', lg: '1rem', xl: '1rem' },
		textAlign: 'center',
		maxWidth: { lg: '800px', xl: '900px' },
		marginBottom: { lg: '1rem', xl: '1rem' },
	},
	tagline: {
		fontFamily: 'monospace',
		fontSize: '0.875rem',
		color: '#0d9488',
		letterSpacing: '0.05em',
		textAlign: 'center',
		textTransform: 'uppercase',
	},
	title: {
		marginTop: { xs: '3rem', md: '3rem', lg: '1rem', xl: '1rem' },
		fontSize: { xs: '1.8rem', md: '2.2rem', xl: '2.4rem' },
		textAlign: 'center',
		color: 'white',
		fontWeight: '600',
		lineHeight: { xs: 1.2, lg: 1, xl: 1.1 },
	},
	subtitle: {
		color: '#6b7280',
		textAlign: 'center',
		fontSize: { xs: '1rem', sm: '1.1rem', lg: '1.2rem', xl: '1.2rem' },
		lineHeight: 1.6,
		maxWidth: { lg: '90%', xl: '80%' },
	},
	contentWrapper: {
		display: 'flex',
		flexDirection: { xs: 'column', md: 'row' },
		alignItems: 'center',
		gap: { xs: '2rem', md: '3rem', lg: '5rem', xl: '4rem' },
		backgroundColor: '#171717',
		borderRadius: { xs: '0.5rem', lg: '0.75rem', xl: '0.75rem' },
		padding: { xs: '1.5rem', md: '2rem', lg: '3.5rem', xl: '3rem' },
		border: '1px solid #374151',
		width: '100%',
		maxWidth: { lg: '1300px', xl: '1200px' },
		margin: '0 auto',
	},
	textContent: {
		flex: '1',
		display: 'flex',
		flexDirection: 'column',
		alignItems: { xs: 'center', md: 'flex-start' },
		textAlign: { xs: 'center', md: 'left' },
		width: '100%',
		maxWidth: { lg: '600px', xl: '550px' },
	},
	ctaTitle: {
		fontWeight: '600',
		fontSize: { xs: '1.125rem', lg: '1.25rem', xl: '1.3rem' },
		color: 'white',
		marginBottom: { xs: '1rem', lg: '1.5rem', xl: '1.5rem' },
		lineHeight: { xs: 1.3, lg: 1.35, xl: 1.35 },
	},
	description: {
		color: '#6b7280',
		fontSize: { xs: '0.875rem', lg: '0.95rem', xl: '0.95rem' },
		lineHeight: { xs: 1.6, lg: 1.65, xl: 1.65 },
		marginBottom: { xs: '1.5rem', lg: '2rem', xl: '2rem' },
		maxWidth: '500px',
	},
	featureList: {
		marginBottom: { xs: '1.5rem', lg: '2.5rem', xl: '2rem' },
		display: 'flex',
		flexDirection: 'column',
		gap: { xs: '0.75rem', lg: '1.25rem', xl: '1rem' },
		width: '100%',
		alignItems: 'flex-start',
	},
	featureItem: {
		display: 'flex',
		alignItems: 'flex-start',
		gap: { xs: '0.75rem', lg: '1.25rem', xl: '1rem' },
		width: '100%',
	},
	featureIcon: {
		color: '#0d9488',
		fontSize: { xs: '1.25rem', lg: '1.375rem', xl: '1.3rem' },
		flexShrink: 0,
		marginTop: '0.125rem',
	},
	featureText: {
		color: '#6b7280',
		fontSize: { xs: '0.875rem', lg: '0.95rem', xl: '0.95rem' },
		lineHeight: { xs: 1.5, lg: 1.6, xl: 1.6 },
		flex: 1,
		textAlign: 'left',
	},
	button: {
		display: 'inline-flex',
		px: { xs: '0.75rem', sm: '1rem', md: '1.5rem', lg: '1rem', xl: '1.2rem' },
		py: { xs: '0.375rem', sm: '0.5rem', md: '0.5rem', lg: '0.5rem', xl: '0.7rem' },
		backgroundColor: '#115e59',
		'&:hover': {
			backgroundColor: '#0f766e',
			transform: { lg: 'translateY(-2px)', xl: 'translateY(-2px)' },
		},
		color: 'white',
		fontSize: { xs: '0.875rem', lg: '0.8rem', xl: '0.9rem' },
		borderRadius: '0.5rem',
		transition: 'all 150ms ease',
		border: '1px solid #0d9488',
		textTransform: 'none',
		marginTop: { xs: '1rem', lg: '1.5rem', xl: '1.5rem' },
		fontWeight: 600,
		minWidth: { lg: 'auto', xl: 'auto' },
	},
	imageContainer: {
		flex: '1',
		display: { xs: 'none', md: 'flex' },
		justifyContent: 'center',
		alignItems: 'center',
		position: 'relative',
		maxWidth: { lg: '500px', xl: '450px' },
	},
	backgroundGradient: {
		position: 'absolute',
		top: '0',
		left: '0',
		width: '100%',
		height: '100%',
		background: 'radial-gradient(circle at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 70%)',
		zIndex: 1,
	},
};

export default ctaSectionStyle;
