import { alpha } from '@mui/material/styles';

const contactStyle = {
	section: {
		minHeight: '100vh',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		padding: { xs: '5rem 1rem', sm: '3rem 1.5rem', md: '3rem 2rem' },
		position: 'relative',
		overflow: 'hidden',
		background: '#101010',
	},
	backgroundGradient: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
		background: 'radial-gradient(50% 50% at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 100%)',
		zIndex: 1,
	},
	container: {
		maxWidth: '1200px',
		width: '100%',
		position: 'relative',
		zIndex: 5,
	},
	contentBox: {
		padding: { xs: '1.5rem', sm: '2rem', md: '3rem' },
		borderRadius: '16px',
		backdropFilter: 'blur(10px)',
		
	},
	title: {
		fontSize: { xs: '2rem', sm: '2.5rem', md: '3.5rem' },
		fontWeight: 600,
		color: 'white',
		mb: 2,
		lineHeight: 1.2,
	},
	highlightText: {
		color: '#115e59',
	},
	description: {
		fontSize: { xs: '0.9rem', sm: '1rem', md: '1.1rem' },
		color: '#a3a3a3',
		mb: { xs: 3, md: 5 },
		maxWidth: '800px',
	},
	mainContent: {
		mt: { xs: 2, md: 4 },
	},
	contactInfoContainer: {
		background: '#17171799',
		borderRadius: '12px',
		padding: { xs: '1.5rem', md: '2rem' },
		height: '100%',
		display: 'flex',
		flexDirection: 'column',
		border: '1px solid rgba(255, 255, 255, 0.1)',
	},
	infoTitle: {
		fontSize: { xs: '1.1rem', md: '1.25rem' },
		fontWeight: 600,
		color: 'white',
		mb: 3,
	},
	contactItem: {
		display: 'flex',
		alignItems: 'flex-start',
		mb: 3,
		gap: 2,
	},
	contactIcon: {
		color: '#ffff',
		fontSize: { xs: '1.25rem', md: '1.5rem' },
	},
	contactLabel: {
		color: '#a3a3a3',
		fontSize: '0.875rem',
		mb: 0.5,
	},
	contactValue: {
		color: 'white',
		fontSize: { xs: '0.9rem', md: '1rem' },
	},
	reachOutBox: {
		marginTop: 'auto',
		background: 'rgba(17, 94, 89, 0.2)',
		borderRadius: '8px',
		padding: { xs: '1.25rem', md: '1.5rem' },
		mt: 4,
	},
	reachOutTitle: {
		fontSize: { xs: '1rem', md: '1.1rem' },
		fontWeight: 600,
		color: 'white',
		mb: 1,
	},
	reachOutText: {
		color: '#a3a3a3',
		fontSize: '0.9rem',
		mb: 2,
	},
	outlinedButton: {
		marginTop: '1.5rem',
		color: '#f9fafb',
		fontWeight: 800,
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.7rem 1rem',
		},
		borderRadius: '0.5rem',
		backgroundColor: '#1f2937',
		border: '1px solid #4b5563',
		textTransform: 'none',
		fontSize: '0.9rem',
		whiteSpace: 'nowrap',
		transition: 'background-color 150ms ease',
		'&:hover': {
			backgroundColor: '#374151',
			borderColor: '#4b5563',
		},
		'&.Mui-disabled': {
			color: '#f9fafb',
			opacity: 0.5,
			backgroundColor: '#1f2937',
			border: '1px solid #374151',
		},
	},
	formContainer: {
		background: '#17171799',
		borderRadius: '12px',
		padding: { xs: '1.5rem', md: '2rem' },
		border: '1px solid rgba(255, 255, 255, 0.1)',
		height: '100%',
	},
	formTitle: {
		fontSize: { xs: '1.1rem', md: '1.25rem' },
		fontWeight: 600,
		color: 'white',
		mb: 3,
	},
	textField: {
		'& .MuiOutlinedInput-root': {
			color: 'white',
			'& fieldset': {
				borderColor: 'rgba(255, 255, 255, 0.2)',
			},
			'&:hover fieldset': {
				borderColor: 'rgba(255, 255, 255, 0.3)',
			},
			'&.Mui-focused fieldset': {
				borderColor: '#5eead4',
			},
		},
		'& .MuiInputLabel-root': {
			color: '#a3a3a3',
			'&.Mui-focused': {
				color: '#5eead4',
			},
		},
		'& .MuiSelect-icon': {
			color: '#a3a3a3',
		},
		'& .MuiMenuItem-root': {
			color: '#101010',
		},
		mb: 2,
	},
	primaryButton: {
		marginTop: '1.5rem',
		color: '#f9fafb',
		fontWeight: 800,
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.7rem 1rem',
		},
		borderRadius: '0.5rem',
		backgroundColor: '#1f2937',
		border: '1px solid #4b5563',
		textTransform: 'none',
		fontSize: '0.9rem',
		whiteSpace: 'nowrap',
		transition: 'background-color 150ms ease',
		'&:hover': {
			backgroundColor: '#374151',
			borderColor: '#4b5563',
		},
		'&.Mui-disabled': {
			color: '#f9fafb',
			opacity: 0.5,
			backgroundColor: '#1f2937',
			border: '1px solid #374151',
		},
	},
	decorationContainer: {
		position: 'absolute',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
		zIndex: 1,
		pointerEvents: 'none',
		display: { xs: 'none', md: 'block' }, // Hide decorations on mobile for better performance
	},
	circle1: {
		position: 'absolute',
		width: { sm: '200px', md: '300px' },
		height: { sm: '200px', md: '300px' },
		borderRadius: '50%',
		background: 'rgba(17, 94, 89, 0.1)',
		top: '10%',
		right: '5%',
	},
	circle2: {
		position: 'absolute',
		width: { sm: '250px', md: '400px' },
		height: { sm: '250px', md: '400px' },
		borderRadius: '50%',
		background: 'rgba(17, 94, 89, 0.05)',
		bottom: '5%',
		left: '5%',
	},
	glowDot1: {
		position: 'absolute',
		width: '10px',
		height: '10px',
		borderRadius: '50%',
		background: '#5eead4',
		boxShadow: '0 0 20px 5px rgba(94, 234, 212, 0.3)',
		top: '30%',
		left: '15%',
	},
	glowDot2: {
		position: 'absolute',
		width: '15px',
		height: '15px',
		borderRadius: '50%',
		background: '#5eead4',
		boxShadow: '0 0 30px 8px rgba(94, 234, 212, 0.3)',
		bottom: '25%',
		right: '20%',
	},
	glowLine1: {
		position: 'absolute',
		width: { sm: '150px', md: '200px' },
		height: '1px',
		background: 'linear-gradient(90deg, transparent, rgba(94, 234, 212, 0.5), transparent)',
		transform: 'rotate(45deg)',
		top: '35%',
		left: '25%',
	},
	glowLine2: {
		position: 'absolute',
		width: { sm: '180px', md: '250px' },
		height: '1px',
		background: 'linear-gradient(90deg, transparent, rgba(94, 234, 212, 0.5), transparent)',
		transform: 'rotate(-30deg)',
		bottom: '20%',
		right: '15%',
	},
	alertStyle: {
		backgroundColor: '#115e59',
		color: 'white',
		'& .MuiAlert-icon': {
			color: 'white',
		},
	},
};

export default contactStyle;