const cookieBannerStyle = {
	bannerContainer: {
		position: 'fixed',
		bottom: '20px',
		left: '20px',
		transform: 'none',
		maxWidth: '90%',
		width: '500px',
		zIndex: 9999,
		backgroundColor: '#171717',
		borderRadius: '12px',
		boxShadow: '0 10px 25px rgba(0, 0, 0, 0.3)',
		border: '1px solid rgba(94, 234, 212, 0.2)',
		padding: '24px',
		backdropFilter: 'blur(10px)',
	},
	titleText: {
		color: 'white',
		fontSize: '1.5rem',
		fontWeight: 700,
		marginBottom: '16px',
	},
	descriptionText: {
		color: '#a3a3a3',
		fontSize: '0.9rem',
		lineHeight: 1.6,
		marginBottom: '24px',
	},
	buttonContainer: {
		display: 'flex',
		gap: '12px',
		marginTop: '8px',
		flexDirection: { xs: 'column', sm: 'row' },
	},
	customizeButton: {
		background: 'transparent',
		border: '1px solid rgba(255, 255, 255, 0.2)',
		color: 'white',
		fontSize: '0.9rem',
		padding: '10px 20px',
		borderRadius: '8px',
		cursor: 'pointer',
		fontWeight: 600,
		transition: 'all 0.2s ease',
		'&:hover': {
			backgroundColor: 'rgba(255, 255, 255, 0.05)',
			borderColor: 'rgba(255, 255, 255, 0.3)',
		},
		flex: 1,
	},
	acceptButton: {
		backgroundColor: '#115e59',
		color: '#f9fafb',
		borderRadius: '0.5rem',
		padding: {
			xs: '0.25rem 0.5rem',
			sm: '0.375rem 0.75rem',
			md: '0.25rem 0.5rem',
		},
		textTransform: 'none',
		fontSize: '1rem',
		whiteSpace: 'nowrap',
		border: '1px solid #0d9488',
		transition: 'all 150ms ease',
		'&:hover': {
			backgroundColor: '#0f766e',
		},
	},
	closeButton: {
		position: 'absolute',
		top: '16px',
		right: '16px',
		background: 'transparent',
		border: 'none',
		color: '#a3a3a3',
		cursor: 'pointer',
		padding: '4px',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		'&:hover': {
			color: 'white',
			backgroundColor: 'rgba(255, 255, 255, 0.1)',
		},
	},
	prefContainer: {
		marginTop: '16px',
		display: 'none',
		flexDirection: 'column',
		gap: '12px',
	},
	prefOption: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '12px',
		borderRadius: '8px',
		backgroundColor: 'rgba(255, 255, 255, 0.05)',
		border: '1px solid rgba(255, 255, 255, 0.1)',
	},
	prefText: {
		color: 'white',
		fontSize: '0.9rem',
	},
	prefSwitch: {
		position: 'relative',
		display: 'inline-block',
		width: '40px',
		height: '24px',
	},
	prefSlider: {
		position: 'absolute',
		cursor: 'pointer',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: '#ccc',
		transition: '0.4s',
		borderRadius: '12px',
		'&:before': {
			position: 'absolute',
			content: '""',
			height: '16px',
			width: '16px',
			left: '4px',
			bottom: '4px',
			backgroundColor: 'white',
			transition: '0.4s',
			borderRadius: '50%',
		},
	},
	prefInput: {
		opacity: 0,
		width: 0,
		height: 0,
		'&:checked + span': {
			backgroundColor: '#5eead4',
		},
		'&:checked + span:before': {
			transform: 'translateX(16px)',
		},
	},
	active: {
		display: 'flex',
	},
};

export default cookieBannerStyle;
