import theme from '../../../theme';

const notFoundStyle = {
  section: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    background: '#101010',
    position: 'relative',
    overflow: 'hidden',
  },
  backgroundGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: 'radial-gradient(50% 50% at 50% 50%, rgba(17, 94, 89, 0.15) 0%, rgba(0, 0, 0, 0) 100%)',
    zIndex: 1,
  },
  container: {
    maxWidth: '800px',
    width: '100%',
    position: 'relative',
    zIndex: 5,
    textAlign: 'center',
  },
  contentBox: {
    padding: '3rem',
    borderRadius: '16px',
    backdropFilter: 'blur(10px)',
  },
  errorCode: {
    fontSize: { xs: '6rem', md: '8rem' },
    fontWeight: 'bold',
    color: 'white',
    lineHeight: 0.9,
    mb: 2,
    background: 'white',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  title: {
    fontSize: { xs: '1.8rem', md: '2.5rem' },
    fontWeight: 600,
    color: 'white',
    mb: 2,
  },
  description: {
    fontSize: { xs: '1rem', md: '1.1rem' },
    color: '#a3a3a3',
    mb: 4,
    maxWidth: '600px',
    margin: '0 auto 2rem',
  },
  linkContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    mb: 4,
    width: '100%',
  },
  resourceList: {
    listStyleType: 'disc',
    textAlign: 'left',
    color: '#a3a3a3',
    width: 'fit-content',
    margin: '0 auto',
    paddingLeft: { xs: '30px', md: '160px' }, // Added padding to move links to the right
  },
  listItem: {
    mb: 1,
  },
  linkStyle: {
    color: '#5eead4',
    textDecoration: 'none',
    '&:hover': {
      textDecoration: 'underline',
    },
  },
  buttonContainer: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
    justifyContent: 'center',
    mt: 3,
  },
  primaryButton: {
    backgroundColor: '#115e59',
    color: '#f9fafb',
    padding: '0.75rem 2rem',
    borderRadius: '0.375rem',
    fontWeight: 600,
    textTransform: 'none',
    fontSize: '1rem',
    border: '1px solid #0d9488',
    transition: 'all 0.3s ease',
    '&:hover': {
      backgroundColor: '#0f766e',
      transform: 'translateY(-2px)',
    },
  },
  secondaryButton: {
    background: 'transparent',
    color: 'white',
    padding: '0.75rem 2rem',
    borderRadius: '0.375rem',
    fontWeight: 600,
    textTransform: 'none',
    fontSize: '1rem',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    transition: 'all 0.3s ease',
    '&:hover': {
      borderColor: 'rgba(255, 255, 255, 0.3)',
      background: 'rgba(255, 255, 255, 0.05)',
      transform: 'translateY(-2px)',
    },
  },
  decorationContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
    pointerEvents: 'none',
  },
  circle1: {
    position: 'absolute',
    width: '200px',
    height: '200px',
    borderRadius: '50%',
    background: 'rgba(17, 94, 89, 0.1)',
    top: '10%',
    right: '5%',
  },
  circle2: {
    position: 'absolute',
    width: '300px',
    height: '300px',
    borderRadius: '50%',
    background: 'rgba(17, 94, 89, 0.05)',
    bottom: '5%',
    left: '5%',
  },
  glowDot1: {
    position: 'absolute',
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: '#5eead4',
    boxShadow: '0 0 20px 5px rgba(94, 234, 212, 0.3)',
    top: '20%',
    left: '20%',
  },
  glowDot2: {
    position: 'absolute',
    width: '15px',
    height: '15px',
    borderRadius: '50%',
    background: '#5eead4',
    boxShadow: '0 0 30px 8px rgba(94, 234, 212, 0.3)',
    bottom: '30%',
    right: '15%',
  },
  glowLine1: {
    position: 'absolute',
    width: '150px',
    height: '1px',
    background: 'linear-gradient(90deg, transparent, rgba(94, 234, 212, 0.5), transparent)',
    transform: 'rotate(45deg)',
    top: '40%',
    left: '20%',
  },
  glowLine2: {
    position: 'absolute',
    width: '200px',
    height: '1px',
    background: 'linear-gradient(90deg, transparent, rgba(94, 234, 212, 0.5), transparent)',
    transform: 'rotate(-30deg)',
    bottom: '25%',
    right: '10%',
  },
};

export default notFoundStyle;