import theme from '../../../../theme';

const heroSectionStyle = {
	mainContainer: {
		width: '100%',
		padding: { xs: '1rem 1rem 2rem', md: '7rem 2rem 5rem' },
		position: 'relative' as const,
		overflow: 'hidden',
		background: theme.palette.background.default,
	},
	contentWrapper: {
		marginTop: '3rem',
		maxWidth: '1200px',
		margin: '0 auto',
		display: 'flex',
		flexDirection: 'column' as const,
		alignItems: 'center',
		background: theme.palette.background.paper,
		padding: { xs: '1.5rem', sm: '2rem', md: '2.5rem' },
		borderRadius: '2rem',
	},
	chip: {
		background: theme.palette.secondary.main,
		color: theme.palette.text.primary,
		fontWeight: 'bold',
		marginBottom: '2rem',
		borderRadius: '2rem',
		padding: '0.7rem 1.5rem',
		boxShadow: '0rem 0.25rem 0.375rem rgba(0, 0, 0, 0.2)',
		display: 'inline-block',
		maxWidth: { xs: '95%', sm: '650px' },
		textAlign: 'center' as const,
	},
	chipTypography: {
		fontWeight: 'bold' as const,
		textAlign: 'center' as const,
		fontSize: '0.95rem',
	},
	textContainer: {
		display: 'flex',
		flexDirection: 'column' as const,
		color: theme.palette.text.primary,
		maxWidth: '800px',
		marginBottom: '2.5rem',
		alignItems: 'center',
	},
	heading: {
		fontWeight: '700',
		lineHeight: '1.2',
		marginBottom: '1rem',
		fontSize: { xs: '1.75rem', sm: '2rem', md: '2.5rem' },
		color: theme.palette.text.primary,
		textShadow: '0px 2px 4px rgba(0, 0, 0, 0.3)',
		textAlign: 'center' as const,
	},
	subheading: {
		fontWeight: '500',
		fontSize: { xs: '1.1rem', sm: '1.2rem', md: '1.4rem' },
		marginBottom: '1.25rem',
		color: theme.palette.text.primary,
		textAlign: 'center' as const,
	},
	description: {
		fontSize: { xs: '0.95rem', sm: '1rem', md: '1.1rem' },
		lineHeight: '1.6',
		color: theme.palette.text.secondary,
		maxWidth: '700px',
		textAlign: 'center' as const,
	},
	statsContainer: {
		marginBottom: '2.5rem',
		maxWidth: '900px',
		justifyContent: 'center',
	},
	statItem: {
		display: 'flex',
		flexDirection: 'column' as const,
		alignItems: 'center',
		textAlign: 'center' as const,
		color: theme.palette.text.primary,
		padding: '1rem',
		borderRadius: '0.5rem',
	},
	statIconContainer: {
		width: '3rem',
		height: '3rem',
		borderRadius: '50%',
		backgroundColor: theme.palette.secondary.main,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: '0.75rem',
		boxShadow: '0 0.25rem 0.5rem rgba(0, 0, 0, 0.2)',
	},
	statIconSvg: {
		fontSize: '1.75rem',
		color: theme.palette.text.primary,
	},
	statValue: {
		fontWeight: 'bold',
		fontSize: '1.5rem',
		marginBottom: '0.25rem',
		color: theme.palette.primary.light,
	},
	statLabel: {
		fontSize: '0.85rem',
		color: theme.palette.text.secondary,
		opacity: 0.9,
		lineHeight: '1.3',
	},
	button: {
		color: theme.palette.text.primary,
		background: theme.palette.primary.main,
		fontWeight: 'bold',
		padding: '0.75rem 2rem',
		borderRadius: '2rem',
		fontSize: '1rem',
		boxShadow: '0 0.25rem 0.5rem rgba(0, 0, 0, 0.3)',
		'&:hover': {
			background: theme.palette.primary.dark,
		},
		textTransform: 'none',
		letterSpacing: '0.5px',
		alignSelf: 'center',
		'&:focus': {
			boxShadow: `0 0 0 3px rgba(${parseInt(theme.palette.primary.main.slice(1, 3), 16)},
			${parseInt(theme.palette.primary.main.slice(3, 5), 16)},
			${parseInt(theme.palette.primary.main.slice(5, 7), 16)}, 0.6),
			0 0.25rem 0.5rem rgba(0, 0, 0, 0.3)`,
			outline: 'none',
		},
	},
};

export default heroSectionStyle;
