import theme from '../../../../theme';

const heroSectionStyle = {
  mainContainer: {
    width: '100%',
    paddingTop: '5rem',
    paddingBottom: '5rem',
    position: 'relative',
    overflow: 'hidden',
    background: theme.palette.background.default,
  },
  contentWrapper: {
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: { xs: '1.5rem', sm: '2rem', md: '2.5rem' },
  },
  chip: {
    background: '#115e59',
    color: '#ffffff',
    fontWeight: 'bold',
    marginBottom: '2rem',
    borderRadius: '2rem',
    padding: '0.6rem 1.2rem',
    display: 'inline-block',
  },
  chipTypography: {
    fontWeight: 'bold',
    fontSize: '0.9rem',
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    color: theme.palette.text.primary,
    maxWidth: '800px',
    marginBottom: '3.5rem',
    textAlign: 'left',
  },
  heading: {
    fontWeight: '600',
    fontSize: { xs: '2rem', sm: '2.5rem', md: '3rem' },
    lineHeight: { xs: '1.2', md: '1.15' },
    color: '#ffffff',
    marginBottom: '1.5rem',
    textAlign: 'left',
  },
  subheading: {
    fontSize: { xs: '1.2rem', sm: '1.4rem', md: '1.5rem' },
    marginBottom: '1.5rem',
    color: '#fffff',
    fontWeight: '600',
    textAlign: 'left',
  },
  description: {
    fontSize: { xs: '1rem', sm: '1.1rem' },
    lineHeight: '1.7',
    color: '#94a3b8',
    textAlign: 'left',
    maxWidth: '700px',
  },
  statsContainer: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    gap: { xs: '1.5rem', md: '2rem' },
    width: '100%',
    marginBottom: '3.5rem',
  },
  statCard: {
    flex: 1,
    background: '#17171799',
    borderRadius: '16px',
    overflow: 'hidden',
    border: `1px solid ${theme.palette.divider}`,
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: '0 15px 30px rgba(0, 0, 0, 0.2)',
      borderColor: 'rgba(94, 234, 212, 0.3)',
    },
  },
  statContent: {
    padding: '1.5rem',
  },
  statValue: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '1rem',
    textAlign: 'left',
  },
  statDetails: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  statIconBox: {
    width: '2.5rem',
    height: '2.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0d9488',
    borderRadius: '6px',
    flexShrink: 0,
  },
  statIcon: {
    color: '#ffffff',
    fontSize: '1.6rem',
  },
  statLabel: {
    fontSize: '1rem',
    color: '#94a3b8',
    fontWeight: '500',
  },
  ctaButton: {
	marginTop: '1.5rem',
	color: '#f9fafb',
	fontWeight: 800,
	padding: {
		xs: '0.25rem 0.5rem',
		sm: '0.375rem 0.75rem',
		md: '0.7rem 1rem',
	},
	borderRadius: '0.5rem',
	backgroundColor: '#1f2937',
	border: '1px solid #4b5563',
	textTransform: 'none',
	fontSize: '0.9rem',
	whiteSpace: 'nowrap',
	transition: 'background-color 150ms ease',
	'&:hover': {
		backgroundColor: '#374151',
		borderColor: '#4b5563',
	},
	'&.Mui-disabled': {
		color: '#f9fafb',
		opacity: 0.5,
		backgroundColor: '#1f2937',
		border: '1px solid #374151',
	},
  },
};

export default heroSectionStyle;