import theme from '../../../../theme';

const stepsSectionStyle = {
   box: {
   	paddingTop: { sm: '1.5rem', xs: '0.5rem' },
   	paddingBottom: { sm: '2rem', xs: '1rem' },
   	marginTop: '0rem',
   	marginX: { xs: '1rem', sm: '0rem' },
       background: theme.palette.background.default,
   },
   container: {
   	maxWidth: '75rem',
   	marginX: 'auto',
   },
   title: {
   	fontWeight: '700',
   	fontSize: { xs: '1.4rem', sm: '2rem' },
   	marginBottom: { xs: '0.25rem', sm: '0.5rem' },
   	textAlign: 'center',
   	color: theme.palette.text.primary,
   },
   subtitle: {
   	fontWeight: '500',
   	fontSize: { xs: '0.85rem', sm: '1.1rem' },
   	marginBottom: { xs: '1rem', sm: '1.5rem' },
   	textAlign: 'center',
   	color: '#6B7280',
   },
   stepsIndicator: {
       display: 'flex',
       justifyContent: 'left',
       alignItems: 'left',
       marginBottom: { xs: '1rem', sm: '1.5rem' },
       gap: { xs: '2rem', sm: '3rem' },
       flexWrap: 'wrap',
   },
   stepDot: {
       width: { xs: '1.5rem', sm: '2rem' },
       height: { xs: '1.5rem', sm: '2rem' },
       borderRadius: '50%',
       display: 'flex',
       justifyContent: 'left',
       alignItems: 'left',
       fontSize: { xs: '0.8rem', sm: '0.9rem' },
       fontWeight: 'bold',
       color: theme.palette.text.primary,
   },
   gridContainer: {
   	marginTop: '0.5rem',
   	justifyContent: 'center',
   },
   card: {
   	borderRadius: { xs: '0.75rem', sm: '1rem' },
   	backgroundColor: '#17171799',
   	height: '100%',
   	display: 'flex',
   	flexDirection: 'column',
   	border: `1px solid ${theme.palette.divider}`,
       boxShadow: theme.customShadows?.card || '0 4px 12px rgba(0, 0, 0, 0.4)',
   },
   cardContent: {
   	display: 'flex',
   	flexDirection: 'column',
   	alignItems: 'left',
   	textAlign: 'left',
   	padding: { xs: '0.75rem', sm: '1.5rem 1.25rem' },
   	height: '100%',
   },
   cardStep: {
   	fontWeight: 'bold',
   	fontSize: { xs: '0.7rem', sm: '0.8rem' },
   	color: theme.palette.primary.main,
   	marginBottom: { xs: '0.5rem', sm: '0.75rem' },
   	textAlign: 'center',
       textTransform: 'uppercase',
       letterSpacing: '0.05rem',
   },
   iconContainer: {
   	width: { xs: '2.5rem', sm: '3rem' },
   	height: { xs: '2.5rem', sm: '3rem' },
   	borderRadius: '0.5rem',
   	background: theme.palette.secondary.main,
   	display: 'flex',
   	justifyContent: 'center',
   	alignItems: 'center',
   	marginBottom: { xs: '0.5rem', sm: '1rem' },
   },
   icon: {
   	fontSize: { xs: '1.2rem', sm: '1.8rem' },
   	color: theme.palette.text.primary,
   },
   cardTitle: {
   	fontWeight: '600',
   	fontSize: { xs: '14px', sm: '1.1rem' },
   	color: theme.palette.primary.light,
   	marginBottom: { xs: '0.5rem', sm: '0.75rem' },
   	textAlign: 'left',
   },
   cardDescription: {
   	fontSize: { xs: '12px', sm: '0.9rem' },
   	color: theme.palette.text.secondary,
   	lineHeight: 1.5,
   	textAlign: 'left',
   	flexGrow: 1,
   },
};

export default stepsSectionStyle;